package com.spaceagent.platform.project;
import com.fasterxml.jackson.databind.ObjectMapper;import com.spaceagent.platform.identity.api.IdentityOwnershipPort;import com.spaceagent.platform.memory.api.*;import com.spaceagent.platform.memory.application.MemoryApplicationService;import com.spaceagent.platform.memory.domain.*;import com.spaceagent.platform.memory.infrastructure.memory.*;import com.spaceagent.platform.project.api.*;import com.spaceagent.platform.project.application.*;import com.spaceagent.platform.project.domain.*;import com.spaceagent.platform.project.infrastructure.memory.*;import com.spaceagent.shared.exception.BusinessException;import com.spaceagent.shared.id.UuidGenerator;import org.junit.jupiter.api.*;import java.time.Instant;import java.util.*;import static org.assertj.core.api.Assertions.*;
class PlatformWorkspaceBlueprintApplicationTest{
 static final Instant NOW=Instant.parse("2026-08-23T01:00:00Z");Fixture f;
 @BeforeEach void setup(){f=new Fixture();}
 @Test void isolatesManagedAndLocalWorkspaces(){var managed=f.workspace.provision(new WorkspaceApplicationApi.ProvisionCommand("tenant-1","owner",f.project,f.task1,f.remote.id(),null));assertThat(managed.state()).isEqualTo(WorkspaceState.READY);assertThat(managed.worktreeRef()).startsWith("managed:");
  assertThatThrownBy(()->f.workspace.provision(new WorkspaceApplicationApi.ProvisionCommand("tenant-1","owner",f.project,f.task1,f.remote.id(),null))).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.getCode()).isEqualTo("WORKSPACE_ACTIVE_CONFLICT"));
  var delegated=f.workspace.provision(new WorkspaceApplicationApi.ProvisionCommand("tenant-1","owner",f.project,f.task1,f.remote.id(),null,"delegation:one"));assertThat(delegated.id()).isNotEqualTo(managed.id());assertThat(delegated.isolationKey()).isEqualTo("delegation:one");
  var local=f.workspace.provision(new WorkspaceApplicationApi.ProvisionCommand("tenant-1","owner",f.project,f.task2,f.local.id(),"HEAD"));assertThat(local.state()).isEqualTo(WorkspaceState.WAITING_FOR_BRIDGE);var cmds=f.workspace.pendingBridgeCommands(new WorkspaceApplicationApi.BridgeCommandsQuery("tenant-1","owner",f.bridge.bridge().id()));assertThat(cmds).hasSize(1);
  var ready=f.workspace.completeBridge(new WorkspaceApplicationApi.CompleteBridgeCommand("tenant-1","owner",cmds.get(0).id(),f.bridge.bridgeToken(),"localw_12345678","a".repeat(40),true,null));assertThat(ready.state()).isEqualTo(WorkspaceState.READY);assertThat(ready.worktreeKey()).isNotEqualTo(managed.worktreeKey());}
 @Test void blueprintVersionsSupersedeAndProjectMemoryTracksConfirmed(){var b1=f.blueprints.create(new ProjectBlueprintApplicationApi.CreateCommand("tenant-1","owner",f.project,f.remote.id(),null,ProjectBlueprintSource.USER,doc("v1")));f.blueprints.confirm(new ProjectBlueprintApplicationApi.ConfirmCommand("tenant-1","owner",f.project,b1.id()));var b2=f.blueprints.create(new ProjectBlueprintApplicationApi.CreateCommand("tenant-1","owner",f.project,f.remote.id(),null,ProjectBlueprintSource.USER,doc("v2")));var confirmed=f.blueprints.confirm(new ProjectBlueprintApplicationApi.ConfirmCommand("tenant-1","owner",f.project,b2.id()));assertThat(confirmed.versionNumber()).isEqualTo(2);assertThat(f.blueprints.list(new ProjectBlueprintApplicationApi.ListQuery("tenant-1","owner",f.project))).extracting(ProjectBlueprintApplicationApi.BlueprintView::status).containsExactly(ProjectBlueprintStatus.SUPERSEDED,ProjectBlueprintStatus.CONFIRMED);assertThat(f.memory.recall(new MemoryRecallCommand(MemoryScopeRef.project(f.project),List.of(MemoryKind.ARCHITECTURE),10))).singleElement().satisfies(m->assertThat(m.value()).contains("v2"));}
 static ProjectBlueprintDocument doc(String g){return new ProjectBlueprintDocument(g,List.of("req"),List.of("module"),List.of("boundary"),List.of(),Map.of("test","mvn test"),List.of("DB_URL"),List.of(),List.of(),List.of(),List.of(),List.of("done"),List.of());}
 static class Fixture{final UuidGenerator ids=new UuidGenerator();final InMemorySourceRepositoryRepository sourceRepo=new InMemorySourceRepositoryRepository();final MemoryApplicationService memory;final WorkspaceApplicationService workspace;final ProjectBlueprintApplicationService blueprints;final String project,task1,task2;final SourceRepository remote,local;final CreatedLocalWorkspaceBridgeView bridge;
  Fixture(){IdentityOwnershipPort identity=(t,u)->true;var pr=new InMemoryProjectRepository();var pm=new InMemoryProjectMembershipRepository();var tr=new InMemoryTaskRepository();ProjectAccessPolicy access=new ProjectAccessPolicy(pr,pm,identity, (t, u, w) -> {});var ps=new ProjectApplicationService(pr,pm,access,ids,()->NOW);var ts=new TaskApplicationService(tr,access,ids,()->NOW);project=ps.createProject(new CreateProjectCommand("tenant-1","owner","P",null)).id();task1=ts.createTask(new CreateTaskCommand("tenant-1","owner",project,null,"T1","g",null,List.of(),List.of())).id();task2=ts.createTask(new CreateTaskCommand("tenant-1","owner",project,null,"T2","g",null,List.of(),List.of())).id();Instant n=NOW;remote=new SourceRepository(ids.nextId(),project,"tenant-1",null,null,null,"42","r","https://x/r.git",null,"main",SourceRepositoryType.GITHUB,SourceRepositoryState.READY,SourceRepositoryVisibility.PUBLIC,"owner",n,n);var bridgeRepo=new InMemoryLocalWorkspaceBridgeRepository();var bridgeApi=new LocalWorkspaceBridgeApplicationService(bridgeRepo,access,ids,()->NOW);bridge=bridgeApi.register(new RegisterLocalWorkspaceBridgeCommand("tenant-1","owner","d","dev","root_abcdefgh"));local=new SourceRepository(ids.nextId(),project,"tenant-1",null,null,bridge.bridge().id(),"local","l",null,"root_abcdefgh","main",SourceRepositoryType.LOCAL,SourceRepositoryState.READY,SourceRepositoryVisibility.LOCAL,"owner",n,n);sourceRepo.save(remote);sourceRepo.save(local);memory=new MemoryApplicationService(new InMemoryMemoryCandidateRepository(),new InMemoryConsolidatedMemoryRepository(),ids,()->NOW);workspace=new WorkspaceApplicationService(new InMemoryWorkspaceRepository(),new InMemoryBridgeWorkspaceCommandRepository(),access,tr,sourceRepo,bridgeRepo,bridgeApi,r->{throw new AssertionError("MCP credential not expected");},new WorkspaceProvisioningGateway(){public ProvisionedWorkspace provision(Workspace w,SourceRepository s,String header){return new ProvisionedWorkspace("managed:"+w.id(),"b".repeat(40));}public void cleanup(Workspace w,SourceRepository s){}},ids,()->NOW);blueprints=new ProjectBlueprintApplicationService(new InMemoryProjectBlueprintRepository(),sourceRepo,access,memory,new ObjectMapper(),ids,()->NOW);}}
}
