import type { Language } from './types'
import { extraMessages } from './copyExtra'

export const languageOrder: Language[] = ['zh', 'ja', 'en']
export const languageLabels: Record<Language, string> = { zh: '中', ja: '日', en: 'EN' }

const messages: Record<string, [string, string, string]> = {
  administration: ['私有管理控制平面', '非公開管理コントロールプレーン', 'Private administration plane'],
  overview: ['态势总览', 'システム概要', 'System overview'],
  administrators: ['系统管理员', 'システム管理者', 'System administrator'],
  users: ['用户管理', 'ユーザー管理', 'User administration'],
  organizations: ['组织管理', '組織管理', 'Organizations'],
  resources: ['资源拓扑', 'リソース構成', 'Resource topology'],
  mcpRegistry: ['MCP 注册审核', 'MCP レジストリ審査', 'MCP Registry review'],
  cleanup: ['清理中心', 'クリーンアップ', 'Cleanup center'],
  credentials: ['凭据清单', '認証情報一覧', 'Credential inventory'],
  commands: ['命令中心', 'コマンド', 'Command center'],
  audit: ['审计证据', '監査証跡', 'Audit evidence'],
  returnToPlatform: ['返回用户平台 ↗', 'ユーザー画面へ ↗', 'Return to user plane ↗'],
  signOut: ['退出管理系统', '管理画面からログアウト', 'Sign out'],
  restoringSession: ['正在恢复安全管理会话', '安全な管理セッションを復元中', 'Restoring secure administrator session'],
  sessionRestoreFailed: ['暂时无法恢复原管理会话，请重新登录。', '管理セッションを復元できません。もう一度ログインしてください。', 'The previous administrator session could not be restored. Sign in again.'],
  loginTitle: ['进入系统控制平面。', 'システム制御へ。', 'Enter system control.'],
  loginCopy: ['管理身份独立于普通用户和组织角色。使用服务器环境中配置的账号和密码登录。', '管理者 ID は通常ユーザーや組織とは独立しています。サーバー環境で設定したアカウントとパスワードでログインしてください。', 'Administrator identity is independent of users and organizations. Sign in with the account and password configured on the server.'],
  configuredAccountHint: ['管理员账号和密码由服务器 .env 管理。修改配置并重启后生效，旧会话会失效。', '管理者アカウントとパスワードはサーバーの .env で管理します。変更後に再起動すると旧セッションは無効になります。', 'Administrator credentials are managed in the server .env. Change configuration and restart; old sessions are revoked.'],
  authenticatedSessionRequired: ['需要有效管理员会话', '有効な管理者セッションが必要です', 'Valid administrator session required'],
  loginName: ['管理员账号', '管理者アカウント', 'Administrator login'],
  password: ['密码', 'パスワード', 'Password'],
  continue: ['继续验证', '検証を続ける', 'Continue verification'],
  totpTitle: ['验证第二因素。', '第2要素を確認。', 'Verify second factor.'],
  totpCopy: ['输入认证器中当前的 6 位动态验证码。', '認証アプリの現在の6桁コードを入力してください。', 'Enter the current six-digit code from your authenticator.'],
  verify: ['验证并进入', '確認して入る', 'Verify and enter'],
  recoveryCode: ['恢复码', 'リカバリーコード', 'Recovery code'],
  useRecoveryCode: ['改用恢复码', 'リカバリーコードを使用', 'Use a recovery code'],
  useTotp: ['改用 TOTP', 'TOTP を使用', 'Use TOTP'],
  back: ['返回账号输入', 'アカウント入力へ戻る', 'Back to login'],
  securityBoundaryCopy: ['普通用户 JWT 与组织 OWNER/ADMIN 角色在这里无效。', '通常ユーザー JWT と組織 OWNER/ADMIN ロールはここでは無効です。', 'Normal user JWTs and Organization OWNER/ADMIN roles are invalid here.'],
  overviewTitle: ['系统控制台。', 'システム制御。', 'System control.'],
  overviewCopy: ['观察全局资源、身份活动、运行状态和风险证据。所有数字都来自后端权威投影。', '全リソース、ID アクティビティ、実行状態、リスク証跡を監視します。数値はすべて権威ある投影です。', 'Observe global resources, identity activity, runtime health, and risk evidence from authoritative projections.'],
  onlineUsers: ['当前在线人数', '現在オンライン', 'Recently active users'],
  totalUsers: ['累计平台用户', '累計ユーザー', 'Cumulative users'],
  runningWork: ['执行中任务 / Run', '実行中タスク / Run', 'Active work / Runs'],
  organizationsMetric: ['活跃组织', 'アクティブ組織', 'Active organizations'],
  unknownEffects: ['UNKNOWN 影响', 'UNKNOWN 効果', 'Unknown effects'],
  registeredWindow: ['窗口新增用户', '期間内の新規ユーザー', 'Registered in window'],
  platformTopology: ['平台资源拓扑', 'プラットフォーム構成', 'Platform resource topology'],
  securityBoundary: ['安全边界', 'セキュリティ境界', 'Security perimeter'],
  staleEvidence: ['当前展示的是缓存投影，平台实时读取暂不可用。', 'キャッシュ投影を表示しています。ライブ読み取りは利用できません。', 'Showing cached projection; live platform reads are unavailable.'],
  governanceTitle: ['Agent 版本治理', 'Agent バージョン統制', 'Agent version governance'],
  governanceCopy: ['只读展示跨组织的审核与调度计数；不返回提示词、版本正文或操作者详情。', '組織横断の審査・スケジュール件数のみを表示し、プロンプト、バージョン本文、担当者情報は返しません。', 'Read-only cross-organization review and scheduling counts; prompts, version content, and operator details are never returned.'],
  openReviews: ['待处理审核', '未処理レビュー', 'Open reviews'],
  reviewedReviews: ['已完成审核', '完了レビュー', 'Reviewed'],
  approvedReviews: ['已批准', '承認済み', 'Approved'],
  rejectedReviews: ['已拒绝', '却下済み', 'Rejected'],
  scheduledActions: ['已调度操作', '予定済み操作', 'Scheduled actions'],
  claimedActions: ['执行中操作', '実行中操作', 'Claimed actions'],
  unknownActions: ['UNKNOWN 操作', 'UNKNOWN 操作', 'Unknown actions'],
  governanceUnavailable: ['版本治理证据暂不可用。', 'バージョン統制の証跡を取得できません。', 'Version governance evidence is unavailable.'],
  governanceReadOnly: ['只读全局证据', '読み取り専用の全体証跡', 'Read-only global evidence'],
  usersTitle: ['用户控制。', 'ユーザー制御。', 'User control.'],
  usersCopy: ['全局检索用户、检查组织成员关系，执行创建、暂停、恢复与受控删除流程。', 'グローバル検索、組織メンバーシップ、作成・停止・復元・削除フローを管理します。', 'Search globally, inspect memberships, and execute controlled create, suspend, restore, and deletion workflows.'],
  searchUsers: ['搜索用户名、显示名或 ID', 'ユーザー名、表示名、ID を検索', 'Search login, display name, or ID'],
  createUser: ['创建用户', 'ユーザー作成', 'Create user'],
  noUsers: ['没有符合条件的用户。', '該当するユーザーはいません。', 'No users match the filter.'],
  user: ['用户', 'ユーザー', 'User'], status: ['状态', '状態', 'Status'], memberships: ['组织', '組織', 'Memberships'], lastSeen: ['最近活动', '最終活動', 'Last active'], sessions: ['会话', 'セッション', 'Sessions'],
  organizationTitle: ['组织索引。', '組織インデックス。', 'Organization index.'],
  organizationCopy: ['查看用户组、唯一所有者、活跃成员和删除状态。组织写操作仍由后端权威契约控制。', '組織、唯一 OWNER、メンバー、削除状態を確認します。書き込みは権威ある契約が制御します。', 'Inspect groups, unique ownership, active membership, and deletion state. Mutations remain backend-authoritative.'],
  createOrganization: ['创建组织', '組織を作成', 'Create organization'],
  editOrganization: ['修改组织', '組織を編集', 'Edit organization'],
  deleteOrganization: ['删除组织', '組織を削除', 'Delete organization'],
  authorizeStorageCleanup: ['授权继续物理清理', '物理クリーンアップを承認', 'Authorize physical cleanup'],
  storageCleanupWarning: ['此操作授权后台继续清理组织的物理代码存储，不是删除逻辑目录。清理后可能无法恢复。', '組織の物理コードストレージ削除を承認します。論理フォルダー削除ではなく、復元できない場合があります。', 'This authorizes physical organization code cleanup, not logical folder removal. Deleted storage may not be recoverable.'],
  ownerUserId: ['所有者用户 ID', '所有者ユーザー ID', 'Owner user ID'],
  organizationDeleteCopy: ['删除会进入 Identity 管理的耐久清理流程，不会在 HTTP 请求中级联删除。', '削除は Identity 所有の永続クリーンアップへ入り、HTTP 内でカスケード削除しません。', 'Deletion enters the Identity-owned durable cleanup workflow; it never cascades inside the HTTP request.'],
  organizationMembers: ['组织成员', '組織メンバー', 'Organization members'],
  addMember: ['添加/重新激活成员', 'メンバーを追加・再有効化', 'Add or reactivate member'],
  changeRole: ['修改角色', 'ロールを変更', 'Change role'],
  removeMember: ['移除成员', 'メンバーを削除', 'Remove member'],
  transferOwner: ['转移 OWNER', 'OWNER を移譲', 'Transfer OWNER'],
  memberSearch: ['搜索成员姓名、账号或用户 ID', '名前、アカウント、ユーザー ID を検索', 'Search member name, login, or user ID'],
  noMembers: ['没有符合条件的成员。', '該当するメンバーはいません。', 'No members match the filter.'],
  memberRole: ['成员角色', 'メンバーロール', 'Member role'],
  ownerProtected: ['必须通过显式 OWNER 转移修改', '明示的な OWNER 移譲が必要です', 'Requires explicit OWNER transfer'],
  resourceTitle: ['资源态势。', 'リソース状態。', 'Resource posture.'],
  resourceCopy: ['聚合各权威模块的全局资源和运行健康，不让 Admin Web 直接访问业务数据库。', '各所有モジュールの状態を集約し、Admin Web から業務 DB へ直接アクセスしません。', 'Aggregate owner-module resource health without direct business database access.'],
  credentialsTitle: ['凭据清单。', '認証情報一覧。', 'Credential inventory.'],
  credentialsCopy: ['仅展示配置位置、认证类型、掩码提示和密钥版本；永不返回明文或密文。', '設定場所、方式、マスク、鍵バージョンのみ表示し、秘密値は返しません。', 'Show configuration location, auth type, masked hints, and key versions—never plaintext or ciphertext.'],
  commandsTitle: ['命令调和。', 'コマンド照合。', 'Command reconciliation.'],
  commandsCopy: ['按命令 ID 查询终态。UNKNOWN 只能调和，禁止重复派发。', 'コマンド ID で終端状態を確認します。UNKNOWN は照合のみで再送しません。', 'Query terminal evidence by command ID. UNKNOWN may be reconciled, never blindly redispatched.'],
  auditTitle: ['审计证据。', '監査証跡。', 'Audit evidence.'],
  auditCopy: ['敏感读取和修改均形成追加式证据，不包含密码、Token、正文或原始网络标识。', '機密読み取りと変更は追記専用証跡になり、秘密値や本文は含みません。', 'Sensitive reads and mutations append evidence without passwords, tokens, content, or raw network identifiers.'],
  search: ['搜索', '検索', 'Search'], retry: ['重试', '再試行', 'Retry'], loading: ['正在读取权威数据', '権威データを読み込み中', 'Loading authoritative data'],
  readOnly: ['只读', '読み取り専用', 'Read only'], previous: ['上一页', '前へ', 'Previous'], next: ['下一页', '次へ', 'Next'],
  activeAgent: ['关联 Agent', '関連エージェント', 'Linked Agents'], providerResources: ['模型提供商', 'モデルプロバイダ', 'Model providers'],
  associationPending: ['后端尚未提供按用户过滤的 Provider/Agent 明细接口。不会用不完整的前端全量抓取代替。', 'ユーザー別 Provider/Agent API は未公開です。不完全な全件取得では代替しません。', 'Owner-filtered Provider/Agent APIs are not exposed yet; the UI will not substitute incomplete client-side scans.'],
  suspend: ['暂停用户', 'ユーザー停止', 'Suspend user'], restore: ['恢复用户', 'ユーザー復元', 'Restore user'], deletionPreflight: ['删除预检', '削除プリフライト', 'Deletion preflight'], requestDeletion: ['提交删除作业', '削除ジョブを要求', 'Request deletion job'],
  operationReason: ['操作原因', '操作理由', 'Operation reason'], recentMfa: ['最近 MFA', '直近 MFA', 'Recent MFA'], confirm: ['确认并记录命令', '確認して記録', 'Confirm and record'], cancel: ['取消', 'キャンセル', 'Cancel'],
  activationWarning: ['激活引用只在首次成功响应中展示一次，请通过受控渠道交付。', 'アクティベーション参照は初回成功時に一度だけ表示されます。', 'The activation reference appears only in the first successful response. Deliver it through a controlled channel.'],
  commandId: ['命令 ID', 'コマンド ID', 'Command ID'], reconcile: ['调和 UNKNOWN', 'UNKNOWN を照合', 'Reconcile UNKNOWN'],
  commandLookupEmpty: ['输入命令 ID 读取真实命令证据。后端不提供无界命令列表。', 'コマンド ID を入力して証跡を取得します。無制限の一覧 API はありません。', 'Enter a command ID to read authoritative evidence. The backend exposes no unbounded command list.'],
  noCommands: ['没有符合筛选条件的命令。', '条件に一致するコマンドはありません。', 'No commands match the filter.'],
  cleanupTitle: ['全局清理控制。', 'グローバルクリーンアップ。', 'Global cleanup control.'],
  cleanupCopy: ['统一查看用户与组织清理作业、步骤进度、阻断原因和下一次执行时间。BLOCKED 不提供盲目重试。', 'ユーザーと組織のジョブ、進捗、ブロッカー、次回実行を確認します。BLOCKED は無条件再試行しません。', 'Inspect User and Organization cleanup jobs, progress, blockers, and next attempts. BLOCKED jobs are never blindly retried.'],
  blockerSummary: ['阻断原因聚合', 'ブロッカー集計', 'Blocker aggregation'],
  mcpRegistryTitle: ['MCP 注册审核。', 'MCP レジストリ審査。', 'MCP Registry review.'],
  mcpRegistryCopy: ['同步官方 Registry 的不可变快照，审查兼容候选，并且只在明确批准后发布到本地市场。同步本身不会安装或执行任何 MCP。', '公式 Registry の不変スナップショットを同期し、互換候補を審査します。明示的な承認後にのみローカル市場へ公開され、同期だけで MCP が導入・実行されることはありません。', 'Synchronize immutable official Registry snapshots, review compatible candidates, and publish to the local marketplace only after explicit approval. Synchronization never installs or executes an MCP.'],
  mcpRegistryLoadFailed: ['无法加载 MCP Registry 审核数据', 'MCP Registry 審査データを読み込めません', 'Unable to load MCP Registry review data'],
  mcpRegistryCommandFailed: ['MCP Registry 管理命令失败', 'MCP Registry 管理コマンドに失敗しました', 'MCP Registry administration command failed'],
  latestSync: ['最近同步', '最新の同期', 'Latest synchronization'],
  requestRegistrySync: ['请求同步', '同期を要求', 'Request synchronization'],
  searchRegistryCandidates: ['搜索名称、版本或来源', '名前、バージョン、ソースを検索', 'Search name, version, or source'],
  reviewState: ['审核状态', '審査状態', 'Review state'],
  syncState: ['同步状态', '同期状態', 'Synchronization state'],
  reviewCandidates: ['审核候选', '審査候補', 'Review candidates'],
  syncJobs: ['同步任务', '同期ジョブ', 'Synchronization jobs'],
  noRegistryCandidates: ['当前没有符合条件的审核候选。', '該当する審査候補はありません。', 'No review candidates match this view.'],
  noRegistryJobs: ['暂无同步任务。', '同期ジョブはありません。', 'No synchronization jobs yet.'],
  approveCandidate: ['批准并发布', '承認して公開', 'Approve and publish'],
  rejectCandidate: ['拒绝候选', '候補を拒否', 'Reject candidate'],
  noCleanupJobs: ['没有符合条件的清理作业。', '該当するクリーンアップジョブはありません。', 'No cleanup jobs match the filter.'],
  cleanupNoBlindRetry: ['清理中心只展示权威状态。UNKNOWN/BLOCKED 必须先在对应 owner 模块完成调和，不能从浏览器直接重跑。', '権威状態のみ表示します。UNKNOWN/BLOCKED は所有モジュールで照合後に処理し、ブラウザから直接再実行しません。', 'This surface shows authoritative state only. UNKNOWN/BLOCKED must be reconciled by the owning module and cannot be rerun from the browser.'],
  preflightBlockers: ['删除阻断项', '削除ブロッカー', 'Deletion blockers'],
  preflightRequired: ['提交删除作业前，必须先完成一次无阻断的删除预检。', '削除ジョブの前に、ブロッカーなしのプリフライトが必要です。', 'A blocker-free deletion preflight is required before requesting the cleanup job.'],
  noActor: ['系统/未知', 'システム/不明', 'System/unknown'],
  administratorsTitle: ['唯一系统管理员。', '唯一のシステム管理者。', 'Singleton system administrator.'],
  administratorsCopy: ['平台只允许一个不属于任何组织的最高权限身份。这里仅管理当前身份的恢复码和活跃 Session。', 'プラットフォームは組織に属さない最高権限 ID を1つだけ許可します。ここでは復旧コードと有効な Session のみを管理します。', 'The platform permits exactly one highest-privilege identity outside every Organization. Manage only its recovery codes and active Sessions here.'],
  administrator: ['系统管理员', 'システム管理者', 'System administrator'],
  currentAdministrator: ['当前系统管理员', '現在のシステム管理者', 'current system administrator'], administratorSessions: ['管理员 Session', '管理者 Session', 'Administrator sessions'],
  currentSession: ['当前 Session', '現在の Session', 'Current session'], revokeSession: ['撤销 Session', 'Session を取り消す', 'Revoke session'],
  recoveryCodes: ['恢复码', 'リカバリーコード', 'Recovery codes'],
  rotateRecoveryCodes: ['轮换恢复码', '復旧コードをローテーション', 'Rotate recovery codes'],
  rotateRecoveryCodesCopy: ['轮换会立即废止全部旧恢复码并生成 8 枚新码。需要当前密码和最近一次 TOTP 验证。', 'ローテーションすると旧コードはすべて無効になり、8個の新しいコードが生成されます。現在のパスワードと直近の TOTP が必要です。', 'Rotation immediately invalidates every old code and generates eight replacements. Current password and recent TOTP are required.'],
  oneTimeRecoveryCodes: ['一次性恢复码', '一度だけ表示される復旧コード', 'One-time recovery codes'],
  recoveryCodesWarning: ['这些恢复码只在本次成功响应中展示。请立即保存到独立的安全系统；浏览器不会持久化。', 'この復旧コードは今回の成功応答でのみ表示されます。別の安全な保管先へ直ちに保存してください。ブラウザには保存されません。', 'These recovery codes appear only in this successful response. Store them immediately in a separate secure system; the browser does not persist them.'],
  passwordChangeTitle: ['必须修改临时密码。', '一時パスワードの変更が必要です。', 'Temporary password change required.'],
  passwordChangeCopy: ['完成密码修改前不能进入管理控制平面。新密码至少 14 位，并包含大小写字母、数字和符号。', '変更完了まで管理画面は利用できません。14文字以上で大小文字、数字、記号が必要です。', 'The control plane remains unavailable until you set a 14+ character password with upper, lower, digit, and symbol.'],
  currentPassword: ['当前/临时密码', '現在/一時パスワード', 'Current / temporary password'], newPassword: ['新密码', '新しいパスワード', 'New password'],
  confirmPassword: ['确认新密码', '新しいパスワードを確認', 'Confirm new password'], changePassword: ['修改密码并重新登录', '変更して再ログイン', 'Change password and sign in again'],
  passwordMismatch: ['两次输入的新密码不一致。', '新しいパスワードが一致しません。', 'The new passwords do not match.'], passwordChangeFailed: ['密码修改失败。', 'パスワード変更に失敗しました。', 'Password change failed.'],
  passwordChangeLogout: ['修改成功会提升凭据版本并撤销所有旧 Session，随后必须重新登录。', '成功すると資格情報バージョンが上がり、全 Session が失効します。再ログインが必要です。', 'Success increments the credential version and revokes every old session; you must sign in again.'],
  resourceAssociation: ['用户资源关联', 'ユーザー資源関連', 'User resource associations'], cleanupJob: ['删除清理作业', '削除クリーンアップ', 'Deletion cleanup job'],
  resourceDrilldown: ['完整资源下钻', '全リソース詳細', 'Full resource drill-down'],
  resourceContentBoundary: ['这里只展示归属、状态、时间、计数和安全错误码；不会返回提示词、消息、文档正文、文件路径、Tool 参数/结果或凭据。', '所有・状態・時刻・件数・安全なエラーコードのみ表示し、プロンプト、本文、パス、Tool 入出力、認証情報は返しません。', 'Only ownership, state, time, counts, and safe error codes are shown—never prompts, content, paths, Tool payloads, or credentials.'],
  modelPools: ['模型池', 'モデルプール', 'Model pools'], projects: ['项目', 'プロジェクト', 'Projects'],
  tasks: ['任务', 'タスク', 'Tasks'], workspaces: ['工作区', 'ワークスペース', 'Workspaces'],
  conversations: ['对话', '会話', 'Conversations'], mcpConnections: ['MCP 连接', 'MCP 接続', 'MCP connections'],
  knowledgeDocuments: ['知识文档', 'ナレッジ文書', 'Knowledge documents'], memories: ['记忆', 'メモリ', 'Memories'],
  automations: ['自动化', '自動化', 'Automations'], runs: ['运行', '実行', 'Runs'],
  modelEffects: ['模型异常效果', 'モデル異常効果', 'Model risk effects'], toolEffects: ['Tool 异常效果', 'Tool 異常効果', 'Tool risk effects'],
  membersCount: ['成员', 'メンバー', 'members'], enabledCount: ['启用', '有効', 'enabled'],
  childTasksCount: ['子任务', '子タスク', 'child tasks'], writableCount: ['可写', '書き込み可', 'writable'],
  messagesCount: ['消息', 'メッセージ', 'messages'], snapshotsCount: ['快照', 'スナップショット', 'snapshots'],
  chunksCount: ['分块', 'チャンク', 'chunks'], executionsCount: ['执行', '実行', 'executions'],
  riskCount: ['异常', '異常', 'risk'], stepsCount: ['步骤', 'ステップ', 'steps'],
  checkpointsCount: ['检查点', 'チェックポイント', 'checkpoints'], yes: ['是', 'はい', 'yes'], no: ['否', 'いいえ', 'no'],
}

export const text = (language: Language, key: string) => {
  const value = extraMessages[key] ?? messages[key]
  if (!value) return key
  return value[language === 'zh' ? 0 : language === 'ja' ? 1 : 2]
}
