package com.spaceagent.platform.runtime.infrastructure.persistence;

import com.spaceagent.platform.runtime.domain.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import java.sql.ResultSet; import java.sql.SQLException; import java.sql.Timestamp; import java.time.Instant; import java.util.Optional;

@Repository @ConditionalOnProperty(prefix = "platform", name = "persistence", havingValue = "postgres")
public class PostgresProjectPlanWaveConcurrencyRepository implements ProjectPlanWaveConcurrencyRepository {
    private final JdbcTemplate jdbc; public PostgresProjectPlanWaveConcurrencyRepository(JdbcTemplate jdbc) { this.jdbc = jdbc; }
    @Override public void insert(ProjectPlanWaveConcurrency v) { jdbc.update("INSERT INTO platform_project_plan_wave_concurrency(execution_id,tenant_id,owner_id,project_id,task_plan_id,max_parallelism,active_claims,revision,created_at,updated_at) VALUES(CAST(? AS UUID),?,?,CAST(? AS UUID),CAST(? AS UUID),?,?,?, ?,?)", v.executionId(),v.tenantId(),v.ownerId(),v.projectId(),v.taskPlanId(),v.maxParallelism(),v.activeClaims(),v.revision(),ts(v.createdAt()),ts(v.updatedAt())); }
    @Override public Optional<ProjectPlanWaveConcurrency> findByExecutionId(String id) { return jdbc.query("SELECT * FROM platform_project_plan_wave_concurrency WHERE execution_id=CAST(? AS UUID)",this::budget,id).stream().findFirst(); }
    @Override @Transactional public Optional<ProjectPlanWaveClaim> claim(String executionId,String tenant,String owner,String plan,String step,String worker,String token,Instant now,Instant lease) {
        var budget=jdbc.query("SELECT * FROM platform_project_plan_wave_concurrency WHERE execution_id=CAST(? AS UUID) AND tenant_id=? AND owner_id=? AND task_plan_id=CAST(? AS UUID) FOR UPDATE",this::budget,executionId,tenant,owner,plan).stream().findFirst(); if(budget.isEmpty()) return Optional.empty();
        jdbc.update("UPDATE platform_project_plan_wave_claims SET state='RELEASED',released_at=?,updated_at=?,revision=revision+1 WHERE execution_id=CAST(? AS UUID) AND state='CLAIMED' AND lease_until<=?",ts(now),ts(now),executionId,ts(now));
        int active=jdbc.queryForObject("SELECT count(*) FROM platform_project_plan_wave_claims WHERE execution_id=CAST(? AS UUID) AND state='CLAIMED'",Integer.class,executionId); if(active>=budget.get().maxParallelism()) return Optional.empty();
        var prior=jdbc.query("SELECT * FROM platform_project_plan_wave_claims WHERE execution_id=CAST(? AS UUID) AND plan_step_id=CAST(? AS UUID) FOR UPDATE",this::claim,executionId,step).stream().findFirst(); if(prior.isPresent()&&prior.get().state()==ProjectPlanWaveClaim.State.CLAIMED) return Optional.empty();
        if(prior.isEmpty()) jdbc.update("INSERT INTO platform_project_plan_wave_claims(execution_id,task_plan_id,plan_step_id,tenant_id,owner_id,claim_owner,claim_token,fencing_token,lease_until,state,revision,created_at,updated_at) VALUES(CAST(? AS UUID),CAST(? AS UUID),CAST(? AS UUID),?,?,?,CAST(? AS UUID),1,?,'CLAIMED',1,?,?)",executionId,plan,step,tenant,owner,worker,token,ts(lease),ts(now),ts(now));
        else jdbc.update("UPDATE platform_project_plan_wave_claims SET claim_owner=?,claim_token=CAST(? AS UUID),fencing_token=fencing_token+1,lease_until=?,state='CLAIMED',released_at=NULL,job_id=NULL,revision=revision+1,updated_at=? WHERE execution_id=CAST(? AS UUID) AND plan_step_id=CAST(? AS UUID)",worker,token,ts(lease),ts(now),executionId,step);
        jdbc.update("UPDATE platform_project_plan_wave_concurrency SET active_claims=?,revision=revision+1,updated_at=? WHERE execution_id=CAST(? AS UUID)",active+1,ts(now),executionId); return jdbc.query("SELECT * FROM platform_project_plan_wave_claims WHERE execution_id=CAST(? AS UUID) AND plan_step_id=CAST(? AS UUID)",this::claim,executionId,step).stream().findFirst();
    }
    @Override @Transactional public boolean release(ProjectPlanWaveClaim c,Instant at) { int n=jdbc.update("UPDATE platform_project_plan_wave_claims SET state='RELEASED',released_at=?,updated_at=?,revision=revision+1 WHERE execution_id=CAST(? AS UUID) AND plan_step_id=CAST(? AS UUID) AND state='CLAIMED' AND claim_token=CAST(? AS UUID) AND fencing_token=?",ts(at),ts(at),c.executionId(),c.planStepId(),c.claimToken(),c.fencingToken()); if(n!=1)return false; jdbc.update("UPDATE platform_project_plan_wave_concurrency SET active_claims=active_claims-1,revision=revision+1,updated_at=? WHERE execution_id=CAST(? AS UUID) AND active_claims>0",ts(at),c.executionId());return true; }
    @Override public boolean bindJob(ProjectPlanWaveClaim claim,String jobId,Instant at){return jdbc.update("UPDATE platform_project_plan_wave_claims SET job_id=CAST(? AS UUID),revision=revision+1,updated_at=? WHERE execution_id=CAST(? AS UUID) AND plan_step_id=CAST(? AS UUID) AND state='CLAIMED' AND claim_token=CAST(? AS UUID) AND fencing_token=? AND (job_id IS NULL OR job_id=CAST(? AS UUID))",jobId,ts(at),claim.executionId(),claim.planStepId(),claim.claimToken(),claim.fencingToken(),jobId)==1;}
    @Override public boolean synchronizeWithJob(String executionId,String stepId,String jobId,String owner,String token,long fence,Instant lease,Instant at){return jdbc.update("UPDATE platform_project_plan_wave_claims wave SET job_id=job.id,claim_owner=?,claim_token=CAST(? AS UUID),fencing_token=?,lease_until=job.lease_until,revision=wave.revision+1,updated_at=? FROM platform_project_coding_jobs job WHERE wave.execution_id=CAST(? AS UUID) AND wave.plan_step_id=CAST(? AS UUID) AND wave.state='CLAIMED' AND (wave.job_id IS NULL OR wave.job_id=job.id) AND job.id=CAST(? AS UUID) AND job.state='RUNNING' AND job.claim_owner=? AND job.claim_token=CAST(? AS UUID) AND job.fencing_token=? AND job.lease_until>?",owner,token,fence,ts(at),executionId,stepId,jobId,owner,token,fence,ts(at))==1;}
    @Override @Transactional public boolean releaseBound(String executionId,String stepId,String jobId,String token,long fence,Instant at){int n=jdbc.update("UPDATE platform_project_plan_wave_claims SET state='RELEASED',released_at=?,updated_at=?,revision=revision+1 WHERE execution_id=CAST(? AS UUID) AND plan_step_id=CAST(? AS UUID) AND job_id=CAST(? AS UUID) AND state='CLAIMED' AND claim_token=CAST(? AS UUID) AND fencing_token=?",ts(at),ts(at),executionId,stepId,jobId,token,fence);if(n!=1)return false;jdbc.update("UPDATE platform_project_plan_wave_concurrency SET active_claims=active_claims-1,revision=revision+1,updated_at=? WHERE execution_id=CAST(? AS UUID) AND active_claims>0",ts(at),executionId);return true;}
    private ProjectPlanWaveConcurrency budget(ResultSet r,int n)throws SQLException{return new ProjectPlanWaveConcurrency(r.getString("execution_id"),r.getString("tenant_id"),r.getString("owner_id"),r.getString("project_id"),r.getString("task_plan_id"),r.getInt("max_parallelism"),r.getInt("active_claims"),r.getLong("revision"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());}
    private ProjectPlanWaveClaim claim(ResultSet r,int n)throws SQLException{Timestamp released=r.getTimestamp("released_at");return new ProjectPlanWaveClaim(r.getString("execution_id"),r.getString("task_plan_id"),r.getString("plan_step_id"),r.getString("tenant_id"),r.getString("owner_id"),r.getString("claim_owner"),r.getString("claim_token"),r.getLong("fencing_token"),r.getTimestamp("lease_until").toInstant(),ProjectPlanWaveClaim.State.valueOf(r.getString("state")),r.getLong("revision"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant(),released==null?null:released.toInstant(),r.getString("job_id"));}
    private static Timestamp ts(Instant v){return Timestamp.from(v);}
}
