package com.spaceagent.platform.knowledge;

import com.spaceagent.platform.knowledge.api.KnowledgeUrlIngestionApplicationApi;
import com.spaceagent.platform.knowledge.domain.*;
import org.junit.jupiter.api.Test;
import java.lang.reflect.RecordComponent;import java.time.Instant;import java.util.Arrays;
import static org.assertj.core.api.Assertions.*;

class KnowledgeUrlDomainTest {
 private static final Instant NOW=Instant.parse("2026-09-09T00:00:00Z");private static final String H="sha256:"+"a".repeat(64);
 @Test void normalizesOnlyCanonicalPublicHttps(){assertThat(KnowledgeUrlJob.normalize("HTTPS://Docs.Example.COM/a/../guide?q=1")).isEqualTo("https://docs.example.com/guide?q=1");assertThat(KnowledgeUrlJob.origin("https://docs.example.com/guide")).isEqualTo("https://docs.example.com");assertThatThrownBy(()->KnowledgeUrlJob.normalize("http://example.com")).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->KnowledgeUrlJob.normalize("https://127.0.0.1/a")).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->KnowledgeUrlJob.normalize("https://user:pass@example.com/a")).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->KnowledgeUrlJob.normalize("https://example.com/a#fragment")).isInstanceOf(IllegalArgumentException.class);}
 @Test void jobAndRefreshPolicyAreBounded(){var policy=new KnowledgeUrlJob.RefreshPolicy(KnowledgeUrlJob.RefreshMode.PERIODIC,3600,true,3,1_000_000);var job=new KnowledgeUrlJob("job","tenant","owner","document","https://docs.example.com/","https://docs.example.com",policy,KnowledgeUrlJob.State.ACTIVE,1,NOW,NOW,NOW,null);assertThat(job.refreshPolicy()).isEqualTo(policy);assertThatThrownBy(()->new KnowledgeUrlJob.RefreshPolicy(KnowledgeUrlJob.RefreshMode.PERIODIC,10,true,0,100)).isInstanceOf(IllegalArgumentException.class);}
 @Test void observationsAndContentVersionsAreHashOnlyAndFailClosed(){var fetched=new KnowledgeUrlEvidence.Observation("observation","job","tenant",H,"https://docs.example.com/page",H,200,"etag","date",H,KnowledgeUrlEvidence.ObservationOutcome.FETCHED,null,NOW);assertThat(fetched.contentSha256()).isEqualTo(H);var active=new KnowledgeUrlEvidence.ContentVersion("content","job","document","tenant",1,H,"knowledge-url/job/content","text/html","UTF-8",100,KnowledgeUrlEvidence.ContentState.ACTIVE,"observation",NOW,NOW);assertThat(active.objectReference()).doesNotStartWith("/");assertThatThrownBy(()->new KnowledgeUrlEvidence.Observation("o","j","t",H,null,H,200,null,null,null,KnowledgeUrlEvidence.ObservationOutcome.UNKNOWN,null,NOW)).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->new KnowledgeUrlEvidence.ContentVersion("c","j","d","t",1,H,"/host/path","text/plain","UTF-8",1,KnowledgeUrlEvidence.ContentState.STAGED,"o",NOW,null)).isInstanceOf(IllegalArgumentException.class);}
 @Test void publicCommandsContainNoDnsBytesParserOrClientState(){var names=Arrays.stream(KnowledgeUrlIngestionApplicationApi.CreateUrlJobCommand.class.getRecordComponents()).map(RecordComponent::getName).toList();assertThat(names).containsExactly("tenantId","ownerId","knowledgeDocumentId","url","refreshPolicy","idempotencyKey").doesNotContain("dnsAddress","body","content","state","chunk","embedding");}
}
