DO $agent_version_governance_reviews$ BEGIN
 IF to_regclass('public.platform_tenants') IS NULL
    OR to_regclass('public.platform_users') IS NULL
    OR to_regclass('public.platform_agent_definitions') IS NULL
    OR to_regclass('public.platform_agent_versions') IS NULL THEN RETURN; END IF;
 ALTER TABLE platform_users ADD CONSTRAINT uk_user_tenant_agent_governance UNIQUE(id,tenant_id);
 ALTER TABLE platform_agent_versions ADD CONSTRAINT uk_agent_version_review_hash UNIQUE(id,config_hash);
 CREATE TABLE platform_agent_version_governance_policies(tenant_id VARCHAR(64) PRIMARY KEY REFERENCES platform_tenants(id),require_review BOOLEAN NOT NULL DEFAULT TRUE,separate_creator_reviewer BOOLEAN NOT NULL DEFAULT TRUE,separate_creator_approver BOOLEAN NOT NULL DEFAULT TRUE,separate_reviewer_approver BOOLEAN NOT NULL DEFAULT TRUE,allow_automatic_activation BOOLEAN NOT NULL DEFAULT FALSE,review_ttl_seconds INTEGER NOT NULL DEFAULT 604800,revision BIGINT NOT NULL,updated_by VARCHAR(36) NOT NULL,updated_at TIMESTAMPTZ NOT NULL,CONSTRAINT fk_agent_version_policy_actor FOREIGN KEY(updated_by,tenant_id) REFERENCES platform_users(id,tenant_id),CONSTRAINT ck_agent_version_policy CHECK(review_ttl_seconds BETWEEN 300 AND 2592000 AND revision>0 AND (require_review OR NOT(separate_creator_reviewer OR separate_creator_approver OR separate_reviewer_approver OR allow_automatic_activation))));
 CREATE TABLE platform_agent_version_reviews(id UUID PRIMARY KEY,tenant_id VARCHAR(64) NOT NULL REFERENCES platform_tenants(id),owner_id VARCHAR(36) NOT NULL,agent_id VARCHAR(64) NOT NULL,agent_version_id UUID NOT NULL,config_hash VARCHAR(64) NOT NULL,state VARCHAR(16) NOT NULL,revision BIGINT NOT NULL,created_by VARCHAR(36) NOT NULL,created_at TIMESTAMPTZ NOT NULL,expires_at TIMESTAMPTZ NOT NULL,reviewed_by VARCHAR(36),reviewed_at TIMESTAMPTZ,approved_by VARCHAR(36),approved_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL,CONSTRAINT uk_agent_version_review UNIQUE(agent_version_id,config_hash),CONSTRAINT uk_agent_review_tenant UNIQUE(id,tenant_id),CONSTRAINT uk_agent_review_scope UNIQUE(id,tenant_id,agent_version_id,config_hash),CONSTRAINT fk_agent_review_owner FOREIGN KEY(owner_id,tenant_id) REFERENCES platform_users(id,tenant_id),CONSTRAINT fk_agent_review_creator FOREIGN KEY(created_by,tenant_id) REFERENCES platform_users(id,tenant_id),CONSTRAINT fk_agent_review_reviewer FOREIGN KEY(reviewed_by,tenant_id) REFERENCES platform_users(id,tenant_id),CONSTRAINT fk_agent_review_approver FOREIGN KEY(approved_by,tenant_id) REFERENCES platform_users(id,tenant_id),CONSTRAINT fk_agent_review_definition FOREIGN KEY(agent_id,tenant_id,owner_id) REFERENCES platform_agent_definitions(id,tenant_id,owner_id),CONSTRAINT fk_agent_review_version FOREIGN KEY(agent_id,agent_version_id) REFERENCES platform_agent_versions(agent_id,id),CONSTRAINT fk_agent_review_version_hash FOREIGN KEY(agent_version_id,config_hash) REFERENCES platform_agent_versions(id,config_hash),CONSTRAINT ck_agent_review_hash CHECK(config_hash~'^[0-9a-f]{64}$'),CONSTRAINT ck_agent_review_state CHECK(state IN('OPEN','REVIEWED','APPROVED','REJECTED','EXPIRED','CANCELLED')),CONSTRAINT ck_agent_review_lifecycle CHECK(revision>0 AND expires_at>created_at AND (state NOT IN('REVIEWED','APPROVED') OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)) AND (state<>'APPROVED' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL))));
 CREATE TABLE platform_agent_version_review_comments(id UUID PRIMARY KEY,review_id UUID NOT NULL,tenant_id VARCHAR(64) NOT NULL,author_id VARCHAR(36) NOT NULL,body VARCHAR(4000) NOT NULL,body_sha256 VARCHAR(71) NOT NULL,created_at TIMESTAMPTZ NOT NULL,CONSTRAINT fk_agent_review_comment FOREIGN KEY(review_id,tenant_id) REFERENCES platform_agent_version_reviews(id,tenant_id),CONSTRAINT fk_agent_review_comment_actor FOREIGN KEY(author_id,tenant_id) REFERENCES platform_users(id,tenant_id),CONSTRAINT ck_agent_review_comment_hash CHECK(body_sha256~'^sha256:[0-9a-f]{64}$'));
 CREATE TABLE platform_agent_version_review_decisions(id UUID PRIMARY KEY,review_id UUID NOT NULL,tenant_id VARCHAR(64) NOT NULL,agent_version_id UUID NOT NULL,config_hash VARCHAR(64) NOT NULL,kind VARCHAR(32) NOT NULL,actor_id VARCHAR(36) NOT NULL,note VARCHAR(2000),evidence_sha256 VARCHAR(71) NOT NULL,created_at TIMESTAMPTZ NOT NULL,CONSTRAINT uk_agent_review_decision_kind UNIQUE(review_id,kind),CONSTRAINT fk_agent_review_decision FOREIGN KEY(review_id,tenant_id,agent_version_id,config_hash) REFERENCES platform_agent_version_reviews(id,tenant_id,agent_version_id,config_hash),CONSTRAINT fk_agent_review_decision_actor FOREIGN KEY(actor_id,tenant_id) REFERENCES platform_users(id,tenant_id),CONSTRAINT ck_agent_review_decision_kind CHECK(kind IN('REVIEW_APPROVED','REVIEW_REJECTED','PUBLICATION_APPROVED','PUBLICATION_REJECTED')),CONSTRAINT ck_agent_review_decision_hash CHECK(config_hash~'^[0-9a-f]{64}$' AND evidence_sha256~'^sha256:[0-9a-f]{64}$'));
 CREATE INDEX idx_agent_reviews_scope ON platform_agent_version_reviews(tenant_id,owner_id,agent_id,created_at DESC,id);
END $agent_version_governance_reviews$;
