DO $knowledge_url_ingestion$ BEGIN
 IF to_regclass('public.platform_knowledge_documents') IS NULL OR to_regclass('public.platform_users') IS NULL OR to_regclass('public.platform_tenants') IS NULL THEN RETURN; END IF;
 ALTER TABLE platform_users ADD CONSTRAINT uk_user_tenant_knowledge_url UNIQUE(id,tenant_id);
 ALTER TABLE platform_knowledge_documents ADD CONSTRAINT uk_knowledge_document_owner_url UNIQUE(id,owner_id);
 CREATE TABLE platform_knowledge_url_jobs(id UUID PRIMARY KEY,tenant_id VARCHAR(64) NOT NULL,owner_id VARCHAR(36) NOT NULL,knowledge_document_id VARCHAR(36) NOT NULL,normalized_url VARCHAR(2048) NOT NULL,origin VARCHAR(300) NOT NULL,refresh_mode VARCHAR(16) NOT NULL,refresh_interval_seconds INTEGER NOT NULL,use_conditional_requests BOOLEAN NOT NULL,maximum_redirects INTEGER NOT NULL,maximum_bytes INTEGER NOT NULL,state VARCHAR(16) NOT NULL,revision BIGINT NOT NULL,next_refresh_at TIMESTAMPTZ,claim_token UUID,claim_owner VARCHAR(120),lease_until TIMESTAMPTZ,fencing_token BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,archived_at TIMESTAMPTZ,CONSTRAINT fk_knowledge_url_tenant FOREIGN KEY(tenant_id) REFERENCES platform_tenants(id),CONSTRAINT fk_knowledge_url_owner FOREIGN KEY(owner_id,tenant_id) REFERENCES platform_users(id,tenant_id),CONSTRAINT fk_knowledge_url_document FOREIGN KEY(knowledge_document_id,owner_id) REFERENCES platform_knowledge_documents(id,owner_id),CONSTRAINT uk_knowledge_url_job UNIQUE(tenant_id,owner_id,knowledge_document_id,normalized_url),CONSTRAINT uk_knowledge_url_job_tenant UNIQUE(id,tenant_id),CONSTRAINT uk_knowledge_url_job_scope UNIQUE(id,knowledge_document_id,tenant_id),CONSTRAINT ck_knowledge_url_policy CHECK(refresh_mode IN('MANUAL','PERIODIC') AND ((refresh_mode='MANUAL' AND refresh_interval_seconds=0) OR (refresh_mode='PERIODIC' AND refresh_interval_seconds BETWEEN 300 AND 2592000)) AND maximum_redirects BETWEEN 0 AND 5 AND maximum_bytes BETWEEN 1 AND 10000000),CONSTRAINT ck_knowledge_url_state CHECK(state IN('DRAFT','ACTIVE','PAUSED','ARCHIVED')),CONSTRAINT ck_knowledge_url_claim CHECK((claim_token IS NULL AND claim_owner IS NULL AND lease_until IS NULL) OR (claim_token IS NOT NULL AND claim_owner IS NOT NULL AND lease_until IS NOT NULL)),CONSTRAINT ck_knowledge_url_lifecycle CHECK(revision>0 AND fencing_token>=0 AND (state<>'ACTIVE' OR next_refresh_at IS NOT NULL) AND ((state='ARCHIVED' AND archived_at IS NOT NULL) OR (state<>'ARCHIVED' AND archived_at IS NULL))));
 CREATE TABLE platform_knowledge_url_observations(id UUID PRIMARY KEY,url_job_id UUID NOT NULL,tenant_id VARCHAR(64) NOT NULL,request_url_sha256 VARCHAR(71) NOT NULL,final_url VARCHAR(2048),final_url_sha256 VARCHAR(71) NOT NULL,http_status INTEGER NOT NULL,etag VARCHAR(500),last_modified VARCHAR(200),content_sha256 VARCHAR(71),outcome VARCHAR(20) NOT NULL,safe_error_code VARCHAR(64),observed_at TIMESTAMPTZ NOT NULL,CONSTRAINT uk_knowledge_url_observation_scope UNIQUE(id,url_job_id,tenant_id),CONSTRAINT fk_knowledge_url_observation_job FOREIGN KEY(url_job_id,tenant_id) REFERENCES platform_knowledge_url_jobs(id,tenant_id),CONSTRAINT ck_knowledge_url_observation_hash CHECK(request_url_sha256~'^sha256:[0-9a-f]{64}$' AND final_url_sha256~'^sha256:[0-9a-f]{64}$' AND (content_sha256 IS NULL OR content_sha256~'^sha256:[0-9a-f]{64}$')),CONSTRAINT ck_knowledge_url_observation_outcome CHECK(outcome IN('FETCHED','NOT_MODIFIED','REJECTED','FAILED','UNKNOWN') AND http_status BETWEEN 0 AND 599));
 CREATE TABLE platform_knowledge_url_content_versions(id UUID PRIMARY KEY,url_job_id UUID NOT NULL,knowledge_document_id VARCHAR(36) NOT NULL,tenant_id VARCHAR(64) NOT NULL,version INTEGER NOT NULL,content_sha256 VARCHAR(71) NOT NULL,object_reference VARCHAR(500) NOT NULL,media_type VARCHAR(160) NOT NULL,charset VARCHAR(80) NOT NULL,byte_size BIGINT NOT NULL,state VARCHAR(16) NOT NULL,source_observation_id UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL,activated_at TIMESTAMPTZ,CONSTRAINT fk_knowledge_url_content_job FOREIGN KEY(url_job_id,knowledge_document_id,tenant_id) REFERENCES platform_knowledge_url_jobs(id,knowledge_document_id,tenant_id),CONSTRAINT fk_knowledge_url_content_observation FOREIGN KEY(source_observation_id,url_job_id,tenant_id) REFERENCES platform_knowledge_url_observations(id,url_job_id,tenant_id),CONSTRAINT uk_knowledge_url_content_version UNIQUE(url_job_id,version),CONSTRAINT uk_knowledge_url_content_hash UNIQUE(url_job_id,content_sha256),CONSTRAINT ck_knowledge_url_content_hash CHECK(content_sha256~'^sha256:[0-9a-f]{64}$'),CONSTRAINT ck_knowledge_url_content_state CHECK(state IN('STAGED','ACTIVE','SUPERSEDED','REJECTED')),CONSTRAINT ck_knowledge_url_content_bounds CHECK(version>0 AND byte_size BETWEEN 0 AND 10000000 AND ((state IN('ACTIVE','SUPERSEDED') AND activated_at IS NOT NULL) OR (state IN('STAGED','REJECTED') AND activated_at IS NULL))));
 CREATE UNIQUE INDEX uk_knowledge_url_active_content ON platform_knowledge_url_content_versions(url_job_id) WHERE state='ACTIVE';
 CREATE INDEX idx_knowledge_url_due ON platform_knowledge_url_jobs(next_refresh_at,id) WHERE state='ACTIVE';
END $knowledge_url_ingestion$;
