package com.spaceagent.platform.knowledge.infrastructure.persistence;

import com.spaceagent.platform.knowledge.domain.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import java.sql.*;
import java.time.Instant;
import java.util.*;

@Repository
@ConditionalOnProperty(prefix="platform", name="persistence", havingValue="postgres")
public class PostgresDocumentWorkspaceRepository implements DocumentWorkspaceRepository {
    private static final String W="id,tenant_id,scope_type,scope_id,owner_id,name,object_namespace,maximum_files,maximum_bytes,file_count,byte_count,state,revision,created_at,updated_at,archived_at";
    private static final String O="id,tenant_id,workspace_id,actor_user_id,agent_run_id,run_step_id,tool_call_id,idempotency_key,input_hash,operation_type,path,requested_bytes,previous_bytes,previous_file_present,reserved_files,reserved_bytes,state,result_bytes,result_hash,safe_error_code,revision,created_at,updated_at,completed_at";
    private final JdbcTemplate jdbc; private final TransactionTemplate tx;
    public PostgresDocumentWorkspaceRepository(JdbcTemplate jdbc,PlatformTransactionManager manager){this.jdbc=jdbc;this.tx=new TransactionTemplate(manager);}
    public Instant currentTime(){return jdbc.queryForObject("SELECT clock_timestamp()",Timestamp.class).toInstant();}
    public void insert(DocumentWorkspace v,String key){jdbc.update("INSERT INTO platform_document_workspaces(id,tenant_id,scope_type,scope_id,owner_id,name,object_namespace,maximum_files,maximum_bytes,file_count,byte_count,state,revision,create_idempotency_key,created_at,updated_at,archived_at) VALUES(CAST(? AS UUID),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",v.id(),v.tenantId(),v.scopeType().name(),v.scopeId(),v.ownerId(),v.name(),v.objectNamespace(),v.quota().maximumFiles(),v.quota().maximumBytes(),v.usage().fileCount(),v.usage().byteCount(),v.state().name(),v.revision(),key,ts(v.createdAt()),ts(v.updatedAt()),ts(v.archivedAt()));}
    public Optional<DocumentWorkspace> findByCreateKey(String t,String o,String k){return jdbc.query("SELECT "+W+" FROM platform_document_workspaces WHERE tenant_id=? AND owner_id=? AND create_idempotency_key=?",this::workspace,t,o,k).stream().findFirst();}
    public Optional<DocumentWorkspace> findById(String t,String id){return jdbc.query("SELECT "+W+" FROM platform_document_workspaces WHERE tenant_id=? AND id=CAST(? AS UUID)",this::workspace,t,id).stream().findFirst();}
    public List<DocumentWorkspace> list(String t){return jdbc.query("SELECT "+W+" FROM platform_document_workspaces WHERE tenant_id=? ORDER BY created_at,id",this::workspace,t);}
    public Optional<DocumentWorkspace> update(DocumentWorkspace v,long r){return jdbc.query("UPDATE platform_document_workspaces SET maximum_files=?,maximum_bytes=?,file_count=?,byte_count=?,state=?,revision=revision+1,updated_at=?,archived_at=? WHERE id=CAST(? AS UUID) AND tenant_id=? AND revision=? RETURNING "+W,this::workspace,v.quota().maximumFiles(),v.quota().maximumBytes(),v.usage().fileCount(),v.usage().byteCount(),v.state().name(),ts(v.updatedAt()),ts(v.archivedAt()),v.id(),v.tenantId(),r).stream().findFirst();}
    public MutationClaim claimMutation(MutationRequest r){return tx.execute(x->{DocumentWorkspace w=lockedWorkspace(r.tenantId(),r.workspaceId()).orElseThrow();var same=findOperationByCall(r.workspaceId(),r.toolCallId(),r.idempotencyKey());if(same.isPresent())return existing(same.get(),r,w);boolean busy=Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM platform_document_workspace_operations WHERE workspace_id=CAST(? AS UUID) AND path=? AND state IN('PENDING','UNKNOWN'))",Boolean.class,r.workspaceId(),r.path()));if(busy)return new MutationClaim(ClaimType.BUSY,w,null);var prior=jdbc.query("SELECT byte_size,content_hash FROM platform_document_workspace_files WHERE workspace_id=CAST(? AS UUID) AND path=?",(rs,n)->new FileState(rs.getLong(1),rs.getString(2)),r.workspaceId(),r.path()).stream().findFirst();long previous=prior.map(FileState::bytes).orElse(0L);long files=r.type()==DocumentWorkspaceOperation.Type.WRITE&&prior.isEmpty()?1:0;long bytes=r.type()==DocumentWorkspaceOperation.Type.WRITE?Math.max(0,r.requestedBytes()-previous):0;DocumentWorkspace reserved=r.type()==DocumentWorkspaceOperation.Type.WRITE?w.reserve(files,bytes,r.at()):w;if(reserved.revision()!=w.revision())saveLocked(reserved,w.revision());jdbc.update("INSERT INTO platform_document_workspace_operations(id,tenant_id,workspace_id,actor_user_id,agent_run_id,run_step_id,tool_call_id,idempotency_key,input_hash,operation_type,path,requested_bytes,previous_bytes,previous_file_present,reserved_files,reserved_bytes,state,revision,created_at,updated_at) VALUES(CAST(? AS UUID),?,CAST(? AS UUID),?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)",r.operationId(),r.tenantId(),r.workspaceId(),r.actorUserId(),r.agentRunId(),r.runStepId(),r.toolCallId(),r.idempotencyKey(),r.inputHash(),r.type().name(),r.path(),r.requestedBytes(),previous,prior.isPresent(),files,bytes,DocumentWorkspaceOperation.State.PENDING.name(),ts(r.at()),ts(r.at()));var op=findOperation(r.tenantId(),r.operationId()).orElseThrow();return new MutationClaim(ClaimType.CLAIMED,reserved,op);});}
    public Optional<MutationResult> completeMutation(String t,String id,long actual,String hash,Instant at){return transition(t,id,(w,o)->{if(o.type()==DocumentWorkspaceOperation.Type.WRITE){if(actual!=o.requestedBytes())return null;long shrink=Math.max(0,o.previousBytes()-actual);DocumentWorkspace next=shrink==0?w:w.release(0,shrink,at);jdbc.update("INSERT INTO platform_document_workspace_files(workspace_id,tenant_id,path,byte_size,content_hash,updated_at) VALUES(CAST(? AS UUID),?,?,?,?,?) ON CONFLICT(workspace_id,path) DO UPDATE SET byte_size=excluded.byte_size,content_hash=excluded.content_hash,updated_at=excluded.updated_at",o.workspaceId(),t,o.path(),actual,hash,ts(at));return result(next,terminal(o,DocumentWorkspaceOperation.State.SUCCEEDED,actual,hash,null,at));}jdbc.update("DELETE FROM platform_document_workspace_files WHERE workspace_id=CAST(? AS UUID) AND path=?",o.workspaceId(),o.path());DocumentWorkspace next=o.previousFilePresent()?w.release(1,o.previousBytes(),at):w;return result(next,terminal(o,DocumentWorkspaceOperation.State.SUCCEEDED,0L,hash,null,at));});}
    public Optional<MutationResult> failMutation(String t,String id,String code,Instant at){return transition(t,id,(w,o)->{DocumentWorkspace next=o.type()==DocumentWorkspaceOperation.Type.WRITE&&(o.reservedFiles()>0||o.reservedBytes()>0)?w.release(o.reservedFiles(),o.reservedBytes(),at):w;return result(next,terminal(o,DocumentWorkspaceOperation.State.FAILED,null,null,code,at));});}
    public Optional<MutationResult> markMutationUnknown(String t,String id,String code,Instant at){return transition(t,id,(w,o)->result(w,terminal(o,DocumentWorkspaceOperation.State.UNKNOWN,null,null,code,at)));}
    public Optional<DocumentWorkspaceOperation> findMutation(String t,String run,String call){return jdbc.query("SELECT "+O+" FROM platform_document_workspace_operations WHERE tenant_id=? AND agent_run_id=? AND tool_call_id=?",this::operation,t,run,call).stream().findFirst();}
    private Optional<MutationResult> transition(String t,String id,Transition fn){return tx.execute(x->{var op=jdbc.query("SELECT "+O+" FROM platform_document_workspace_operations WHERE tenant_id=? AND id=CAST(? AS UUID) FOR UPDATE",this::operation,t,id).stream().findFirst();if(op.isEmpty())return Optional.empty();DocumentWorkspaceOperation o=op.get();DocumentWorkspace w=lockedWorkspace(t,o.workspaceId()).orElseThrow();if(o.state()!=DocumentWorkspaceOperation.State.PENDING)return Optional.of(new MutationResult(w,o));MutationResult result=fn.apply(w,o);if(result==null)return Optional.empty();if(result.workspace().revision()!=w.revision())saveLocked(result.workspace(),w.revision());saveOperation(result.operation(),o.revision());return Optional.of(result);});}
    private void saveLocked(DocumentWorkspace v,long revision){int changed=jdbc.update("UPDATE platform_document_workspaces SET file_count=?,byte_count=?,revision=revision+1,updated_at=? WHERE id=CAST(? AS UUID) AND tenant_id=? AND revision=?",v.usage().fileCount(),v.usage().byteCount(),ts(v.updatedAt()),v.id(),v.tenantId(),revision);if(changed!=1)throw new IllegalStateException("Document Workspace quota CAS conflict");}
    private void saveOperation(DocumentWorkspaceOperation o,long revision){int changed=jdbc.update("UPDATE platform_document_workspace_operations SET state=?,result_bytes=?,result_hash=?,safe_error_code=?,revision=revision+1,updated_at=?,completed_at=? WHERE id=CAST(? AS UUID) AND tenant_id=? AND revision=?",o.state().name(),o.resultBytes(),o.resultHash(),o.safeErrorCode(),ts(o.updatedAt()),ts(o.completedAt()),o.id(),o.tenantId(),revision);if(changed!=1)throw new IllegalStateException("Document Workspace operation CAS conflict");}
    private Optional<DocumentWorkspace> lockedWorkspace(String t,String id){return jdbc.query("SELECT "+W+" FROM platform_document_workspaces WHERE tenant_id=? AND id=CAST(? AS UUID) FOR UPDATE",this::workspace,t,id).stream().findFirst();}
    private Optional<DocumentWorkspaceOperation> findOperationByCall(String w,String call,String key){return jdbc.query("SELECT "+O+" FROM platform_document_workspace_operations WHERE workspace_id=CAST(? AS UUID) AND (tool_call_id=? OR idempotency_key=?)",this::operation,w,call,key).stream().findFirst();}
    private Optional<DocumentWorkspaceOperation> findOperation(String t,String id){return jdbc.query("SELECT "+O+" FROM platform_document_workspace_operations WHERE tenant_id=? AND id=CAST(? AS UUID)",this::operation,t,id).stream().findFirst();}
    private static MutationClaim existing(DocumentWorkspaceOperation o,MutationRequest r,DocumentWorkspace w){if(!o.sameRequest(r.toolCallId(),r.idempotencyKey(),r.inputHash(),r.type(),r.path()))return new MutationClaim(ClaimType.CONFLICT,w,o);return new MutationClaim(switch(o.state()){case SUCCEEDED->ClaimType.REPLAY;case UNKNOWN->ClaimType.UNKNOWN;case FAILED->ClaimType.FAILED;case PENDING->ClaimType.BUSY;},w,o);}
    private DocumentWorkspace workspace(ResultSet r,int n)throws SQLException{return new DocumentWorkspace(r.getString("id"),r.getString("tenant_id"),DocumentWorkspace.ScopeType.valueOf(r.getString("scope_type")),r.getString("scope_id"),r.getString("owner_id"),r.getString("name"),r.getString("object_namespace"),new DocumentWorkspace.Quota(r.getLong("maximum_files"),r.getLong("maximum_bytes")),new DocumentWorkspace.Usage(r.getLong("file_count"),r.getLong("byte_count")),DocumentWorkspace.State.valueOf(r.getString("state")),r.getLong("revision"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant(),in(r.getTimestamp("archived_at")));}
    private DocumentWorkspaceOperation operation(ResultSet r,int n)throws SQLException{return new DocumentWorkspaceOperation(r.getString("id"),r.getString("tenant_id"),r.getString("workspace_id"),r.getString("actor_user_id"),r.getString("agent_run_id"),r.getString("run_step_id"),r.getString("tool_call_id"),r.getString("idempotency_key"),r.getString("input_hash"),DocumentWorkspaceOperation.Type.valueOf(r.getString("operation_type")),r.getString("path"),r.getLong("requested_bytes"),r.getLong("previous_bytes"),r.getBoolean("previous_file_present"),r.getLong("reserved_files"),r.getLong("reserved_bytes"),DocumentWorkspaceOperation.State.valueOf(r.getString("state")),nullableLong(r,"result_bytes"),r.getString("result_hash"),r.getString("safe_error_code"),r.getLong("revision"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant(),in(r.getTimestamp("completed_at")));}
    private static DocumentWorkspaceOperation terminal(DocumentWorkspaceOperation o,DocumentWorkspaceOperation.State state,Long bytes,String hash,String code,Instant at){return new DocumentWorkspaceOperation(o.id(),o.tenantId(),o.workspaceId(),o.actorUserId(),o.agentRunId(),o.runStepId(),o.toolCallId(),o.idempotencyKey(),o.inputHash(),o.type(),o.path(),o.requestedBytes(),o.previousBytes(),o.previousFilePresent(),o.reservedFiles(),o.reservedBytes(),state,bytes,hash,code,o.revision()+1,o.createdAt(),at,state==DocumentWorkspaceOperation.State.SUCCEEDED||state==DocumentWorkspaceOperation.State.FAILED?at:null);}
    private static MutationResult result(DocumentWorkspace w,DocumentWorkspaceOperation o){return new MutationResult(w,o);}private static Timestamp ts(Instant v){return v==null?null:Timestamp.from(v);}private static Instant in(Timestamp v){return v==null?null:v.toInstant();}private static Long nullableLong(ResultSet r,String f)throws SQLException{long v=r.getLong(f);return r.wasNull()?null:v;}private record FileState(long bytes,String hash){}private interface Transition{MutationResult apply(DocumentWorkspace w,DocumentWorkspaceOperation o);}
}
