package com.spaceagent.platform.tooling;
import com.fasterxml.jackson.databind.ObjectMapper;import com.spaceagent.platform.identity.api.*;import com.spaceagent.platform.identity.application.IdentityApplicationService;import com.spaceagent.platform.identity.domain.TenantRole;import com.spaceagent.platform.identity.infrastructure.memory.InMemoryIdentityRepository;import com.spaceagent.platform.tooling.api.McpMarketplaceApplicationApi.*;import com.spaceagent.platform.tooling.application.McpMarketplaceApplicationService;import com.spaceagent.platform.tooling.domain.*;import com.spaceagent.platform.tooling.infrastructure.memory.InMemoryMcpMarketplaceRepository;import com.spaceagent.shared.exception.BusinessException;import com.spaceagent.shared.id.UuidGenerator;import org.junit.jupiter.api.*;import java.time.Instant;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class PlatformMcpMarketplaceApplicationTest{
 private InMemoryMcpMarketplaceRepository repo;private McpMarketplaceApplicationService api;private IdentityApplicationService identity;private String tenant,owner,member;
 @BeforeEach void setup(){var ir=new InMemoryIdentityRepository();var ids=new UuidGenerator();identity=new IdentityApplicationService(ir,ids,()->Instant.parse("2026-08-23T15:00:00Z"));tenant=identity.createTenant(new CreateTenantCommand("Org","mcp-org")).id();owner=identity.createUser(new CreateUserCommand(tenant,"owner@example.com","Owner")).id();member=identity.createUser(new CreateUserCommand(tenant,"member@example.com","Member")).id();identity.addTenantMembership(new AddTenantMembershipCommand(tenant,owner,TenantRole.OWNER));identity.addTenantMembership(new AddTenantMembershipCommand(tenant,member,TenantRole.MEMBER));repo=new InMemoryMcpMarketplaceRepository();api=new McpMarketplaceApplicationService(repo,identity,new Cipher(),new ObjectMapper(),ids,()->Instant.parse("2026-08-23T15:00:00Z"));}
 @Test void installsByScopeIdempotentlyAndEnforcesManagerRole(){var github=api.catalog().stream().filter(e->e.slug().equals("github")).findFirst().orElseThrow();var one=api.install(new InstallCommand(tenant,owner,github.id(),McpInstallationScope.ORGANIZATION,"GitHub Org"));var again=api.install(new InstallCommand(tenant,owner,github.id(),McpInstallationScope.ORGANIZATION,"GitHub Org"));assertEquals(one.id(),again.id());BusinessException denied=assertThrows(BusinessException.class,()->api.install(new InstallCommand(tenant,member,github.id(),McpInstallationScope.ORGANIZATION,null)));assertEquals("MCP_ACCESS_DENIED",denied.getCode());var personal=api.install(new InstallCommand(tenant,member,github.id(),McpInstallationScope.USER,null));assertEquals(member,personal.subjectId());assertFalse(api.installations(tenant,owner).stream().anyMatch(v->v.id().equals(personal.id())));}
 @Test void connectionStoresOnlyCiphertextAndReturnsPendingOAuthReference(){var github=api.catalog().stream().filter(e->e.slug().equals("github")).findFirst().orElseThrow();var install=api.install(new InstallCommand(tenant,owner,github.id(),McpInstallationScope.USER,null));var pending=api.connect(new ConnectCommand(tenant,owner,install.id(),"https://mcp.github.example/rpc",McpAuthType.OAUTH2,Map.of()));assertEquals(McpConnectionState.PENDING_AUTH,pending.state());assertFalse(pending.authConfigured());var active=api.connect(new ConnectCommand(tenant,owner,install.id(),"https://mcp.github.example/rpc",McpAuthType.OAUTH2,Map.of("access_token","top-secret")));assertEquals(McpConnectionState.PENDING_VALIDATION,active.state());assertTrue(active.authConfigured());var stored=repo.findConnectionByInstallation(install.id()).orElseThrow();assertFalse(stored.encryptedAuthJson().contains("top-secret"));assertEquals("{\"access_token\":\"top-secret\"}",new Cipher().decrypt(stored.encryptedAuthJson()));assertEquals(McpConnectionState.REVOKED,api.revokeConnection(new MutateCommand(tenant,owner,active.id())).state());}
 @Test void officialGithubProfileRejectsDirectTokenFallback(){var github=api.catalog().stream().filter(e->e.slug().equals("github")).findFirst().orElseThrow();assertEquals(GithubMcpProfiles.OFFICIAL_REMOTE_ENDPOINT,github.defaultEndpoint());var install=api.install(new InstallCommand(tenant,owner,github.id(),McpInstallationScope.USER,null));var error=assertThrows(BusinessException.class,()->api.connect(new ConnectCommand(tenant,owner,install.id(),null,McpAuthType.OAUTH2,Map.of("token","forbidden-pat"))));assertEquals("MCP_INPUT_INVALID",error.getCode());var pending=api.connect(new ConnectCommand(tenant,owner,install.id(),null,McpAuthType.OAUTH2,Map.of()));assertEquals(McpConnectionState.PENDING_AUTH,pending.state());}
 private static class Cipher implements McpConnectionSecretCipher{public String encrypt(String v){return "cipher:"+Base64.getEncoder().encodeToString(v.getBytes());}public String decrypt(String v){return new String(Base64.getDecoder().decode(v.substring(7)));}}
}
