export type Language = 'en' | 'zh' | 'ja'

export const languageOrder: Language[] = ['en', 'zh', 'ja']
export const languageLabels: Record<Language, string> = { en: 'EN', zh: '中', ja: '日' }

type MessageTable = Record<string, [string, string, string]>

export const messages: MessageTable = {
  skillRefresh: ['Refresh Skills', '刷新 Skill', 'Skill を更新'],
  skillCreate: ['Create Skill', '新建 Skill', 'Skill を作成'],
  skillLoading: ['Loading Skills…', '正在加载 Skill…', 'Skill を読込中…'],
  skillLoadFailed: ['Could not load Skills. Refresh to retry.', 'Skill 加载失败，请刷新重试。', 'Skill を読み込めません。更新してください。'],
  skillBindingHint: ['Bind published instructions, then save the Agent. Required tools must be enabled separately.', '选择已启用的 Skill 后保存 Agent；所需工具须单独开启，Skill 不授予权限。', '公開済み Skill を選び Agent を保存します。必要なツールは別途有効化してください。'],
  skillHistorical: ['Pinned older or unavailable content', '已绑定旧内容或不可用内容', '以前の内容または利用不可の内容に固定'],
  skillUnbind: ['Unbind Skill', '取消绑定 Skill', 'Skill の紐付けを解除'],
  skillDraft: ['Draft — not bindable yet', '草稿待启用，暂不可绑定', '下書き・まだ紐付けできません'],
  skillMissingTools: ['Enable required tools first', '请先开启所需工具', '必要なツールを先に有効化'],
  skillReadInstructions: ['Read instructions', '查看完整指令', '指示の全文を表示'],
  skillEdit: ['Edit / resume draft', '编辑／继续保存', '編集・保存を再開'],
  skillNoRegistered: ['No Skills registered in this organization.', '当前组织尚未注册 Skill。', 'この組織には Skill が未登録です。'],
  skillListBound: ['Showing the most recent 100 Skills.', '仅显示最近 100 个 Skill。', '最新 100 件の Skill を表示しています。'],
  skillSavedBindHint: ['Skill saved. Select it and save the Agent; existing bindings are unchanged.', 'Skill 已保存，请勾选并保存 Agent；已有绑定不会自动替换。', 'Skill を保存しました。選択して Agent を保存してください。既存の紐付けは変更されません。'],
  skillResumeHint: ['Content was saved; activation needs confirmation. Continue to reconcile the exact draft.', '内容已保存，启用结果待确认；点击继续保存核对该草稿。', '内容は保存済みです。保存を再開してこの下書きの公開状態を確認してください。'],
  skillUncertainHint: ['Save failed or its result is unknown. Refresh the registry before another write.', '保存失败或结果未知。请先刷新列表确认记录，再继续操作。', '保存に失敗または結果不明です。再操作する前に一覧を更新してください。'],
  skillFileInvalid: ['Use a nonempty UTF-8 .md/.txt file up to 128 KiB.', '请选择非空 UTF-8 .md/.txt 文件，最大 128 KiB。', '空でない UTF-8 の .md/.txt（最大 128 KiB）を選択してください。'],
  skillName: ['Skill name', 'Skill 名称', 'Skill 名'],
  skillImportText: ['Import instruction text (.md/.txt)', '导入指令文本（.md/.txt）', '指示テキストを読込（.md/.txt）'],
  skillInstructions: ['Instructions', '完整指令', '指示内容'],
  skillPackageLimit: ['Text only, max 128 KiB. Referenced files/scripts are not imported. Planner source limit: 32,000 characters including metadata.', '仅导入文本，最大 128 KiB；不会导入引用文件或执行脚本。Planner 单条上限为含元数据 32,000 字符。', 'テキストのみ、最大 128 KiB。参照ファイルやスクリプトは読み込みません。Planner はメタデータ込みで 32,000 文字までです。'],
  skillRequiredTools: ['Required tools (does not enable Agent permissions)', '依赖工具（不会自动开启 Agent 权限）', '必要なツール（Agent の権限は変更しません）'],
  skillResumePublish: ['Continue saving', '继续保存', '保存を再開'],
  skillSave: ['Save and enable Skill', '保存并启用 Skill', 'Skill を保存して有効化'],
  skillEvidenceTitle: ['Skill context evidence', 'Skill 上下文证据', 'Skill コンテキスト証跡'],
  skillEvidenceLoad: ['Load evidence', '查询加载记录', '証跡を読み込む'],
  skillEvidencePrepared: ['Context prepared (not proof of model compliance)', '已准备上下文（不代表模型一定遵循）', 'コンテキスト準備済み（モデルの遵守を保証しません）'],
  skillEvidenceNone: ['No preparation record; this does not prove successful loading.', '没有上下文准备记录，不能据此声称已成功加载。', '準備記録がありません。読込成功を示すものではありません。'],
  skillEvidenceFailed: ['Evidence unavailable', '证据暂不可用', '証跡を取得できません'],
  toolPickerSelected: ['Selected tools', '已选工具', '選択済みツール'],
  toolPickerEmpty: ['No tools selected', '尚未选择工具', 'ツールは未選択です'],
  toolPickerSearch: ['Search name or description', '搜索工具名称或说明', '名前や説明を検索'],
  toolPickerAll: ['All', '全部', 'すべて'],
  toolPickerAvailable: ['Available', '可用', '利用可能'],
  toolPickerFilter: ['Tool filter', '工具筛选', 'ツール絞り込み'],
  toolPickerCategory: ['Category', '分类', '分類'],
  toolPickerNetwork: ['Web & search', '网络与搜索', 'Web・検索'],
  toolPickerKnowledge: ['Knowledge', '知识检索', 'ナレッジ'],
  toolPickerFiles: ['Files & documents', '文件与文档', 'ファイル・文書'],
  toolPickerGit: ['Git', 'Git', 'Git'],
  toolPickerMcp: ['MCP & GitHub', 'MCP 与 GitHub', 'MCP・GitHub'],
  toolPickerCoding: ['Code execution', '代码执行', 'コード実行'],
  toolPickerOther: ['Other', '其他', 'その他'],
  toolPickerDetails: ['Technical details', '技术详情', '技術詳細'],
  toolPickerUnavailable: ['Not available in the current deployment; inspect details or check with the administrator.', '当前部署未提供此工具；可查看详情或联系管理员检查配置。', '現在の環境では利用できません。詳細を確認するか管理者にお問い合わせください。'],
  toolPickerMissing: ['No longer in catalog', '已不在工具目录中', 'カタログに存在しません'],
  toolPickerNoMatch: ['No matching tools', '没有匹配的工具', '一致するツールはありません'],
  toolPickerDraft: ['Selections update the draft only. Save the Agent to apply or submit for approval.', '勾选仅修改草稿；请点击 Agent 保存以生效或提交审批。', '選択は下書きのみ更新します。Agent を保存して適用または承認申請してください。'],
  toolPickerRemove: ['Remove tool', '移除工具', 'ツールを解除'],
  toolPickerResults: ['Results', '匹配工具', '検索結果'],
  deleteConversationAction: ['Delete conversation', '删除会话', '会話を削除'],
  editRoot: ['Edit root folder', '编辑根目录', 'ルートフォルダーを編集'],
  conversationSettings: ['Conversation settings', '会话设置', '会話設定'],
  conversationName: ['Conversation name', '会话名称', '会話名'],
  conversationAgent: ['Agent for this conversation', '本会话使用的 Agent', 'この会話のエージェント'],
  saveConversationName: ['Save name', '保存名称', '名前を保存'],
  conversationAgentHint: ['Choose the Agent for future messages. Prompts, model parameters and tools are managed on the Agent page.', '这里只选择后续消息使用的 Agent。提示词、模型参数和工具统一在 Agent 页面管理。', '今後のメッセージに使用するエージェントを選択します。指示・モデル設定・ツールはエージェント画面で管理します。'],
  manageAgentDefinition: ['Open Agent settings', '前往 Agent 页面配置', 'エージェント設定を開く'],
  belongsToRoot: ['Root folder', '所属根目录', '所属ルートフォルダー'],
  selectConversationToConfigure: ['Choose an Agent for the new conversation, or select an existing conversation to configure it.', '请为新会话选择 Agent，或选择已有会话进行设置。', '新しい会話のエージェントを選ぶか、既存の会話を選択して設定します。'],
  conversationSettingsLocked: ['Settings are locked while an operation is active.', '当前操作进行中，暂时不能修改会话设置。', '処理中は会話設定を変更できません。'],
  conversationSettingsFailed: ['Unable to save conversation settings', '无法保存会话设置', '会話設定を保存できません'],
  conversationRunDetails: ['Run details', '运行详情', '実行詳細'],
  jumpToLatestMessage: ['Jump to latest', '回到最新消息', '最新のメッセージへ'],
  messageFromYou: ['You', '你', 'あなた'],
  messageFromAssistant: ['Assistant', '助手', 'アシスタント'],
  linkedConversationTitle: ['Conversation', '会话', '会話'],
  finishStreamBeforeSwitch: ['Finish or stop this response before switching conversations.', '请先等待本次回答结束或停止生成，再切换会话。', '回答の完了を待つか停止してから、会話を切り替えてください。'],
  githubRepositoryRoot: ['Import GitHub repository', '导入 GitHub 仓库', 'GitHub リポジトリを追加'],
  existingRepositoryRoot: ['Use existing repository storage', '使用已有仓库代码', '既存のリポジトリを使用'],
  chooseGithubConnection: ['Select authorized GitHub connection', '选择已授权的 GitHub 连接', '認証済み GitHub 接続を選択'],
  refreshConnections: ['Refresh connections', '刷新连接列表', '接続一覧を更新'],
  streamDisconnectedRecovering: ['Connection interrupted; checking the saved Run status.', '连接已中断，正在查询后端运行状态。', '接続が中断されました。実行状態を確認しています。'],
  runStopping: ['Stopping at a safe boundary', '正在停止，等待当前调用收尾', '安全な境界で停止中'],
  runCancelled: ['Run cancelled', '运行已取消', '実行はキャンセルされました'],
  runFailed: ['Run did not complete', '运行未完成', '実行は完了していません'],
  runFinished: ['Run completed', '运行已结束', '実行完了'],
  runInBackground: ['Run in progress', '运行进行中', '実行中'],
  partialAnswerSaved: ['An incomplete answer has been saved. You can ask to continue.', '已保留部分回答，尚未完成，可继续提问。', '未完了の回答を保存しました。続行を依頼できます。'],
  runUncertainOutcome: ['Some call outcomes or usage are unconfirmed; cancellation does not imply zero usage.', '部分调用结果或用量待确认，取消不代表未产生用量。', '一部の呼出結果や使用量は未確認です。'],
  loadMoreConversations: ['Load more conversations', '加载更多会话', '会話をさらに読み込む'],
  loadOlderMessages: ['Load earlier messages', '加载更早消息', '以前のメッセージを読み込む'],
  loadMoreAgents: ['Load more agents', '加载更多 Agent', 'Agentをさらに読み込む'],
  scroll: ['Scroll', '滚动探索', 'スクロール'],
  product: ['Product', '产品', 'プロダクト'],
  principles: ['Principles', '理念', '設計思想'],
  system: ['System', '系统', 'システム'],
  access: ['Access', '进入', 'アクセス'],
  signIn: ['Sign in', '登录', 'ログイン'],
  enter: ['Enter', '进入', 'はじめる'],
  heroLine1: ['Build intelligence', '构建持续行动的', '動き続ける知性を'],
  heroLine2: ['that keeps moving.', '智能系统。', '構築する。'],
  heroCopy: [
    'Create agents that reason, remember, and act using your knowledge and tools. Observe every run. Improve continuously.',
    '让 Agent 运用你的知识与工具进行推理、记忆和行动。看见每次运行，持续进化。',
    '知識とツールを使って、考え、記憶し、行動するエージェントを。すべての実行を観測し、継続的に改善します。',
  ],
  start: ['Start building →', '开始构建 →', '構築をはじめる →'],
  seeHow: ['See how it works →', '了解运行方式 →', '仕組みを見る →'],
  durable: ['A durable agent system', '耐久的 Agent 系统', '永続するエージェントシステム'],
  durableCopy: [
    'Not another chat window. SpaceAgent gives every goal a plan, every action a trace, and every outcome a place to live.',
    '不只是另一个聊天窗口。SpaceAgent 为每个目标建立计划，为每次行动留下轨迹，也让每个结果有处可循。',
    '単なるチャット画面ではありません。すべての目標に計画を、すべての行動に履歴を、すべての成果に居場所を与えます。',
  ],
  intent: ['01 / INTENT', '01 / 意图', '01 / 意図'],
  intentLine1: ['Start with work,', '从工作出发，', 'プロンプトではなく、'],
  intentLine2: ['not prompts.', '而不是提示词。', '仕事から始める。'],
  intentCopy: [
    'Turn a goal into projects, tasks, and reviewable plans. Agents inherit the right context without owning the work itself.',
    '把目标拆成项目、任务和可审查的计划。Agent 获得正确上下文，但不取代工作的所有权。',
    '目標をプロジェクト、タスク、レビュー可能な計画へ。エージェントは仕事を所有せず、必要な文脈だけを引き継ぎます。',
  ],
  execution: ['02 / EXECUTION', '02 / 执行', '02 / 実行'],
  executionLine1: ['See every move', '实时看见', 'すべての動きを'],
  executionLine2: ['as it happens.', '每一步行动。', 'リアルタイムに。'],
  executionCopy: [
    'Follow reasoning, model calls, tools, checkpoints, approvals, and handoffs in one continuous run timeline.',
    '在一条连续时间线里追踪推理、模型调用、工具、检查点、审批与交接。',
    '推論、モデル呼び出し、ツール、チェックポイント、承認、引き継ぎを一つのタイムラインで追跡します。',
  ],
  memory: ['03 / MEMORY', '03 / 记忆', '03 / 記憶'],
  memoryLine1: ['Keep what matters.', '留下重要的，', '大切なものだけを残し、'],
  memoryLine2: ['Discard the noise.', '丢掉噪音。', 'ノイズを捨てる。'],
  memoryCopy: [
    'Build durable project knowledge from verified outcomes while conversations remain lightweight and recoverable.',
    '从已验证结果中沉淀长期项目知识，同时让对话保持轻量且可恢复。',
    '検証済みの成果から永続的なプロジェクト知識を構築し、会話は軽量かつ復元可能に保ちます。',
  ],
  systemLine1: ['One system.', '一个系统，', '一つのシステムで、'],
  systemLine2: ['Every state.', '承载所有状态。', 'すべての状態を。'],
  systemCopy: [
    'SpaceAgent keeps plans, workspaces, runs, model usage, tools, and approvals connected—without hiding the evidence behind a friendly answer.',
    'SpaceAgent 将计划、工作区、运行、模型用量、工具和审批连接起来，不让证据消失在一句友好的回答背后。',
    '計画、ワークスペース、実行、モデル利用、ツール、承認をつなぎ、親切な回答の裏に証拠を隠しません。',
  ],
  liveDurable: ['Live, durable, recoverable', '实时、耐久、可恢复', 'リアルタイム・永続・復元可能'],
  work: ['Work', '工作', 'ワーク'],
  agents: ['Agents', 'Agent', 'エージェント'],
  resources: ['Resources', '资源', 'リソース'],
  operations: ['Operations', '运行管理', 'オペレーション'],
  project: ['Project / Release intelligence', '项目 / 发布智能', 'プロジェクト / リリース知性'],
  runActive: ['Run active', '运行中', '実行中'],
  waiting: ['Awaiting approval', '等待审批', '承認待ち'],
  task: ['TASK-042 · Prepare the trusted beta release', 'TASK-042 · 准备可信测试版发布', 'TASK-042 · Trusted Beta リリースを準備'],
  plan: ['Plan / 5 steps', '计划 / 5 个步骤', '計画 / 5 ステップ'],
  task1: ['Inspect release boundary', '检查发布边界', 'リリース境界を確認'],
  task1Copy: ['Dependencies, runtime and schema.', '依赖、运行时与数据结构。', '依存関係、ランタイム、スキーマ。'],
  task2: ['Run architecture checks', '运行架构检查', 'アーキテクチャ検証'],
  task2Copy: ['Dependency rules verified.', '依赖规则已验证。', '依存ルールを検証済み。'],
  task3: ['Validate provider path', '验证模型链路', 'プロバイダ経路を検証'],
  task3Copy: ['Connection, chat and usage evidence.', '连接、对话与用量证据。', '接続、チャット、利用証跡。'],
  task4: ['Review artifacts', '审查交付物', '成果物をレビュー'],
  task4Copy: ['Patch and acceptance evidence.', '补丁与验收证据。', 'パッチと受入証跡。'],
  done: ['Done', '完成', '完了'],
  running: ['Running', '运行中', '実行中'],
  queued: ['Queued', '排队中', '待機中'],
  timeline: ['Run timeline', '运行时间线', '実行タイムライン'],
  context: ['Context', '上下文', 'コンテキスト'],
  model: ['Model', '模型', 'モデル'],
  tool: ['Tool', '工具', 'ツール'],
  approval: ['Approval', '审批', '承認'],
  event1: ['Context compiled', '上下文已编译', 'コンテキストを構築'],
  event1Copy: ['Project blueprint, task memory and 3 knowledge sources selected.', '已选择项目蓝图、任务记忆与 3 个知识源。', 'プロジェクト設計、タスク記憶、3つの知識ソースを選択。'],
  event2: ['Model route resolved', '模型路由已解析', 'モデル経路を決定'],
  event2Copy: ['Qwen primary · immutable price and budget evidence pinned.', '已固定 Qwen 主模型、不可变价格与预算证据。', 'Qwen を選択し、不変の価格・予算証跡を固定。'],
  event3: ['Tool completed', '工具执行完成', 'ツール実行完了'],
  event3Copy: ['Architecture validation passed with no dependency violations.', '架构验证通过，未发现依赖违规。', '依存違反なしでアーキテクチャ検証に合格。'],
  event4: ['Approval required', '需要审批', '承認が必要'],
  event4Copy: ['Apply reviewed source change to the local integration ref.', '将已审查的源码变更应用到本地集成引用。', 'レビュー済みの変更をローカル統合参照へ適用します。'],
  operatingLayer: ['The operating layer', '智能运行层', 'オペレーティングレイヤー'],
  controlLine1: ['Built to stay', '为始终可控', '制御し続けるために'],
  controlLine2: ['under control.', '而构建。', '設計する。'],
  controlCopy: ['Agents can move quickly because authority, evidence, and recovery stay explicit.', '正因为权限、证据和恢复机制始终明确，Agent 才能快速行动。', '権限、証跡、復元が明確だからこそ、エージェントは素早く動けます。'],
  cap1: ['Plan the work', '规划工作', '仕事を計画'],
  cap1Copy: ['Projects, tasks, plans, agents, and isolated workspaces stay connected by design.', '项目、任务、计划、Agent 与隔离工作区从设计上保持连接。', 'プロジェクト、タスク、計画、エージェント、分離ワークスペースを設計段階から接続。'],
  cap2: ['Read the run', '读懂运行', '実行を読み解く'],
  cap2Copy: ['Stream live progress, reconnect to durable events, and understand cost and tool evidence.', '实时查看进度、重连耐久事件，并理解成本与工具证据。', '進捗をストリーミングし、永続イベントへ再接続して、コストとツール証跡を理解。'],
  cap3: ['Approve the effect', '审批影响', '効果を承認'],
  cap3Copy: ['Keep secrets, mutations, budgets, and delivery behind exact, auditable boundaries.', '让密钥、变更、预算和交付始终处于精确、可审计的边界内。', '秘密、変更、予算、デリバリーを正確で監査可能な境界内に保ちます。'],
  closingLine1: ['Give intent', '让意图', '意図に'],
  closingLine2: ['some gravity.', '拥有引力。', '重力を。'],
  enterSpaceAgent: ['Enter SpaceAgent ↗', '进入 SpaceAgent ↗', 'SpaceAgentへ入る ↗'],
  stack: ['Java authority · TypeScript interaction', 'Java 权威状态 · TypeScript 交互', 'Java の権威状態 · TypeScript の操作層'],
  trustedBeta: ['Trusted beta', '可信测试版', 'Trusted Beta'],
  back: ['← Back to site', '← 返回官网', '← サイトへ戻る'],
  privatePlane: ['Private control plane', '私有控制平面', 'プライベート制御プレーン'],
  welcomeLine1: ['Return to', '回到你的', 'あなたの軌道へ'],
  welcomeLine2: ['your orbit.', '运行轨道。', '戻る。'],
  welcomeCopy: ['Your projects, agents, runs, and approvals are waiting exactly where you left them.', '你的项目、Agent、运行和审批都停留在离开时的位置。', 'プロジェクト、エージェント、実行、承認が、離れた場所でそのまま待っています。'],
  createLine1: ['Create work', '创建拥有', '仕事に'],
  createLine2: ['with gravity.', '引力的工作。', '重力を与える。'],
  createCopy: ['Begin with a personal organization, connect your model resources, and turn the first goal into a durable run.', '从个人组织开始，连接模型资源，把第一个目标转化为耐久运行。', '個人組織から始め、モデル資源を接続し、最初の目標を永続的な実行へ。'],
  accountAccess: ['Account access / 01', '账户访问 / 01', 'アカウントアクセス / 01'],
  welcomeBack: ['Welcome back.', '欢迎回来。', 'おかえりなさい。'],
  continueControl: ['Continue to your SpaceAgent control plane.', '继续进入你的 SpaceAgent 控制平面。', 'SpaceAgent の制御プレーンへ進みます。'],
  identity: ['Email or username', '邮箱或用户名', 'メールまたはユーザー名'],
  password: ['Password', '密码', 'パスワード'],
  identityPlaceholder: ['you@example.com', 'you@example.com', 'you@example.com'],
  passwordPlaceholder: ['Enter your password', '输入密码', 'パスワードを入力'],
  keepSigned: ['Keep me signed in', '保持登录', 'ログイン状態を保持'],
  forgot: ['Forgot password?', '忘记密码？', 'パスワードを忘れた？'],
  enterWorkspace: ['Enter workspace', '进入工作区', 'ワークスペースへ'],
  newHere: ['New to SpaceAgent?', '第一次使用 SpaceAgent？', 'SpaceAgent は初めて？'],
  createAccount: ['Create an account', '创建账户', 'アカウントを作成'],
  createAccess: ['Create account / 02', '创建账户 / 02', 'アカウント作成 / 02'],
  startBuilding: ['Start building.', '开始构建。', '構築を始める。'],
  createOrg: ['Create your personal organization and first workspace.', '创建个人组织和第一个工作区。', '個人組織と最初のワークスペースを作成します。'],
  displayName: ['Display name', '显示名称', '表示名'],
  namePlaceholder: ['How should we address you?', '我们该如何称呼你？', 'お名前を入力'],
  email: ['Email', '邮箱', 'メール'],
  newPasswordPlaceholder: ['At least 10 characters', '至少 10 个字符', '10文字以上'],
  acceptTerms: ['I accept the terms', '我接受相关条款', '利用規約に同意'],
  createWorkspace: ['Create workspace', '创建工作区', 'ワークスペースを作成'],
  already: ['Already have an account?', '已经有账户？', 'すでにアカウントをお持ち？'],
  show: ['Show', '显示', '表示'],
  hide: ['Hide', '隐藏', '非表示'],
  prototype: ['New frontend foundation · Authentication wiring comes next', '全新前端基础 · 下一步接入真实认证', '新しいフロントエンド基盤 · 次に認証を接続'],
  nativeSession: ['Native platform session', '原生平台会话', 'ネイティブプラットフォームセッション'],
  authFailed: ['Authentication failed', '认证失败', '認証に失敗しました'],
  restoringSession: ['Restoring session', '正在恢复会话', 'セッションを復元中'],
  signOut: ['Sign out', '退出登录', 'ログアウト'],
  sessionReady: ['Session ready.', '会话已就绪。', 'セッション準備完了。'],
  organization: ['Organization', '组织', '組織'],
  role: ['Role', '角色', 'ロール'],
  shellNext: ['Authentication is connected. The approved product shell is the next milestone.', '认证已完成对接。下一里程碑将实现已验收的产品工作台。', '認証接続が完了しました。次のマイルストーンで承認済みの製品シェルを実装します。'],
  primaryNavigation: ['Primary navigation', '主导航', 'メインナビゲーション'],
  overviewNav: ['Overview', '概览', '概要'],
  workspaceNav: ['Workspace', '工作台', 'ワークスペース'],
  chatNav: ['Chat', '对话', 'チャット'],
  projectNav: ['Project', '项目', 'プロジェクト'],
  createProject: ['Create Project', '创建项目', 'プロジェクトを作成'],
  agentsNav: ['Agents', 'Agent', 'エージェント'],
  automationNav: ['Automation', '自动化', '自動化'],
  memoryNav: ['Memory', '记忆', 'メモリ'],
  mcpNav: ['MCP Market', 'MCP 市场', 'MCP マーケット'],
  tracingNav: ['Run Tracing', '调用追踪', '実行トレース'],
  knowledgeNav: ['Knowledge', '知识库', 'ナレッジ'],
  modelsNav: ['Model Resources', '模型资源', 'モデル資源'],
  organizationNav: ['Organization', '组织设置', '組織設定'],
  adminControl: ['Admin control', '管理控制台', '管理コントロール'],
  change: ['Change', '更改', '変更'],
  lightMode: ['Switch to light mode', '切换到白天模式', 'ライトモードへ'],
  darkMode: ['Switch to dark mode', '切换到夜间模式', 'ダークモードへ'],
  systemConfirmation: ['System confirmation', '系统确认', 'システム確認'],
  switchOrganization: ['Switch organization?', '切换组织？', '組織を切り替えますか？'],
  organizationSwitchFailed: ['Organization switch failed', '组织切换失败', '組織の切替に失敗しました'],
  cancel: ['Cancel', '取消', 'キャンセル'],
  confirmSwitch: ['Confirm switch', '确认切换', '切替を確認'],
  switching: ['Switching', '正在切换', '切替中'],
  commandCenter: ['Command center', '指挥中心', 'コマンドセンター'],
  commandOverview: ['Command overview.', '指挥总览。', 'コマンド概要。'],
  retry: ['Retry', '重试', '再試行'],
  registeredAgents: ['Registered agents', 'Agent 数量', '登録エージェント'],
  sessions: ['Conversations', '会话数量', '会話数'],
  settledTokens: ['Settled tokens', '已结算 Token', '確定済みトークン'],
  settledCost: ['Settled cost', '已结算费用', '確定済みコスト'],
  incompleteCost: ['Incomplete pricing', '存在未定价调用', '未価格の呼出しあり'],
  agentTokenOrbit: ['Agent token orbit', 'Agent Token 轨道', 'エージェントトークン軌道'],
  usageByAgent: ['Usage by Agent', 'Agent 用量', 'エージェント別利用量'],
  calls: ['calls', '次调用', '回'],
  tokenTrend: ['Token trend', 'Token 消耗趋势', 'トークン推移'],
  realtime: ['Realtime', '实时运行', 'リアルタイム'],
  runtimeActive: ['Runtime active', '运行中 Runtime', '実行中 Runtime'],
  processing: ['Processing', '处理中', '処理中'],
  peakConcurrent: ['Peak concurrent', '并发峰值', '最大同時実行'],
  runtimeSessions: ['Runtime sessions', 'Runtime 会话', 'Runtime セッション'],
  sessionMessages: ['messages', '条消息', 'メッセージ'],
  stopSession: ['Stop', '停止', '停止'],
  viewTrace: ['View trace', '查看链路', 'トレースを表示'],
  previousPage: ['Previous', '上一页', '前へ'],
  nextPage: ['Next', '下一页', '次へ'],
  stopAllActive: ['Stop visible active', '停止当前页运行会话', '表示中の実行セッションを停止'],
  allActiveSessions: ['Visible active Runtime sessions', '当前页运行中的 Runtime 会话', '表示中の実行 Runtime セッション'],
  stopSessionTitle: ['Stop this Runtime session?', '停止该 Runtime 会话？', 'この Runtime セッションを停止しますか？'],
  stopAllSessionsTitle: ['Stop all visible active sessions?', '停止当前全部运行会话？', '表示中の実行セッションをすべて停止しますか？'],
  stopSessionHint: ['The backend will cancel the authoritative AgentRun. Completed effects are not rolled back and UNKNOWN effects are not retried.', '后端将取消权威 AgentRun；已经完成的效果不会回滚，UNKNOWN 效果也不会重试。', 'バックエンドが正規の AgentRun をキャンセルします。完了済みの効果は戻さず、UNKNOWN の効果も再試行しません。'],
  sessionStopFailed: ['Unable to stop the Runtime session', '无法停止 Runtime 会话', 'Runtime セッションを停止できません'],
  sessionBatchStopPartial: ['Some Runtime sessions could not be stopped. The list has been refreshed from backend evidence.', '部分 Runtime 会话未能停止，列表已根据后端证据刷新。', '一部の Runtime セッションを停止できませんでした。バックエンド証跡から一覧を更新しました。'],
  noRuntimeSessions: ['No Runtime sessions in this range.', '当前时间范围内没有 Runtime 会话。', 'この期間に Runtime セッションはありません。'],
  noUsageEvidence: ['No settled usage evidence in this range.', '当前时间范围内暂无已结算用量证据。', 'この期間には確定済み利用証跡がありません。'],
  chatLoadFailed: ['Unable to load Chat workspace', '无法加载 Chat 工作台', 'Chat ワークスペースを読み込めません'],
  messageLoadFailed: ['Unable to load messages', '无法加载消息', 'メッセージを読み込めません'],
  agentRequired: ['Create an Agent before starting a conversation.', '请先创建 Agent，再开始会话。', '会話を始める前にエージェントを作成してください。'],
  newConversation: ['New conversation', '新会话', '新しい会話'],
  conversationCreateFailed: ['Unable to create conversation', '无法创建会话', '会話を作成できません'],
  conversationDeleteFailed: ['Unable to delete conversation', '无法删除会话', '会話を削除できません'],
  delete: ['Delete', '删除', '削除'],
  deleteConversation: ['Delete this conversation?', '删除该会话？', 'この会話を削除しますか？'],
  streamCancelled: ['Response cancelled', '响应已取消', '応答をキャンセルしました'],
  streamFailed: ['Response stream failed', '响应流失败', '応答ストリームに失敗しました'],
  searchConversations: ['Search conversations', '搜索会话', '会話を検索'],
  noConversations: ['No conversations yet.', '暂无会话。', '会話はまだありません。'],
  noAgent: ['No Agent', '无 Agent', 'エージェントなし'],
  waitingForResponse: ['Waiting for response', '正在等待响应', '応答を待っています'],
  reasoningLive: ['Reasoning', '正在思考', '推論中'],
  reasoningComplete: ['Reasoned', '思考完成', '推論完了'],
  startConversation: ['Start a conversation.', '开始一次会话。', '会話を始める。'],
  startConversationHint: ['Select an existing conversation or create a new one.', '选择已有会话，或创建新会话。', '既存の会話を選択するか、新しく作成してください。'],
  composerPlaceholder: ['Describe the next objective…', '描述下一个目标…', '次の目標を入力…'],
  stop: ['Stop', '停止', '停止'],
  runInspector: ['Run inspector', '运行检查器', '実行インスペクタ'],
  activeAgent: ['Active Agent', '当前 Agent', 'アクティブエージェント'],
  activeContext: ['Active backend context', '当前后端上下文', '現在のバックエンドコンテキスト'],
  currentRun: ['Current run', '当前运行', '現在の実行'],
  runtimeEvents: ['Runtime events', 'Runtime 事件', 'Runtime イベント'],
  projectLoadFailed: ['Unable to load Projects', '无法加载项目', 'プロジェクトを読み込めません'],
  projectContextFailed: ['Unable to load Project context', '无法加载项目上下文', 'プロジェクト文脈を読み込めません'],
  projectCreateFailed: ['Unable to create Project', '无法创建项目', 'プロジェクトを作成できません'],
  projectUpdateFailed: ['Unable to update Project', '无法更新项目', 'プロジェクトを更新できません'],
  projectArchiveFailed: ['Unable to archive Project', '无法归档项目', 'プロジェクトをアーカイブできません'],
  projectRequired: ['Create or select a Project first.', '请先创建或选择项目。', '先にプロジェクトを作成または選択してください。'],
  projectDirectoryRequired: ['Create or select a Project directory first.', '请先创建或选择项目目录。', '先にプロジェクトディレクトリを作成または選択してください。'],
  newProjectDirectory: ['New directory', '新建目录', '新しいディレクトリ'],
  directoryName: ['Directory name', '目录名称', 'ディレクトリ名'],
  directoryPath: ['Relative path (optional)', '相对路径（可选）', '相対パス（任意）'],
  archiveDirectory: ['Archive directory', '归档目录', 'ディレクトリをアーカイブ'],
  activeProjectDirectory: ['Active directory', '当前项目目录', '現在のディレクトリ'],
  projectDirectoryCreateFailed: ['Unable to create Project directory', '无法创建项目目录', 'プロジェクトディレクトリを作成できません'],
  projectDirectoryArchiveFailed: ['Unable to archive Project directory', '无法归档项目目录', 'プロジェクトディレクトリをアーカイブできません'],
  projectIntake: ['Project intake', '项目分析', 'プロジェクト分析'],
  projectIntakeGoal: ['Describe the project outcome to analyze and plan…', '描述需要分析和规划的项目目标…', '分析・計画するプロジェクト目標を入力…'],
  startProjectIntake: ['Analyze and propose plan', '分析并生成提案', '分析して計画を提案'],
  projectIntakeLoadFailed: ['Unable to load Project intake jobs', '无法加载项目分析任务', 'プロジェクト分析ジョブを読み込めません'],
  projectIntakeCreateFailed: ['Unable to start Project intake', '无法启动项目分析', 'プロジェクト分析を開始できません'],
  projectIntakeReviewFailed: ['Unable to review Project proposal', '无法审核项目提案', 'プロジェクト提案を審査できません'],
  projectIntakeRejectReason: ['Reason for rejecting this proposal', '请输入拒绝该提案的原因', '提案を拒否する理由'],
  confirmProposal: ['Confirm proposal', '确认提案', '提案を確認'],
  rejectProposal: ['Reject proposal', '拒绝提案', '提案を拒否'],
  noProjectIntakes: ['No intake jobs for this directory.', '当前目录暂无分析任务。', 'このディレクトリには分析ジョブがありません。'],
  projectExecution: ['Plan execution', '计划执行', '計画実行'],
  projectExecutionLoadFailed: ['Unable to load Project execution jobs', '无法加载项目执行任务', 'プロジェクト実行ジョブを読み込めません'],
  projectExecutionStartFailed: ['Unable to start the Project plan execution', '无法启动项目计划执行', 'プロジェクト計画の実行を開始できません'],
  executePlan: ['Execute plan', '执行计划', '計画を実行'],
  refreshExecution: ['Refresh execution evidence', '刷新执行证据', '実行証跡を更新'],
  pauseExecution: ['Pause', '暂停', '一時停止'],
  resumeExecution: ['Resume', '恢复', '再開'],
  cancelExecution: ['Cancel execution', '取消执行', '実行をキャンセル'],
  pauseExecutionTitle: ['Pause this execution?', '暂停该执行？', 'この実行を一時停止しますか？'],
  cancelExecutionTitle: ['Cancel this execution?', '取消该执行？', 'この実行をキャンセルしますか？'],
  pauseExecutionHint: ['The Runtime will stop only after reaching a safe boundary.', 'Runtime 只会在到达安全边界后停止。', 'Runtime は安全な境界に到達してから停止します。'],
  cancelExecutionHint: ['Cancellation is fenced and terminal. Ambiguous effects remain blocked for reconciliation.', '取消操作受修订保护且为终态；存在歧义的效果仍会保持阻塞并等待调和。', 'キャンセルはリビジョンで保護された終端操作です。不明な効果は調整待ちのままブロックされます。'],
  executionControlReason: ['Control reason', '控制原因', '制御理由'],
  desiredState: ['Desired state', '目标状态', '目標状態'],
  controlReasonRecorded: ['reason recorded', '已记录原因', '理由を記録済み'],
  noControlReason: ['no control reason', '无控制原因', '制御理由なし'],
  projectExecutionControlFailed: ['Unable to control this Project execution', '无法控制该项目执行', 'このプロジェクト実行を制御できません'],
  reviewerAgent: ['Reviewer Agent', '审查 Agent', 'レビュー Agent'],
  reviewerAgentRequired: ['A distinct Reviewer Agent is required.', '需要选择不同的审查 Agent。', '別の Reviewer Agent が必要です。'],
  currentConfiguration: ['Current configuration', '当前配置', '現在の設定'],
  stepAssignment: ['Plan step assignment', '计划步骤绑定', '計画ステップ割当'],
  configureAssignment: ['Assignment', '配置绑定', '割当設定'],
  assignmentSource: ['Assignment scope', '绑定范围', '割当範囲'],
  planDefault: ['Plan default', '计划默认', '計画デフォルト'],
  stepOverride: ['Step override', '步骤覆盖', 'ステップ上書き'],
  primaryAgent: ['Primary Agent', '主执行 Agent', 'プライマリ Agent'],
  assignmentModelPool: ['Current model / pool', '当前模型 / 模型池', '現在のモデル / プール'],
  saveAssignment: ['Save assignment', '保存绑定', '割当を保存'],
  noStepAssignment: ['No authoritative assignment for this step.', '该步骤暂无权威绑定。', 'このステップには正規の割当がありません。'],
  assignmentLoadFailed: ['Unable to load the step assignment', '无法读取步骤绑定', 'ステップ割当を読み込めません'],
  assignmentSaveFailed: ['Unable to save the step assignment', '无法保存步骤绑定', 'ステップ割当を保存できません'],
  serverDerivedEvidence: ['Server-derived evidence', '后端生成证据', 'サーバー生成証跡'],
  createHandoff: ['Create handoff', '创建交接', 'ハンドオフを作成'],
  handoffTitle: ['Continue in another Conversation and Agent', '交接到另一个会话和 Agent', '別の会話と Agent に引き継ぐ'],
  targetConversation: ['Target Conversation', '目标会话', '引継ぎ先の会話'],
  targetAgent: ['Target Agent', '目标 Agent', '引継ぎ先 Agent'],
  handoffEligibility: ['A handoff requires a waiting or blocked Job, another active Conversation in this directory, and distinct target and Reviewer Agents.', '交接需要处于等待或阻塞状态的执行任务、当前目录中的另一个活跃会话，以及不同的目标 Agent 和审查 Agent。', 'ハンドオフには待機中またはブロック中のジョブ、このディレクトリ内の別の有効な会話、異なる対象 Agent と Reviewer Agent が必要です。'],
  handoffCreateFailed: ['Unable to create the Project handoff', '无法创建项目交接', 'プロジェクトのハンドオフを作成できません'],
  noProjectExecutions: ['No autonomous execution job for the active Plan step.', '当前计划步骤暂无自动执行任务。', '現在の計画ステップには自動実行ジョブがありません。'],
  captureRecovery: ['Capture recovery package', '生成恢复包', '復旧パッケージを作成'],
  projectRecoveryFailed: ['Unable to capture the recovery package', '无法生成恢复包', '復旧パッケージを作成できません'],
  recoveryPackage: ['Recovery package', '项目恢复包', '復旧パッケージ'],
  nextAction: ['Next action', '下一步操作', '次のアクション'],
  blockers: ['Blockers', '阻断项', 'ブロッカー'],
  close: ['Close', '关闭', '閉じる'],
  reject: ['Reject', '拒绝', '拒否'],
  approveAndResume: ['Approve and resume', '批准并继续', '承認して再開'],
  reconcileAndResume: ['Verify effect and resume', '核验效果并继续', '効果を検証して再開'],
  projectResumeFailed: ['Unable to resume the suspended Project run', '无法继续暂停的项目运行', '一時停止したプロジェクト実行を再開できません'],
  runWaitingApproval: ['Run paused before the Tool effect and is waiting for an approval decision.', '运行已在 Tool 生效前暂停，正在等待审批决定。', 'Tool の実行前に停止し、承認判断を待っています。'],
  runWaitingReconciliation: ['The Tool effect is UNKNOWN. Verify its bounded postcondition before continuing.', 'Tool 效果状态为 UNKNOWN，需要核验受限后置条件后才能继续。', 'Tool 効果は UNKNOWN です。再開前に制限された事後条件を検証してください。'],
  newProjectConversation: ['New Project conversation', '新项目会话', '新しいプロジェクト会話'],
  repositoryChat: ['Repository chat', '仓库会话', 'リポジトリ会話'],
  createRoot: ['New root folder', '新建根目录', 'ルートフォルダーを作成'],
  rootType: ['Root type', '根目录类型', 'ルート種類'],
  rootName: ['Root folder name', '根目录名称', 'ルートフォルダー名'],
  emptyRoot: ['Managed folder', '空白目录', '管理フォルダー'],
  repositoryRoot: ['Repository', '仓库目录', 'リポジトリ'],
  emptyRootStorageHint: ['Creates real managed storage on the server. Conversations belong directly to this folder.', '将在服务器创建真实存储，会话直接位于该目录下。', 'サーバーに実ストレージを作成します。'],
  repositoryRootHint: ['Use an imported repository as a root folder.', '将已导入仓库作为根目录。', 'インポート済みリポジトリをルートにします。'],
  deleteRoot: ['Delete root folder', '删除根目录', 'ルートフォルダーを削除'],
  deleteRootRetentionHint: ['Removes this logical folder and its conversation entries from the list. Stored code remains intact. Physical storage cleanup requires an administrator.', '仅移除逻辑目录及其会话入口，保留已存储的代码。物理存储清理需要管理员操作。', '論理フォルダーの入口のみ削除し、コードは保持します。物理削除は管理者のみ可能です。'],
  environmentInfo: ['Environment', '环境信息', '環境情報'],
  changes: ['Changes', '变更', '変更'],
  executionEnvironment: ['Environment', '执行环境', '実行環境'],
  isolatedWorkspace: ['Isolated workspace', '隔离工作区', '隔離ワークスペース'],
  codeBranch: ['Code branch', '代码分支', 'コードブランチ'],
  selectBranch: ['Select branch', '选择分支', 'ブランチを選択'],
  workbenchSelectRepository: ['Select a repository first', '请先选择仓库', 'リポジトリを選択してください'],
  workbenchLoadingBranches: ['Loading branches…', '正在加载分支…', 'ブランチを読み込み中…'],
  workbenchBranchesNotLoaded: ['Branches are not synchronized yet. Prepare the repository first; you can enter a branch name there.', '尚未同步分支，请先准备仓库；准备窗口中可填写分支名称。', 'ブランチ未同期です。先にリポジトリを準備してください。'],
  workbenchChooseBranchToPrepare: ['Choose a branch, then prepare its workspace.', '选择分支后，即可准备该分支的工作区。', 'ブランチを選んでワークスペースを準備してください。'],
  workbenchBranchBusy: ['Branch changes are unavailable while the current operation is running.', '当前操作进行中，暂时不能切换分支。', '操作中はブランチを切り替えられません。'],
  switchBranch: ['Switch branch', '切换分支', 'ブランチを切替'],
  branchIsolationHint: ['Switch to a separate workspace for this branch. The previous workspace and its changes are retained.', '切换到该分支的独立工作区，原工作区及改动会保留。', '別ワークスペースへ切替えます。元の変更は保持されます。'],
  repositoryFiles: ['Repository files', '仓库文件', 'リポジトリファイル'],
  changedFiles: ['changed files', '个变更文件', '変更ファイル'],
  noCodeChanges: ['No tracked changes', '暂无受跟踪文件改动', '追跡ファイルの変更なし'],
  repositoryListTruncated: ['Only the first 300 entries are shown. Open a subfolder to continue.', '当前最多显示 300 项，可打开子目录继续查看。', '先頭300件を表示しています。'],
  repositoryFileTruncated: ['File preview truncated at 200,000 characters.', '文件预览已截断至 200,000 字符。', 'プレビューは200,000文字までです。'],
  advancedProjectControls: ['Tasks and execution controls', '任务与执行管理', 'タスクと実行管理'],
  aiCodingMode: ['AI coding', 'AI 编程', 'AI コーディング'],
  askRepositoryMode: ['Ask about code', '询问代码', 'コードに質問'],
  codingLaunchTitle: ['Delegate coding task', '交给 AI 编程', 'AI にコーディングを依頼'],
  codingLaunchHint: ['Approve this task for the coding Agent and a separate reviewer, enabling the required coding tools on the selected Agent. File changes and commands still follow workspace permissions and approval policy.', '确认将此需求交给编程 Agent 和独立评审 Agent 执行。文件修改与命令仍遵循工作区权限及审批策略，并为选中的 Agent 启用必要的编程工具。', '選択した Agent の必要なコーディングツールを有効にし、独立レビュアーと実行します。変更とコマンドは承認ポリシーに従います。'],
  distinctReviewerRequired: ['Select a different review Agent.', '请选择不同于编程 Agent 的评审 Agent。', '別のレビュー Agent を選択してください。'],
  codingAcceptance: ['Implement the requested change and provide successful relevant test evidence.', '实现所请求的改动，并提供相关测试通过的证据。', '要求を実装し、関連テストの成功証拠を提示する。'],
  codingAlreadyRunning: ['The current coding task is still running or awaiting approval.', '当前编程任务仍在执行或等待审批。', '現在のタスクは実行中か承認待ちです。'],
  confirmCodingLaunch: ['Approve and start', '确认并开始执行', '承認して開始'],
  collapseNavigation: ['Collapse navigation', '收起导航栏', 'ナビゲーションを閉じる'],
  expandNavigation: ['Expand navigation', '展开导航栏', 'ナビゲーションを開く'],
  collapseProjectTree: ['Collapse project list', '收起项目列表', 'プロジェクト一覧を閉じる'],
  expandProjectTree: ['Expand project list', '展开项目列表', 'プロジェクト一覧を開く'],
  collapseInspector: ['Collapse inspector', '收起右侧检查器', 'インスペクターを閉じる'],
  expandInspector: ['Expand inspector', '展开右侧检查器', 'インスペクターを開く'],
  repositoryPrepare: ['Prepare repository chat', '准备仓库会话', 'リポジトリ会話を準備'],
  repositoryPrepareRequired: ['Prepare a workspace before reading this repository.', '请先准备仓库会话，再读取仓库代码。', 'コードを読む前にワークスペースを準備してください。'],
  repositoryPrepareHint: ['Select a repository. Preparation creates its conversation and workspace, and enables file_list/file_read on the current Agent. An unbound Knowledge Search selection will be removed.', '选择仓库后，准备对应的会话和工作区，并为当前 Agent 启用文件列表与文件读取工具；未绑定知识库的 Knowledge Search 勾选会被移除。', 'リポジトリの会話とワークスペースを準備し、現在の Agent のファイル一覧・読み取りを有効にします。未設定の Knowledge Search は解除します。'],
  repositoryReadTask: ['Read repository code', '读取仓库代码', 'リポジトリコードを読む'],
  repositorySourceRequired: ['Import a repository source first.', '请先导入仓库代码源。', '先にリポジトリをインポートしてください。'],
  repositorySandboxUnavailable: ['Repository file tools are unavailable. Check the Sandbox service.', '仓库文件工具不可用，请检查 Sandbox 服务。', 'ファイルツールが利用できません。Sandbox を確認してください。'],
  repositoryToolApprovalRequired: ['File tool configuration is awaiting owner approval. Prepare again after approval.', '文件工具配置正在等待所有者审批，通过后再次准备仓库会话。', 'ファイルツールの承認待ちです。承認後に再準備してください。'],
  repositoryWorkspacePending: ['The workspace is not ready or multiple workspaces exist. Check workspace status.', '工作区尚未就绪或存在多个工作区，请检查工作区状态。', 'ワークスペースが未準備か複数存在します。状態を確認してください。'],
  repositoryReadReady: ['Repository reading ready', '仓库读取已就绪', 'リポジトリ読み取り準備完了'],
  noProjects: ['No Projects yet.', '暂无项目。', 'プロジェクトはまだありません。'],
  projectName: ['Project name', '项目名称', 'プロジェクト名'],
  description: ['Description', '说明', '説明'],
  create: ['Create', '创建', '作成'],
  startProjectConversation: ['Start a Project conversation.', '开始一次项目会话。', 'プロジェクト会話を始める。'],
  projectComposer: ['Describe the next Project objective…', '描述下一个项目目标…', '次のプロジェクト目標を入力…'],
  projectInspector: ['Project inspector', '项目检查器', 'プロジェクトインスペクタ'],
  activeProject: ['Active Project', '当前项目', 'アクティブプロジェクト'],
  tasks: ['Tasks', '任务', 'タスク'],
  workspaces: ['Workspaces', '工作区', 'ワークスペース'],
  noTasks: ['No Tasks', '暂无任务', 'タスクなし'],
  newTask: ['New Task', '新建任务', '新規タスク'],
  taskTitle: ['Task title', '任务标题', 'タスク名'],
  taskGoal: ['Task goal', '任务目标', 'タスク目標'],
  createTask: ['Create Task', '创建任务', 'タスクを作成'],
  editTask: ['Edit Task intent', '编辑任务意图', 'タスク意図を編集'],
  updateTask: ['Save Task', '保存任务', 'タスクを保存'],
  taskConstraints: ['Constraints (one per line)', '约束条件（每行一项）', '制約（1 行に 1 件）'],
  taskAcceptanceCriteria: ['Acceptance criteria (one per line)', '验收标准（每行一项）', '受入条件（1 行に 1 件）'],
  taskUpdateFailed: ['Unable to update Task intent', '无法更新任务意图', 'タスク意図を更新できません'],
  activeTask: ['Active Task', '当前任务', 'アクティブタスク'],
  clearTask: ['Clear Task', '清除任务', 'タスクを解除'],
  rootTask: ['Root Task', '根任务', 'ルートタスク'],
  parentTask: ['Parent', '父任务', '親タスク'],
  taskPlans: ['Task Plans', '任务计划', 'タスク計画'],
  newPlan: ['Create Plan', '创建计划', '計画を作成'],
  childTask: ['Child Task', '子任务', '子タスク'],
  expectedOutput: ['Expected output', '预期产出', '期待する成果物'],
  approvalRequired: ['Approval required', '需要审批', '承認が必要'],
  addPlanStep: ['Add plan step', '添加计划步骤', '計画ステップを追加'],
  removePlanStep: ['Remove plan step', '移除计划步骤', '計画ステップを削除'],
  stepKey: ['Stable step key', '稳定步骤标识', '安定ステップキー'],
  dependencies: ['Depends on steps', '依赖步骤', '依存ステップ'],
  dependsOn: ['Depends on', '依赖', '依存先'],
  viewPlanSteps: ['View dependency graph', '查看依赖关系', '依存関係を表示'],
  noDependencies: ['No other steps yet.', '暂无其他步骤。', '他のステップはまだありません。'],
  requiredCapability: ['Required capability (optional)', '所需能力（可选）', '必要な能力（任意）'],
  planDraftInvalid: ['Each step needs a unique key, child Task and expected output.', '每个步骤都需要唯一标识、子任务和预期产出。', '各ステップには一意のキー、子タスク、期待成果物が必要です。'],
  planNeedsChildTask: ['Create a direct child Task before authoring a Plan.', '创建直接子任务后才能编写计划。', '計画を作成する前に直接の子タスクを作成してください。'],
  noTaskPlans: ['No Task Plans', '暂无任务计划', 'タスク計画なし'],
  markReady: ['Mark ready', '标记就绪', '準備完了にする'],
  startTask: ['Start', '开始', '開始'],
  blockTask: ['Block', '阻塞', 'ブロック'],
  completeTask: ['Complete', '完成', '完了'],
  failTask: ['Fail', '失败', '失敗'],
  cancelTask: ['Cancel Task', '取消任务', 'タスクを取消'],
  proposePlan: ['Propose', '提交计划', '提案'],
  approvePlan: ['Approve', '批准', '承認'],
  activatePlan: ['Activate', '激活', '有効化'],
  completePlan: ['Complete', '完成计划', '計画を完了'],
  cancelPlan: ['Cancel', '取消计划', '計画を取消'],
  noWorkspaces: ['No Workspaces', '暂无工作区', 'ワークスペースなし'],
  sourceRepositories: ['Source repositories', '代码源', 'ソースリポジトリ'],
  addGithubSource: ['Add GitHub source', '添加 GitHub 代码源', 'GitHub ソースを追加'],
  githubMcpConnection: ['GitHub MCP connection', 'GitHub MCP 连接', 'GitHub MCP 接続'],
  loadRepositories: ['Load repositories', '加载仓库', 'リポジトリを読み込む'],
  repository: ['Repository', '仓库', 'リポジトリ'],
  publicGithubUrl: ['Or public GitHub URL', '或填写公开 GitHub URL', 'または公開 GitHub URL'],
  importSource: ['Import source', '导入代码源', 'ソースを取り込む'],
  noGithubConnection: ['Connect and authorize GitHub MCP in the MCP market first.', '请先在 MCP 市场连接并授权 GitHub MCP。', '先に MCP マーケットで GitHub MCP を接続・認証してください。'],
  noSourceRepositories: ['No source repositories', '暂无代码源', 'ソースリポジトリなし'],
  sourceLoadFailed: ['Unable to load source controls', '无法加载代码源控制', 'ソース制御を読み込めません'],
  sourceImportFailed: ['Unable to import source', '无法导入代码源', 'ソースを取り込めません'],
  sourceArchiveFailed: ['Unable to archive source', '无法归档代码源', 'ソースをアーカイブできません'],
  provisionWorkspace: ['Provision workspace', '创建工作区', 'ワークスペースを準備'],
  workspaceTask: ['Workspace Task', '工作区任务', 'ワークスペースのタスク'],
  baseReference: ['Base branch or ref', '基础分支或引用', '基準ブランチまたは参照'],
  workspaceProvisionFailed: ['Unable to provision workspace', '无法创建工作区', 'ワークスペースを準備できません'],
  workspaceArchiveFailed: ['Unable to archive workspace', '无法归档工作区', 'ワークスペースをアーカイブできません'],
  archiveSource: ['Archive source?', '归档该代码源？', 'このソースをアーカイブしますか？'],
  archiveWorkspace: ['Archive workspace?', '归档该工作区？', 'このワークスペースをアーカイブしますか？'],
  editProject: ['Edit Project', '编辑项目', 'プロジェクトを編集'],
  archiveProject: ['Archive this Project?', '归档该项目？', 'このプロジェクトをアーカイブしますか？'],
  agentDefinitions: ['Agent definitions', 'Agent 定义', 'エージェント定義'],
  agentLoadFailed: ['Unable to load Agent definitions', '无法加载 Agent 定义', 'エージェント定義を読み込めません'],
  manageAgentKeys: ['API keys', 'API 密钥', 'API キー'],
  agentKeysTitle: ['Agent API keys', 'Agent API 密钥', 'Agent API キー'],
  agentKeysCopy: ['Create scoped credentials for this Agent. The raw key is shown once and is never stored by the browser.', '为此 Agent 创建限定权限的凭据。原始密钥只展示一次，浏览器不会保存。', 'この Agent 用のスコープ付き認証情報を作成します。生キーは一度だけ表示され、ブラウザには保存されません。'],
  agentKeyName: ['Key name', '密钥名称', 'キー名'],
  agentKeyExpiry: ['Expiry (optional)', '过期时间（可选）', '有効期限（任意）'],
  createAgentKey: ['Create API key', '创建 API 密钥', 'API キーを作成'],
  agentKeysLoadFailed: ['Unable to load Agent API keys', '无法加载 Agent API 密钥', 'Agent API キーを読み込めません'],
  agentKeyCreateFailed: ['Unable to create Agent API key', '无法创建 Agent API 密钥', 'Agent API キーを作成できません'],
  agentKeyScopeRequired: ['Select at least one API key scope.', '请至少选择一个 API 密钥权限。', 'API キーのスコープを1つ以上選択してください。'],
  agentKeyRevokeFailed: ['Unable to revoke Agent API key', '无法撤销 Agent API 密钥', 'Agent API キーを取り消せません'],
  noAgentKeys: ['No API keys have been created.', '尚未创建 API 密钥。', 'API キーはまだありません。'],
  oneTimeAgentKey: ['Copy this key now', '请立即复制此密钥', '今すぐこのキーをコピー'],
  oneTimeAgentKeyWarning: ['It cannot be retrieved after this dialog closes.', '关闭弹窗后无法再次获取。', 'このダイアログを閉じると再取得できません。'],
  revokeAgentKey: ['Revoke', '撤销', '取り消す'],
  confirmRevokeAgentKey: ['Confirm revoke', '确认撤销', '取り消しを確定'],
  expiresNever: ['Never expires', '永不过期', '無期限'],
  createAgent: ['Create Agent', '创建 Agent', 'Agent を作成'],
  agentWriteModeDIRECT: ['Direct save', '直接保存', '直接保存'],
  agentWriteModeOWNER_APPROVAL_REQUIRED: ['Owner approval required', '需要组织所有者审批', '組織所有者の承認が必要'],
  agentWriteModeREAD_ONLY: ['Read only', '只读', '読み取り専用'],
  submitAgentChange: ['Submit change', '提交变更', '変更を提出'],
  agentChangeApplied: ['The current Agent configuration was saved and is immediately effective.', '当前 Agent 配置已保存并立即生效。', '現在の Agent 設定を保存し、直ちに反映しました。'],
  agentChangePending: ['The current configuration is unchanged. This proposal is waiting for the Organization owner.', '当前配置未变更；该提案正在等待组织所有者审批。', '現在の設定は変更されていません。この提案は組織所有者の承認待ちです。'],
  agentChanges: ['Agent edit approval', 'Agent 编辑审批', 'Agent 編集の承認'],
  agentApprovals: ['Pending approvals', '待审批', '承認待ち'],
  agentApprovalPending: ['Pending approval', '等待审批', '承認待ち'],
  pendingAgentApprovals: ['Pending Agent edit approval', '待处理的 Agent 编辑审批', '保留中の Agent 編集承認'],
  agentChangesCopy: ['Only the current pending Agent edit proposal is shown. Approval updates the single current configuration; this is not version history.', '这里只显示当前待处理的 Agent 编辑提案。批准后更新唯一的当前配置；这不是版本历史。', '現在保留中の Agent 編集提案のみを表示します。承認後は唯一の現在設定が更新され、バージョン履歴ではありません。'],
  agentChangesLoadFailed: ['Unable to load Agent configuration changes', '无法加载 Agent 配置变更', 'Agent 設定変更を読み込めません'],
  noAgentChanges: ['No Agent edit is awaiting approval.', '当前没有等待审批的 Agent 编辑。', '承認待ちの Agent 編集はありません。'],
  requester: ['Requester', '申请人', '申請者'],
  updated: ['Updated', '更新时间', '更新日時'],
  viewProposedConfiguration: ['View proposed configuration', '查看提议配置', '提案設定を表示'],
  approveAgentChange: ['Approve', '批准', '承認'],
  rejectAgentChange: ['Reject', '拒绝', '却下'],
  approveAgentChangeWarning: ['Confirm this pending proposal. Approval immediately replaces the Agent current configuration.', '确认批准此待处理提案；批准后将立即替换 Agent 当前配置。', 'この保留中の提案を確認してください。承認すると Agent の現在設定が直ちに置き換わります。'],
  rejectAgentChangeWarning: ['Reject this exact proposal. The current Agent configuration will remain unchanged.', '拒绝此精确提案；Agent 当前配置不会改变。', 'この正確な提案を却下します。Agent の現在設定は変更されません。'],
  confirmApproveAgentChange: ['Confirm approval', '确认批准', '承認を確定'],
  confirmRejectAgentChange: ['Confirm rejection', '确认拒绝', '却下を確定'],
  agentChangeDecisionFailed: ['Unable to record the Agent configuration decision', '无法记录 Agent 配置决定', 'Agent 設定の判断を記録できません'],
  agentChangeConflict: ['This proposal changed before the decision. The authoritative state has been refreshed.', '决定前提案状态已变化，已刷新后端权威状态。', '判断前に提案の状態が変わりました。バックエンドの権威状態を更新しました。'],
  refresh: ['Refresh', '刷新', '更新'],
  expires: ['Expires', '过期时间', '有効期限'],
  decisionNote: ['Decision note (optional)', '决定说明（可选）', '判断メモ（任意）'],
  executeAt: ['Execute at', '执行时间', '実行時刻'],
  automationControl: ['Automation control.', '自动化控制中心。', '自動化コントロール。'],
  automationControlHint: ['Create and inspect backend-owned Agent schedules and their execution evidence.', '创建并查看由后端管理的 Agent 计划及执行证据。', 'バックエンド管理の Agent スケジュールと実行証跡を作成・確認します。'],
  newAutomation: ['New automation', '新建自动化', '新しい自動化'],
  editAutomation: ['Edit automation', '编辑自动化', '自動化を編集'],
  automationSchedules: ['Schedules', '计划', 'スケジュール'],
  noAutomationSchedules: ['No schedules for this Agent.', '当前 Agent 暂无计划。', 'この Agent にスケジュールはありません。'],
  selectAutomation: ['Select a schedule.', '请选择一个计划。', 'スケジュールを選択してください。'],
  scheduleType: ['Schedule type', '计划类型', 'スケジュール種別'],
  nextRun: ['Next run', '下次运行', '次回実行'],
  runCount: ['Run count', '运行次数', '実行回数'],
  lastRun: ['Last run', '最近运行', '最終実行'],
  automationExecutions: ['Execution evidence', '执行证据', '実行証跡'],
  noAutomationExecutions: ['No executions recorded.', '暂无执行记录。', '実行記録はありません。'],
  automationPrompt: ['Automation prompt', '自动化提示词', '自動化プロンプト'],
  timezone: ['Timezone', '时区', 'タイムゾーン'],
  maxRetries: ['Maximum retries', '最大重试次数', '最大再試行回数'],
  cronExpression: ['Cron expression', 'Cron 表达式', 'Cron 式'],
  runNow: ['Run now', '立即运行', '今すぐ実行'],
  runAutomationNow: ['Run this automation now?', '确认立即运行自动化？', 'この自動化を今すぐ実行しますか？'],
  archiveAutomation: ['Archive this automation?', '确认归档自动化？', 'この自動化をアーカイブしますか？'],
  automationRunWarning: ['This creates one backend execution and may require Governance approval. It is never retried automatically by the browser.', '这会创建一次后端执行，并可能需要治理审批；浏览器不会自动重试。', 'バックエンド実行を1件作成し、承認が必要な場合があります。ブラウザは自動再試行しません。'],
  automationArchiveWarning: ['Archived schedules no longer produce new executions.', '归档后的计划不会再产生新的执行。', 'アーカイブ後は新しい実行を生成しません。'],
  automationLoadFailed: ['Unable to load Automation schedules', '无法加载自动化计划', '自動化スケジュールを読み込めません'],
  automationExecutionsLoadFailed: ['Unable to load execution evidence', '无法加载执行证据', '実行証跡を読み込めません'],
  automationSaveFailed: ['Unable to save the Automation schedule', '无法保存自动化计划', '自動化スケジュールを保存できません'],
  automationActionFailed: ['Unable to complete the Automation action', '无法完成自动化操作', '自動化操作を完了できません'],
  memoryControl: ['Memory control.', '记忆控制中心。', 'メモリコントロール。'],
  memoryControlHint: ['Review candidates and inspect consolidated User, Project and Task memory owned by the backend.', '审核候选记忆并查看由后端管理的用户、项目和任务记忆。', 'バックエンド管理のユーザー・プロジェクト・タスクメモリを審査・確認します。'],
  memoryScopeId: ['Scope ID', '范围 ID', 'スコープ ID'],
  userId: ['User ID', '用户 ID', 'ユーザー ID'],
  projectId: ['Project ID', '项目 ID', 'プロジェクト ID'],
  taskId: ['Task ID', '任务 ID', 'タスク ID'],
  consolidatedMemory: ['Consolidated memory', '已合并记忆', '統合済みメモリ'],
  noConsolidatedMemory: ['No consolidated memory in this scope.', '当前范围暂无已合并记忆。', 'このスコープに統合済みメモリはありません。'],
  pendingMemoryCandidates: ['Pending candidates', '待审核候选', '審査待ち候補'],
  noPendingMemory: ['No pending candidates in this scope.', '当前范围暂无待审核候选。', 'このスコープに審査待ち候補はありません。'],
  memoryScopeRequired: ['Enter an authorized scope ID.', '请输入有权限的范围 ID。', '認可されたスコープ ID を入力してください。'],
  proposeMemoryCandidate: ['Propose memory candidate', '提交候选记忆', 'メモリ候補を提案'],
  memoryKind: ['Memory kind', '记忆类型', 'メモリ種別'],
  memorySourceId: ['Source reference', '来源引用', 'ソース参照'],
  memoryContent: ['Candidate content', '候选内容', '候補内容'],
  confidence: ['Confidence', '置信度', '信頼度'],
  dedupeKey: ['Dedupe key (optional)', '去重键（可选）', '重複排除キー（任意）'],
  propose: ['Propose', '提交候选', '提案'],
  consolidateTaskMemory: ['Consolidate Task memory', '合并任务记忆', 'タスクメモリを統合'],
  memoryConsolidationHint: ['The backend evaluates Task candidates and promotes only eligible evidence.', '后端会评估任务候选，仅提升符合条件的证据。', 'バックエンドがタスク候補を評価し、条件を満たす証跡のみ昇格します。'],
  selectTaskScope: ['Select TASK scope to consolidate.', '选择 TASK 范围后才能合并。', '統合するには TASK スコープを選択してください。'],
  acceptThreshold: ['Accept threshold', '接受阈值', '承認しきい値'],
  promotionThreshold: ['Promotion threshold', '提升阈值', '昇格しきい値'],
  promoteMemoryToUser: ['Promote eligible memory to my User scope', '将符合条件的记忆提升到我的用户范围', '条件を満たすメモリを自分のユーザースコープへ昇格'],
  consolidate: ['Consolidate', '开始合并', '統合'],
  accepted: ['Accepted', '已接受', '承認済み'],
  rejected: ['Rejected', '已拒绝', '拒否済み'],
  promoted: ['Promoted', '已提升', '昇格済み'],
  acceptMemoryCandidate: ['Accept this Memory candidate?', '确认接受候选记忆？', 'このメモリ候補を承認しますか？'],
  rejectMemoryCandidate: ['Reject this Memory candidate?', '确认拒绝候选记忆？', 'このメモリ候補を拒否しますか？'],
  reasonOptional: ['Reason (optional)', '原因（可选）', '理由（任意）'],
  memoryLoadFailed: ['Unable to load Memory evidence', '无法加载记忆证据', 'メモリ証跡を読み込めません'],
  memoryCandidateSaveFailed: ['Unable to create the Memory candidate', '无法创建候选记忆', 'メモリ候補を作成できません'],
  memoryReviewFailed: ['Unable to review the Memory candidate', '无法审核候选记忆', 'メモリ候補を審査できません'],
  memoryConsolidationFailed: ['Unable to consolidate Task memory', '无法合并任务记忆', 'タスクメモリを統合できません'],
  memoryThresholdInvalid: ['Promotion threshold must be greater than or equal to the accept threshold.', '提升阈值必须大于或等于接受阈值。', '昇格しきい値は承認しきい値以上である必要があります。'],
  inferenceBudget: ['Organization inference budget', '组织推理预算', '組織推論予算'],
  requests: ['Requests', '请求', 'リクエスト'],
  cost: ['Cost', '费用', 'コスト'],
  configureBudget: ['Configure budget', '配置预算', '予算を設定'],
  enforceBudget: ['Enforce this Organization budget', '启用当前组织预算限制', 'この組織予算を適用'],
  monthlyRequestLimit: ['Monthly request limit', '每月请求上限', '月間リクエスト上限'],
  monthlyTokenLimit: ['Monthly Token limit', '每月 Token 上限', '月間トークン上限'],
  monthlyCostLimitMicros: ['Monthly cost limit (USD micros)', '每月费用上限（美元微单位）', '月間コスト上限（USD マイクロ）'],
  budgetAuthorityHint: ['Consumed and reserved usage is calculated by the backend. Zero limits are interpreted by the backend policy.', '已消耗和预留用量由后端计算；零值限制由后端策略解释。', '消費済み・予約済み使用量はバックエンドが計算し、ゼロ制限もバックエンドポリシーが解釈します。'],
  inferenceBudgetSaveFailed: ['Unable to configure the inference budget', '无法配置推理预算', '推論予算を設定できません'],
  pricing: ['Pricing', '定价', '価格'],
  modelPricing: ['Model pricing', '模型定价', 'モデル価格'],
  priceVersions: ['Immutable price versions', '不可变价格版本', '不変価格バージョン'],
  noModelPrices: ['No price versions recorded.', '暂无价格版本。', '価格バージョンはありません。'],
  createPriceVersion: ['Create price version', '创建价格版本', '価格バージョンを作成'],
  immutablePriceHint: ['Price windows are immutable and may not overlap. Rates use USD micros per one million Tokens.', '价格窗口不可变且不能重叠；费率单位为每百万 Token 的美元微单位。', '価格期間は不変かつ重複不可です。単位は100万トークン当たりのUSDマイクロです。'],
  inputMicrosPerMillion: ['Input rate (micros / 1M Tokens)', '输入费率（微单位/百万 Token）', '入力単価（マイクロ/100万トークン）'],
  outputMicrosPerMillion: ['Output rate (micros / 1M Tokens)', '输出费率（微单位/百万 Token）', '出力単価（マイクロ/100万トークン）'],
  effectiveFrom: ['Effective from (blank = backend now)', '生效时间（留空为后端当前时间）', '適用開始（空欄はバックエンド現在時刻）'],
  effectiveUntil: ['Effective until', '失效时间', '適用終了'],
  modelPricesLoadFailed: ['Unable to load Model prices', '无法加载模型价格', 'モデル価格を読み込めません'],
  modelPriceWindowInvalid: ['Effective-until must be later than effective-from.', '失效时间必须晚于生效时间。', '適用終了は適用開始より後である必要があります。'],
  modelPriceCreateFailed: ['Unable to create the Model price version', '无法创建模型价格版本', 'モデル価格バージョンを作成できません'],
  pause: ['Pause', '暂停', '一時停止'],
  resume: ['Resume', '恢复', '再開'],
  save: ['Save', '保存', '保存'],
  agentCreateFailed: ['Unable to create Agent', '无法创建 Agent', 'エージェントを作成できません'],
  agentSaveFailed: ['Unable to save Agent definition', '无法保存 Agent 定义', 'エージェント定義を保存できません'],
  agentDeleteFailed: ['Unable to delete Agent', '无法删除 Agent', 'Agent を削除できません'],
  agentDeletedRefreshFailed: ['Agent deleted, but the refreshed list could not be loaded.', 'Agent 已删除，但无法重新加载最新列表。', 'Agent は削除されましたが、最新の一覧を再読み込みできませんでした。'],
  archive: ['Archive', '归档', 'アーカイブ'],
  deleteAgent: ['Delete this Agent?', '删除该 Agent？', 'この Agent を削除しますか？'],
  agentDeleteWarning: ['The Agent will be removed from active use. Existing Run snapshots and historical evidence remain available for audit.', '该 Agent 将从可用列表移除；已有 Run 快照和历史证据仍会保留用于审计。', 'Agent は利用可能一覧から削除されます。既存の Run スナップショットと履歴証跡は監査用に保持されます。'],
  confirmDeleteAgent: ['Confirm delete', '确认删除', '削除を確認'],
  confirmArchive: ['Confirm archive', '确认归档', 'アーカイブを確認'],
  untitledAgent: ['Untitled Agent', '未命名 Agent', '名称未設定エージェント'],
  noDescription: ['No description', '暂无说明', '説明なし'],
  noAgents: ['No Agents yet.', '暂无 Agent。', 'エージェントはまだありません。'],
  loadingAgents: ['Loading Agent definitions…', '正在加载 Agent 定义…', 'エージェント定義を読み込み中…'],
  createFirstAgent: ['Create the first Agent.', '创建第一个 Agent。', '最初のエージェントを作成してください。'],
  agentName: ['Agent name', 'Agent 名称', 'エージェント名'],
  saved: ['Saved', '已保存', '保存済み'],
  saving: ['Saving', '正在保存', '保存中'],
  saveDefinition: ['Save definition', '保存定义', '定義を保存'],
  identityAndPrompt: ['Identity and instruction', '身份与指令', '識別と指示'],
  systemInstruction: ['System instruction', '系统指令', 'システム指示'],
  modelPool: ['Model pool', '模型池', 'モデルプール'],
  routingPool: ['Routing pool', '路由池', 'ルーティングプール'],
  directBinding: ['Direct model binding', '直接绑定模型', 'モデルを直接指定'],
  strategy: ['Strategy', '策略', '戦略'],
  status: ['Status', '状态', '状態'],
  providerId: ['Provider ID', '提供商 ID', 'プロバイダ ID'],
  modelId: ['Model ID', '模型 ID', 'モデル ID'],
  searchAvailableModels: ['Type to search active models', '输入关键字搜索可用模型', '入力して利用可能なモデルを検索'],
  modelAutocompleteHint: ['Type any part of a model or provider name; choose a result to fill both Provider ID and Model ID.', '输入模型或提供商名称的任意部分；点击候选项会同时填入 Provider ID 和 Model ID。', 'モデル名またはプロバイダ名の一部を入力し、候補を選ぶと Provider ID と Model ID が同時に入力されます。'],
  noActiveModels: ['No active configured models. Test a Provider and add a model first.', '暂无可用模型，请先测试 Provider 并添加模型。', '有効な設定済みモデルがありません。先に Provider をテストしてモデルを追加してください。'],
  temperature: ['Temperature', '温度', 'Temperature'],
  executionBoundary: ['Execution boundary', '执行边界', '実行境界'],
  permissionMode: ['Permission mode', '权限模式', '権限モード'],
  sandbox: ['Sandbox', '沙箱', 'サンドボックス'],
  sandboxManaged: ['Platform-managed isolated worker', '平台托管的隔离 Worker', 'プラットフォーム管理の分離 Worker'],
  sandboxContainerManaged: ['Disposable OCI container; platform-managed', '平台托管的一次性 OCI 容器', 'プラットフォーム管理の使い捨て OCI コンテナ'],
  sandboxCompatibility: ['In-process compatibility; Coding commands unavailable', '进程内兼容模式；Coding 命令不可用', 'プロセス内互換モード。Coding コマンドは利用不可'],
  networkAccess: ['Network access', '网络权限', 'ネットワークアクセス'],
  networkAccessHint: ['Allow this definition to request network tools', '允许该定义请求网络工具', 'この定義によるネットワークツール要求を許可'],
  sessionBudget: ['Session limits', '会话限制', 'セッション制限'],
  maxTurns: ['Maximum turns', '最大会话轮次', '最大ターン数'],
  tokenBudget: ['Output token budget', '输出 Token 预算', '出力トークン予算'],
  memorySetting: ['Memory', '记忆', 'メモリ'],
  memoryHint: ['Persist eligible memory after verified runs', '在已验证运行后沉淀符合条件的记忆', '検証済み実行後に対象メモリを保存'],
  ragKnowledge: ['RAG and knowledge', 'RAG 与知识库', 'RAG とナレッジ'],
  enableRag: ['Enable retrieval', '启用检索', '検索を有効化'],
  sourcesBound: ['sources bound', '个知识源已绑定', '件のソースを接続'],
  noKnowledgeSources: ['No knowledge sources available.', '暂无可用知识源。', '利用可能なナレッジソースがありません。'],
  skillsAndTools: ['Skills and tools', 'Skill 与工具', 'Skill とツール'],
  skillIds: ['Skill IDs', 'Skill ID', 'Skill ID'],
  toolIds: ['Tool IDs', '工具 ID', 'ツール ID'],
  registeredSkills: ['Registered skills', '已注册 Skill', '登録済み Skill'],
  executableTools: ['Executable tools', '可执行工具', '実行可能ツール'],
  noRegisteredSkills: ['No executable Skill registry is available yet.', '当前暂无可执行 Skill 注册表。', '実行可能な Skill レジストリはまだありません。'],
  noExecutableTools: ['No executable tools are registered.', '当前暂无已注册的可执行工具。', '実行可能なツールは登録されていません。'],
  readOnlyTool: ['Read only', '只读', '読み取り専用'],
  mutatingTool: ['Mutating', '可变更', '変更あり'],
  networkTool: ['Network', '网络', 'ネットワーク'],
  workspaceTool: ['Workspace', '工作区', 'ワークスペース'],
  unavailableTool: ['Unavailable', '当前不可用', '利用不可'],
  toolNetworkPolicyWarning: ['Selected Tools require network access. Enable Network access before saving.', '已选工具需要网络权限，请在保存前启用“网络权限”。', '選択したツールにはネットワーク権限が必要です。保存前に有効化してください。'],
  toolKnowledgePolicyWarning: ['Knowledge Search requires retrieval to be enabled and at least one Knowledge source to be bound.', 'Knowledge Search 需要启用检索并至少绑定一个知识源。', 'Knowledge Search には検索の有効化と1件以上のナレッジソース接続が必要です。'],
  toolWorkspacePolicyHint: ['Workspace Tools run only inside a READY managed Project Workspace.', '工作区工具仅能在 READY 状态的托管项目工作区内运行。', 'ワークスペースツールは READY 状態の管理対象プロジェクト内でのみ実行されます。'],
  unavailableToolWarning: ['Remove unavailable Tools before saving this definition.', '保存定义前请移除当前不可用的工具。', '保存前に利用不可のツールを解除してください。'],
  identifierHint: ['Comma-separated public identifiers', '使用逗号分隔公开标识符', '公開識別子をカンマ区切りで入力'],
  definitionStatus: ['Definition status', '定义状态', '定義ステータス'],
  bindings: ['Bindings', '绑定', '接続'],
  skills: ['Skills', 'Skills', 'Skills'],
  tools: ['Tools', '工具', 'ツール'],
  knowledgeRegistry: ['Knowledge registry.', '知识注册中心。', 'ナレッジレジストリ。'],
  knowledgeRegistryHint: ['Import inspectable sources, build embeddings, and test retrieval before binding them to an Agent.', '导入可检查的知识源，构建向量索引，并在绑定到 Agent 前测试检索结果。', '検査可能なソースを取り込み、ベクトル索引を構築し、エージェントへ接続する前に検索をテストします。'],
  knowledgeLoadFailed: ['Unable to load knowledge sources', '无法加载知识源', 'ナレッジソースを読み込めません'],
  knowledgeChunkLoadFailed: ['Unable to load index evidence', '无法加载索引证据', '索引証跡を読み込めません'],
  knowledgeImportFailed: ['Knowledge import failed', '知识导入失败', 'ナレッジの取り込みに失敗しました'],
  knowledgeDeleteFailed: ['Unable to remove knowledge source', '无法移除知识源', 'ナレッジソースを削除できません'],
  retrievalFailed: ['Retrieval test failed', '检索测试失败', '検索テストに失敗しました'],
  documents: ['Documents', '文档', 'ドキュメント'],
  searchKnowledge: ['Search knowledge sources', '搜索知识源', 'ナレッジソースを検索'],
  allStatuses: ['All statuses', '全部状态', 'すべての状態'],
  localImport: ['Local import', '本地导入', 'ローカル取込'],
  onlineImport: ['Import online source', '导入在线知识源', 'オンラインソースを取り込む'],
  pasteText: ['Paste text', '粘贴文本', 'テキスト貼付'],
  knowledgeSources: ['Knowledge sources', '知识源', 'ナレッジソース'],
  indexed: ['Indexed', '已索引', '索引済み'],
  referenceOnly: ['Reference', '引用记录', '参照'],
  noKnowledgeDocuments: ['No knowledge sources match this view.', '当前视图没有知识源。', 'この表示に一致するナレッジソースはありません。'],
  sourceInspector: ['Source inspector', '知识源检查器', 'ソースインスペクタ'],
  selectedSource: ['Selected source', '当前知识源', '選択中のソース'],
  indexEvidence: ['Index evidence', '索引证据', '索引証跡'],
  chunks: ['Chunks', '分块', 'チャンク'],
  dimensions: ['Dimensions', '向量维度', '次元数'],
  testRetrieval: ['Test retrieval', '测试检索', '検索をテスト'],
  retrievalQuery: ['Ask this source…', '向此知识源提问…', 'このソースへ質問…'],
  noRetrievalMatches: ['No matches yet.', '暂无检索结果。', '一致する結果はありません。'],
  removeSource: ['Remove source', '移除知识源', 'ソースを削除'],
  selectKnowledgeSource: ['Select a source to inspect it.', '选择一个知识源进行检查。', '検査するソースを選択してください。'],
  localImportHint: ['Text, Markdown, JSON and CSV are read in the browser and sent to the platform processing pipeline.', '浏览器读取 Text、Markdown、JSON 或 CSV，并交给平台处理与索引。', 'Text、Markdown、JSON、CSV をブラウザで読み取り、プラットフォームの処理パイプラインへ送ります。'],
  chooseLocalFile: ['Choose a local text file', '选择本地文本文件', 'ローカルテキストファイルを選択'],
  importAndIndex: ['Import and index', '导入并建立索引', '取り込んで索引化'],
  onlineImportHint: ['The platform fetches a bounded public HTTPS source, parses it, builds embeddings, and activates the new content only after the complete pipeline succeeds.', '平台会受限抓取公开 HTTPS 内容，完成解析与向量化后才会激活新的知识内容。', 'プラットフォームが公開 HTTPS ソースを制限付きで取得し、解析とベクトル化がすべて成功してから新しい内容を有効化します。'],
  sourceName: ['Source name', '知识源名称', 'ソース名'],
  sourceUrl: ['Source URL', '知识源 URL', 'ソース URL'],
  urlRefreshMode: ['Refresh policy', '刷新策略', '更新ポリシー'],
  manualUrlRefresh: ['Fetch once', '抓取一次', '1 回取得'],
  periodicUrlRefresh: ['Periodic refresh', '定期刷新', '定期更新'],
  refreshIntervalMinutes: ['Refresh interval (minutes)', '刷新间隔（分钟）', '更新間隔（分）'],
  maximumUrlMegabytes: ['Maximum response size (MB)', '最大响应大小（MB）', '最大レスポンスサイズ（MB）'],
  urlIngestion: ['URL ingestion', 'URL 抓取', 'URL 取り込み'],
  refreshUrlEvidence: ['Refresh status', '刷新状态', '状態を更新'],
  pauseUrlIngestion: ['Pause refresh', '暂停刷新', '更新を一時停止'],
  resumeUrlIngestion: ['Resume and fetch', '恢复并抓取', '再開して取得'],
  knowledgeUrlCreateFailed: ['Unable to start URL ingestion; the source reference remains available for retry.', '无法启动 URL 抓取；知识源引用已保留，可再次重试。', 'URL 取り込みを開始できません。ソース参照は再試行用に保持されています。'],
  knowledgeUrlStatusFailed: ['Unable to refresh URL ingestion status', '无法刷新 URL 抓取状态', 'URL 取り込み状態を更新できません'],
  knowledgeUrlControlFailed: ['Unable to update URL ingestion lifecycle', '无法更新 URL 抓取生命周期', 'URL 取り込みの状態を更新できません'],
  contentType: ['Content type', '内容类型', 'コンテンツタイプ'],
  saveReference: ['Save reference', '保存引用', '参照を保存'],
  pasteTextHint: ['Create and index a compact text source immediately.', '立即创建并索引一份纯文本知识源。', 'コンパクトなテキストソースを作成し、すぐに索引化します。'],
  content: ['Content', '内容', '内容'],
  removeKnowledgeSource: ['Remove knowledge source?', '移除知识源？', 'ナレッジソースを削除しますか？'],
  modelResourceCenter: ['Model resource center.', '模型资源中心。', 'モデル資源センター。'],
  modelResourceHint: ['Register model providers, verify connectivity, curate available models, and compose auditable routing pools.', '注册模型提供商、验证连接、管理可用模型，并组合可审计的路由池。', 'モデルプロバイダを登録し、接続を検証し、利用モデルと監査可能なルーティングプールを管理します。'],
  modelResourcesLoadFailed: ['Unable to load model resources', '无法加载模型资源', 'モデル資源を読み込めません'],
  providerModelsLoadFailed: ['Unable to load provider models', '无法加载提供商模型', 'プロバイダモデルを読み込めません'],
  poolMembersLoadFailed: ['Unable to load pool members', '无法加载模型池成员', 'プールメンバーを読み込めません'],
  providerCreateFailed: ['Unable to create provider', '无法创建模型提供商', 'プロバイダを作成できません'],
  poolCreateFailed: ['Unable to create model pool', '无法创建模型池', 'モデルプールを作成できません'],
  providerTestFailed: ['Provider connection test failed', '模型提供商连接测试失败', 'プロバイダ接続テストに失敗しました'],
  modelAddFailed: ['Unable to add model', '无法添加模型', 'モデルを追加できません'],
  modelAddedSuccessfully: ['Model added successfully', '模型添加成功', 'モデルを追加しました'],
  poolMemberAddFailed: ['Unable to add pool member', '无法添加模型池成员', 'プールメンバーを追加できません'],
  poolStatusFailed: ['Unable to change pool status', '无法更改模型池状态', 'プール状態を変更できません'],
  createPool: ['Create pool', '创建模型池', 'プールを作成'],
  addProvider: ['Add provider', '添加提供商', 'プロバイダを追加'],
  modelProviders: ['Model providers', '模型提供商', 'モデルプロバイダ'],
  providerType: ['Provider type', '提供商类型', 'プロバイダ種別'],
  lastLatency: ['Last latency', '最近延迟', '直近レイテンシ'],
  defaultProvider: ['Default provider', '默认提供商', '既定プロバイダ'],
  available: ['Available', '可用', '利用可能'],
  open: ['Open', '打开', '開く'],
  noProviders: ['No model providers configured.', '暂无模型提供商。', 'モデルプロバイダが設定されていません。'],
  routingPools: ['Routing pools', '路由模型池', 'ルーティングプール'],
  noModelPools: ['No routing pools configured.', '暂无路由模型池。', 'ルーティングプールが設定されていません。'],
  providerName: ['Provider name', '提供商名称', 'プロバイダ名'],
  baseUrl: ['Base URL', 'Base URL', 'Base URL'],
  authType: ['Authentication', '认证方式', '認証方式'],
  setDefault: ['Set as default provider', '设为默认提供商', '既定プロバイダに設定'],
  initialModel: ['Initial model', '初始模型', '初期モデル'],
  createProvider: ['Create provider', '创建提供商', 'プロバイダを作成'],
  poolName: ['Pool name', '模型池名称', 'プール名'],
  visibility: ['Visibility', '可见范围', '公開範囲'],
  routingStrategy: ['Routing strategy', '路由策略', 'ルーティング戦略'],
  fallbackRouting: ['Enable fallback routing', '启用回退路由', 'フォールバックを有効化'],
  noConnectionEvidence: ['Not tested yet', '尚未测试', '未テスト'],
  testing: ['Testing', '正在测试', 'テスト中'],
  testConnection: ['Test connection', '测试连接', '接続テスト'],
  testingConnection: ['Testing connection…', '正在测试连接…', '接続をテスト中…'],
  waitingForProvider: ['Waiting for the provider response', '正在等待模型提供商响应', 'プロバイダの応答を待っています'],
  connectionSucceeded: ['Connection succeeded', '连接成功', '接続成功'],
  connectionFailed: ['Connection failed', '连接失败', '接続失敗'],
  discoveredModels: ['Models found', '发现模型', '検出モデル'],
  testedAt: ['Tested at', '测试时间', 'テスト時刻'],
  providerAuthFailedHint: ['The provider rejected the configured credentials. Update the API key and test again.', '模型提供商拒绝了当前凭证，请更新 API Key 后重新测试。', 'プロバイダが認証情報を拒否しました。API Key を更新して再テストしてください。'],
  providerConnectionFailedHint: ['The backend reached the test workflow, but the provider did not become healthy. Check the endpoint, model and credentials.', '后端已经执行连接测试，但提供商未达到健康状态，请检查地址、模型和凭证。', 'バックエンドは接続テストを実行しましたが、正常状態になりませんでした。エンドポイント、モデル、認証情報を確認してください。'],
  providerReady: ['Model discovery completed', '模型目录发现完成', 'モデル検出が完了しました'],
  testModel: ['Test model', '测试模型', 'モデルをテスト'],
  modelTestFailed: ['Unable to test model', '无法测试模型', 'モデルをテストできません'],
  modelAvailable: ['Model available', '模型可用', 'モデル利用可能'],
  modelUnavailable: ['Model unavailable', '模型不可用', 'モデル利用不可'],
  howToAddModel: ['How to add a model', '如何添加模型', 'モデルの追加方法'],
  modelGuideOne: ['If the connection shows PROVIDER_AUTH_FAILED, choose Edit and replace the API key first.', '如果连接显示 PROVIDER_AUTH_FAILED，请先点击“编辑”并更新正确的 API Key。', 'PROVIDER_AUTH_FAILED の場合は、先に「編集」から正しい API Key を設定してください。'],
  modelGuideTwo: ['Test the connection. A successful test can return model IDs that you can select below.', '点击“测试连接”。成功后，后端发现的模型 ID 会显示在下方供一键选择。', '接続テストを実行します。成功すると検出されたモデル ID を下から選択できます。'],
  modelGuideThree: ['Enter the exact provider model ID, a readable display name, and its context limit, then choose Add model.', '填写提供商真实的 MODEL ID、便于识别的显示名称和上下文上限，然后点击“添加模型”。', '正確な MODEL ID、表示名、コンテキスト上限を入力して「モデルを追加」を選択します。'],
  chooseDiscoveredModel: ['Choose a discovered model to prefill the form', '选择已发现模型，一键填入表单', '検出モデルを選択してフォームへ入力'],
  modelFieldsHint: ['MODEL ID must exactly match the provider API, for example qwen-plus. Display name is only used in the SpaceAgent UI.', 'MODEL ID 必须与提供商 API 完全一致，例如 qwen-plus；DISPLAY NAME 只用于 SpaceAgent 界面展示。', 'MODEL ID はプロバイダ API と完全一致する必要があります（例: qwen-plus）。表示名は SpaceAgent UI のみで使用します。'],
  edit: ['Edit', '编辑', '編集'],
  editProvider: ['Edit provider', '编辑模型提供商', 'プロバイダを編集'],
  deleteProvider: ['Delete provider', '删除提供商', 'プロバイダを削除'],
  providerUpdateFailed: ['Unable to update provider', '无法更新模型提供商', 'プロバイダを更新できません'],
  newApiKeyOptional: ['New API key (optional)', '新 API Key（可选）', '新しい API Key（任意）'],
  keepCurrentSecret: ['Leave blank to keep the current key', '留空则保留当前密钥', '空欄の場合は現在のキーを保持'],
  enabled: ['Enabled', '启用', '有効'],
  saveChanges: ['Save changes', '保存修改', '変更を保存'],
  resourceRemoveFailed: ['Unable to remove this resource', '无法移除该资源', 'このリソースを削除できません'],
  confirmDeleteProvider: ['Delete this provider?', '删除该模型提供商？', 'このプロバイダを削除しますか？'],
  confirmDeleteModel: ['Remove this model?', '移除该模型？', 'このモデルを削除しますか？'],
  confirmRemovePoolMember: ['Remove this pool member?', '移除该模型池成员？', 'このプールメンバーを削除しますか？'],
  confirmRemove: ['Confirm removal', '确认移除', '削除を確認'],
  providerModels: ['Provider models', '提供商模型', 'プロバイダモデル'],
  addModel: ['Add model', '添加模型', 'モデルを追加'],
  disablePool: ['Disable pool', '停用模型池', 'プールを無効化'],
  activatePool: ['Activate pool', '启用模型池', 'プールを有効化'],
  poolMembers: ['Pool members', '模型池成员', 'プールメンバー'],
  noPoolMembers: ['No models in this pool.', '该模型池暂无模型。', 'このプールにモデルはありません。'],
  addPoolMember: ['Add to pool', '添加到模型池', 'プールへ追加'],
  providerModel: ['Provider model', '提供商模型', 'プロバイダモデル'],
  priority: ['Priority', '优先级', '優先度'],
  weight: ['Weight', '权重', '重み'],
  capabilityRegistry: ['Capability registry.', '能力注册中心。', 'ケイパビリティレジストリ。'],
  capabilityRegistryHint: ['Install verified MCP capabilities, connect scoped endpoints, and keep authentication material behind the platform boundary.', '安装已验证的 MCP 能力、连接受限端点，并让认证材料始终留在平台边界内。', '検証済み MCP ケイパビリティを導入し、スコープされたエンドポイントへ接続し、認証情報をプラットフォーム境界内に保ちます。'],
  mcpLoadFailed: ['Unable to load MCP registry', '无法加载 MCP 注册中心', 'MCP レジストリを読み込めません'],
  mcpInstallFailed: ['Unable to install MCP', '无法安装 MCP', 'MCP をインストールできません'],
  mcpConnectFailed: ['Unable to connect MCP', '无法连接 MCP', 'MCP に接続できません'],
  mcpLifecycleFailed: ['Unable to change MCP lifecycle', '无法更改 MCP 生命周期状态', 'MCP ライフサイクルを変更できません'],
  githubOAuthFailed: ['GitHub MCP authorization failed', 'GitHub MCP 授权失败', 'GitHub MCP 認証に失敗しました'],
  mcpOAuthFailed: ['MCP OAuth authorization failed', 'MCP OAuth 授权失败', 'MCP OAuth 認証に失敗しました'],
  mcpVersionsFailed: ['Unable to load approved MCP versions', '无法加载已批准的 MCP 版本', '承認済み MCP バージョンを読み込めません'],
  mcpQualificationFailed: ['MCP connection qualification failed', 'MCP 连接资格验证失败', 'MCP 接続の検証に失敗しました'],
  mcpQualificationLoadFailed: ['Unable to load qualification evidence', '无法加载资格验证证据', '検証証跡を読み込めません'],
  connectCustomMcp: ['Connect custom MCP', '创建自有 MCP 连接', 'カスタム MCP に接続'],
  searchMcp: ['Search MCP capabilities', '搜索 MCP 能力', 'MCP ケイパビリティを検索'],
  results: ['results', '个结果', '件'],
  connectedMcp: ['Installed MCP', '已安装 MCP', 'インストール済み MCP'],
  noConnectedMcp: ['No MCP installations yet.', '暂无 MCP 安装。', 'MCP はまだインストールされていません。'],
  marketplaceMcp: ['Registry catalog', '注册中心 MCP', 'レジストリカタログ'],
  continueOAuth: ['Continue OAuth', '继续 OAuth 授权', 'OAuth を続行'],
  reauthorizeGithub: ['Reauthorize GitHub', '重新授权 GitHub', 'GitHub を再認証'],
  githubReauthorizeHint: ['Renew the GitHub connection in MCP Marketplace, then return here and prepare the repository again.', '请到 MCP 市场重新授权 GitHub 连接，完成后回到这里再次准备仓库。', 'MCP マーケットで GitHub を再認証し、ここに戻ってリポジトリを再準備してください。'],
  openMcpReauthorization: ['Open MCP Marketplace (new tab)', '前往 MCP 市场重新授权（新标签页）', 'MCP マーケットを開く（新しいタブ）'],
  connect: ['Connect', '连接', '接続'],
  manage: ['Manage', '管理', '管理'],
  editConnection: ['Edit connection', '编辑连接', '接続を編集'],
  saveConnection: ['Save connection', '保存连接', '接続を保存'],
  revoke: ['Revoke', '撤销', '取消'],
  disable: ['Disable', '停用', '無効化'],
  confirmRevokeConnection: ['Revoke this connection?', '撤销该 MCP 连接？', 'この接続を取り消しますか？'],
  confirmDisableMcp: ['Disable this installation?', '停用该 MCP 安装？', 'このインストールを無効化しますか？'],
  confirm: ['Confirm', '确认', '確認'],
  install: ['Install', '安装', 'インストール'],
  installationScope: ['Installation scope', '安装范围', 'インストール範囲'],
  installAndContinue: ['Install and continue', '安装并继续', 'インストールして続行'],
  githubConnectionHint: ['Create the official remote connection first, then continue through host OAuth. Direct GitHub tokens are never accepted here.', '先创建官方远程连接，再通过主机 OAuth 完成授权；这里不会接受 GitHub 直传 Token。', '公式リモート接続を作成し、ホスト OAuth で続行します。GitHub トークンの直接入力は受け付けません。'],
  customConnectionHint: ['Only HTTPS Streamable HTTP endpoints accepted by the platform policy can be stored.', '只允许保存符合平台策略的 HTTPS Streamable HTTP 端点。', 'プラットフォームポリシーが許可する HTTPS Streamable HTTP エンドポイントのみ保存できます。'],
  authentication: ['Authentication', '认证方式', '認証方式'],
  headerName: ['Header name', '请求头名称', 'ヘッダー名'],
  connectionSecret: ['Connection secret', '连接密钥', '接続シークレット'],
  createOAuthConnection: ['Create OAuth connection', '创建 OAuth 连接', 'OAuth 接続を作成'],
  serverVersion: ['Server version', '服务版本', 'サーバーバージョン'],
  noApprovedVersions: ['No approved version is available', '暂无已批准版本', '承認済みバージョンはありません'],
  qualificationRequired: ['New and reconfigured connections remain unavailable until remote initialization and bounded Tool discovery succeed.', '新建或重新配置的连接必须完成远程初始化与受限 Tool 发现后才可使用。', '新規または再設定した接続は、リモート初期化と制限付き Tool 検出が成功するまで利用できません。'],
  qualifyConnection: ['Validate connection', '验证连接', '接続を検証'],
  qualificationEvidence: ['Validation evidence', '验证证据', '検証証跡'],
  connectionStatus: ['Connection state', '连接状态', '接続状態'],
  protocolVersion: ['Protocol', '协议版本', 'プロトコル'],
  serverIdentity: ['Server identity', '服务身份', 'サーバー ID'],
  toolCount: ['Discovered Tools', '发现的 Tool', '検出された Tool'],
  qualifiedAt: ['Validated at', '验证时间', '検証時刻'],
  healthHistory: ['Health observations', '健康观察记录', 'ヘルス観測履歴'],
  neverQualified: ['No validation observation yet.', '尚无连接验证记录。', '検証履歴はまだありません。'],
  conversationTracing: ['Conversation tracing.', '会话调用追踪。', '会話トレーシング。'],
  conversationTracingHint: ['Read every AgentRun as evidence inside its owning Chat or Project conversation.', '以 Chat 或 Project 会话为基本单位，读取其中每次 AgentRun 的完整证据。', 'Chat または Project 会話を単位に、各 AgentRun の証跡を確認します。'],
  traceLoadFailed: ['Unable to load conversation traces', '无法加载会话调用追踪', '会話トレースを読み込めません'],
  traceDetailFailed: ['Unable to load trace detail', '无法加载 Trace 详情', 'トレース詳細を読み込めません'],
  conversations: ['Conversations', '会话', '会話'],
  successfulRuns: ['Successful runs', '成功运行', '成功した実行'],
  errorRuns: ['Error runs', '错误运行', 'エラー実行'],
  noConversationTraces: ['No conversations match this view.', '当前视图没有会话记录。', 'この表示に一致する会話はありません。'],
  agent: ['Agent', 'Agent', 'エージェント'],
  duration: ['Duration', '耗时', '所要時間'],
  toolCalls: ['Tool calls', '工具调用', 'ツール呼出し'],
  spanWaterfall: ['Span waterfall', 'Span 瀑布图', 'Span ウォーターフォール'],
  loadingTrace: ['Loading trace evidence…', '正在加载 Trace 证据…', 'トレース証跡を読み込み中…'],
  selectConversationTrace: ['Select a conversation run.', '选择一个会话运行。', '会話の実行を選択してください。'],
  conversationRuns: ['Conversation runs', '会话运行', '会話の実行'],
  evidence: ['Evidence', '运行证据', '証跡'],
  noSettledCost: ['No settled cost evidence', '暂无已结算费用证据', '確定済みコスト証跡なし'],
  estimated: ['Estimated', '估算', '推定'],
  organizationControl: ['Organization control.', '组织控制中心。', '組織コントロール。'],
  organizationControlHint: ['Manage active context and membership boundaries. Policy switches appear only when a durable backend contract exists.', '管理当前组织上下文与成员边界；只有存在耐久后端契约的策略才会开放设置。', 'アクティブな組織コンテキストとメンバー境界を管理します。永続バックエンド契約があるポリシーのみ設定できます。'],
  organizationSettingsLoadFailed: ['Unable to load organization settings', '无法加载组织设置', '組織設定を読み込めません'],
  organizationCreateFailed: ['Unable to create organization', '无法创建组织', '組織を作成できません'],
  newOrganization: ['New organization', '新建组织', '新しい組織'],
  currentOrganization: ['Current organization', '当前组织', '現在の組織'],
  yourRole: ['Your role', '你的角色', 'あなたのロール'],
  members: ['Members', '成员', 'メンバー'],
  created: ['Created', '创建时间', '作成日'],
  organizationContext: ['Organization context', '组织上下文', '組織コンテキスト'],
  active: ['Active', '当前', 'アクティブ'],
  activate: ['Activate', '切换', '切替'],
  accessBoundary: ['Access boundary', '成员边界', 'アクセス境界'],
  agentSharingPolicy: ['Agent sharing policy', 'Agent 共享策略', 'エージェント共有ポリシー'],
  organizationAgentSharing: ['Share organization Agents', '允许共享组织 Agent', '組織エージェントを共有'],
  organizationAgentSharingHint: ['Visible to members of this organization', '允许当前组织成员使用', 'この組織のメンバーへ公開'],
  laterIteration: ['Later iteration', '后续迭代', '今後の更新'],
  unavailable: ['Unavailable', '暂不可用', '利用不可'],
  agentSharingContractMissing: ['The backend currently exposes owner-scoped Agent definitions only. This switch stays disabled until an organization-sharing policy is authoritative.', '当前后端仅公开用户 Owner 范围的 Agent 定义；在组织共享策略成为权威契约前，此开关保持禁用。', '現在のバックエンドは所有者スコープのエージェント定義のみ公開します。組織共有ポリシーが権威契約になるまで無効です。'],
  credentialsAndKeys: ['Credentials and keys', '凭证与密钥', '認証情報とキー'],
  laterIterationUpdate: ['Available in a later iteration.', '后续迭代更新。', '今後のイテレーションで提供します。'],
  credentialPlaceholderHint: ['Provider and MCP secrets remain backend-managed. A dedicated credential vault UI is intentionally not exposed in this release.', 'Provider 与 MCP 密钥继续由后端管理；本版本暂不开放独立凭证保险库界面。', 'Provider と MCP のシークレットはバックエンド管理です。このリリースでは専用 Vault UI を公開しません。'],
  changePassword: ['Change password', '修改密码', 'パスワードを変更'],
  currentPassword: ['Current password', '当前密码', '現在のパスワード'],
  newPassword: ['New password', '新密码', '新しいパスワード'],
  confirmNewPassword: ['Confirm new password', '确认新密码', '新しいパスワードを確認'],
  passwordConfirmationMismatch: ['The new passwords do not match.', '两次输入的新密码不一致。', '新しいパスワードが一致しません。'],
  passwordChangeFailed: ['Unable to change the password', '无法修改密码', 'パスワードを変更できません'],
  passwordChanged: ['Password updated. Existing refresh sessions were revoked by the backend.', '密码已更新，后端已撤销现有刷新会话。', 'パスワードを更新し、既存の更新セッションをバックエンドが取り消しました。'],
  organizationName: ['Organization name', '组织名称', '組織名'],
  createAndSwitch: ['Create and switch', '创建并切换', '作成して切替'],
  organizationMemberSaveFailed: ['Unable to update the Organization member', '无法更新组织成员', '組織メンバーを更新できません'],
  organizationActionFailed: ['Unable to complete the Organization action', '无法完成组织操作', '組織操作を完了できません'],
  organizationInvitations: ['Organization invitations', '组织邀请', '組織招待'],
  organizationInvitationCreateFailed: ['Unable to create the invitation', '无法创建邀请', '招待を作成できません'],
  organizationInvitationAcceptFailed: ['Unable to accept the invitation', '无法接受邀请', '招待を承認できません'],
  organizationManagerRequired: ['Organization OWNER or ADMIN access is required.', '需要组织 OWNER 或 ADMIN 权限。', '組織の OWNER または ADMIN 権限が必要です。'],
  organizationRole: ['Organization role', '组织角色', '組織ロール'],
  memberUserId: ['Registered user ID', '已注册用户 ID', '登録済みユーザー ID'],
  addMember: ['Add / reactivate member', '添加或重新激活成员', 'メンバーを追加・再有効化'],
  transferOwner: ['Transfer owner', '转移所有权', '所有権を移譲'],
  transferOrganizationOwnership: ['Transfer Organization ownership?', '确认转移组织所有权？', '組織の所有権を移譲しますか？'],
  removeOrganizationMember: ['Remove Organization member?', '确认移除组织成员？', '組織メンバーを削除しますか？'],
  changeOrganizationRole: ['Change Organization role?', '确认修改组织角色？', '組織ロールを変更しますか？'],
  leaveOrganization: ['Leave Organization?', '确认退出组织？', '組織から退出しますか？'],
  revokeOrganizationInvitation: ['Revoke invitation?', '确认撤销邀请？', '招待を取り消しますか？'],
  organizationActionWarning: ['The backend will re-authorize this action and return the authoritative result.', '后端会重新鉴权并返回权威结果。', 'バックエンドが再認可し、権威ある結果を返します。'],
  acceptInvitation: ['Accept an invitation', '接受组织邀请', '招待を承認'],
  invitationToken: ['Invitation token', '邀请令牌', '招待トークン'],
  accept: ['Accept', '接受', '承認'],
  leave: ['Leave', '退出', '退出'],
  remove: ['Remove', '移除', '削除'],
  invitationLifetime: ['Lifetime (hours)', '有效期（小时）', '有効期間（時間）'],
  createInvitation: ['Create invitation', '创建邀请', '招待を作成'],
  copyInvitationTokenNow: ['Copy this invitation token now', '请立即复制邀请令牌', '招待トークンを今すぐコピー'],
  invitationTokenOneTime: ['This token is returned once and is not stored by the browser.', '令牌仅返回一次，浏览器不会持久化保存。', 'トークンは一度だけ返され、ブラウザには保存されません。'],
  noOrganizationInvitations: ['No invitations recorded.', '暂无组织邀请。', '組織招待はありません。'],
  dismiss: ['Dismiss', '关闭', '閉じる'],
}

export function text(language: Language, key: string): string {
  return messages[key]?.[languageOrder.indexOf(language)] ?? key
}
