package com.spaceagent.platform.inference.application;

import com.spaceagent.platform.inference.api.InferenceBudgetApplicationApi;import com.spaceagent.platform.inference.domain.*;import com.spaceagent.shared.exception.BusinessException;import com.spaceagent.shared.id.IdGenerator;import com.spaceagent.shared.time.TimeProvider;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;
@Service public class InferenceBudgetApplicationService implements InferenceBudgetApplicationApi{
 private final InferenceBudgetRepository repo;private final IdGenerator ids;private final TimeProvider time;public InferenceBudgetApplicationService(InferenceBudgetRepository r,IdGenerator i,TimeProvider t){repo=r;ids=i;time=t;}
 public PolicyView configure(ConfigurePolicyCommand c){if(c.monthlyRequestLimit()<0||c.monthlyTokenLimit()<0||c.monthlyCostLimitMicros()<0)throw new BusinessException("Inference budget is invalid",HttpStatus.BAD_REQUEST,"INFERENCE_BUDGET_INVALID");InferenceBudgetPolicy old=repo.findPolicy(c.tenantId()).orElse(null),saved=repo.savePolicy(new InferenceBudgetPolicy(c.tenantId(),c.enabled(),c.monthlyRequestLimit(),c.monthlyTokenLimit(),c.monthlyCostLimitMicros(),old==null?1:old.revision()+1,c.userId(),old==null?time.now():old.createdAt(),time.now()));return view(saved);}
 public PolicyView policy(String t){InferenceBudgetPolicy p=repo.findPolicy(t).orElse(new InferenceBudgetPolicy(t,false,0,0,0,0,"system",time.now(),time.now()));return view(p);}public UsageView usage(String t){var v=repo.usage(t);return new UsageView(v.consumedRequests(),v.reservedRequests(),v.consumedTokens(),v.reservedTokens(),v.consumedCostMicros(),v.reservedCostMicros());}
 public ReservationView reserve(ReserveCommand c){long tokens=Math.addExact(c.estimatedInputTokens(),c.maxOutputTokens());Long cost=c.priceId()==null?null:Math.addExact(ceil(c.estimatedInputTokens(),c.inputRate()),ceil(c.maxOutputTokens(),c.outputRate()));try{var d=repo.reserve(new InferenceBudgetRepository.ReserveRequest(ids.nextId(),c.tenantId(),c.agentRunId(),c.logicalCallId(),c.providerId(),c.modelId(),c.priceId(),c.inputRate(),c.outputRate(),tokens,cost));return new ReservationView(d.reservation().id(),d.reservation().status(),d.created(),d.reservation().reservedCostMicros());}catch(InferenceBudgetLimitException e){throw new BusinessException("Inference budget limit exceeded",HttpStatus.TOO_MANY_REQUESTS,e.code());}}
 public void settle(String id,long in,long out){repo.settle(id,in,out);}public void release(String id){repo.release(id);}public void markUnknown(String id){repo.markUnknown(id);}private static long ceil(long t,Long r){if(r==null)throw new InferenceBudgetLimitException("INFERENCE_PRICE_REQUIRED");return Math.addExact(Math.multiplyExact(t,r),999999)/1000000;}private static PolicyView view(InferenceBudgetPolicy p){return new PolicyView(p.tenantId(),p.enabled(),p.monthlyRequestLimit(),p.monthlyTokenLimit(),p.monthlyCostLimitMicros(),p.revision(),p.updatedAt());}
}
