package com.spaceagent.platform.project.infrastructure.persistence;
import com.spaceagent.platform.project.domain.*;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;import java.sql.*;import java.time.Instant;import java.util.*;
@Repository @ConditionalOnProperty(prefix="platform",name="persistence",havingValue="postgres")
public class PostgresWorkspaceRepository implements WorkspaceRepository{
 private static final String C="id,tenant_id,project_id,project_directory_id,task_id,source_repository_id,bridge_id,isolation_key,mode,worktree_key,base_ref,branch_name,worktree_ref,head_commit,writable,state,failure_reason,revision,created_by,created_at,updated_at";private final JdbcTemplate j;public PostgresWorkspaceRepository(JdbcTemplate j){this.j=j;}
 public void save(Workspace v){j.update("INSERT INTO platform_workspaces(id,tenant_id,project_id,project_directory_id,task_id,source_repository_id,bridge_id,isolation_key,mode,worktree_key,base_ref,branch_name,worktree_ref,head_commit,writable,state,failure_reason,revision,created_by,created_at,updated_at) VALUES(CAST(? AS UUID),?,CAST(? AS UUID),CAST(? AS UUID),CAST(? AS UUID),CAST(? AS UUID),CAST(? AS UUID),?,?,CAST(? AS UUID),?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET worktree_ref=EXCLUDED.worktree_ref,head_commit=EXCLUDED.head_commit,state=EXCLUDED.state,failure_reason=EXCLUDED.failure_reason,revision=EXCLUDED.revision,updated_at=EXCLUDED.updated_at",v.id(),v.tenantId(),v.projectId(),v.projectDirectoryId(),v.taskId(),v.sourceRepositoryId(),v.bridgeId(),v.isolationKey(),v.mode().name(),v.worktreeKey(),v.baseRef(),v.branchName(),v.worktreeRef(),v.headCommit(),v.writable(),v.state().name(),v.failureReason(),v.revision(),v.createdBy(),Timestamp.from(v.createdAt()),Timestamp.from(v.updatedAt()));}
 public Optional<Workspace> findById(String id){return j.query("SELECT "+C+" FROM platform_workspaces WHERE id=CAST(? AS UUID)",this::map,id).stream().findFirst();}public List<Workspace> findByProjectId(String p){return j.query("SELECT "+C+" FROM platform_workspaces WHERE project_id=CAST(? AS UUID) ORDER BY created_at,id",this::map,p);}public boolean hasActiveWritable(String t,String s,String isolationKey){Boolean b=j.queryForObject("SELECT EXISTS(SELECT 1 FROM platform_workspaces WHERE task_id=CAST(? AS UUID) AND source_repository_id=CAST(? AS UUID) AND isolation_key=? AND writable AND state NOT IN('ARCHIVED','CLEANED_UP','FAILED'))",Boolean.class,t,s,isolationKey);return Boolean.TRUE.equals(b);}
 public List<Workspace> findStaleProvisioning(Instant before,int limit){return j.query("SELECT "+C+" FROM platform_workspaces WHERE state='PROVISIONING' AND updated_at<=? ORDER BY updated_at,id LIMIT ?",this::map,Timestamp.from(before),limit);}
 public boolean failProvisioning(String id,long revision,String reason,Instant at){return j.update("UPDATE platform_workspaces SET state='FAILED',failure_reason=?,revision=revision+1,updated_at=? WHERE id=CAST(? AS UUID) AND state='PROVISIONING' AND revision=?",reason,Timestamp.from(at),id,revision)==1;}
 private Workspace map(ResultSet r,int n)throws SQLException{return new Workspace(r.getString("id"),r.getString("tenant_id"),r.getString("project_id"),r.getString("project_directory_id"),r.getString("task_id"),r.getString("source_repository_id"),r.getString("bridge_id"),r.getString("isolation_key"),WorkspaceMode.valueOf(r.getString("mode")),r.getString("worktree_key"),r.getString("base_ref"),r.getString("branch_name"),r.getString("worktree_ref"),r.getString("head_commit"),r.getBoolean("writable"),WorkspaceState.valueOf(r.getString("state")),r.getString("failure_reason"),r.getLong("revision"),r.getString("created_by"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());}
}
