(()=>{
const q=s=>document.querySelector(s), all=s=>[...document.querySelectorAll(s)], esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes=[['概览','overview','grid'],['对话','chat','chat'],['项目','project','folder'],['Agent','agents','spark'],['自动化','automation','clock'],['知识库','knowledge','files'],['记忆','memory','spark'],['MCP 市场','mcp','grid'],['调用追踪','tracing','branch'],['模型资源','models','repo'],['组织设置','organization','settings']];
q('#dialog').setAttribute('aria-labelledby','dialogTitle');const sidebar=q('.sidebar');const wrap=document.createElement('div');wrap.className='sidebar-scroll';sidebar.insertBefore(wrap,q('.nav'));wrap.append(q('.nav'),q('#projectDetails'));const nav=q('.nav');nav.innerHTML=routes.map(([name,id,icon],i)=>`${i===5?'<div class="nav-caption">资源与管理</div>':''}<button data-route="${id}" data-page="${name}" ${id==='project'?'aria-expanded="false" aria-controls="projectDetails"':''}><i data-icon="${icon}"></i>${name}</button>`).join('');
const histories=document.createElement('div');histories.className='chat-history';histories.hidden=true;nav.querySelector('[data-route="project"]').after(q('#projectDetails'));nav.querySelector('[data-route="chat"]').after(histories);q('#more').remove();const backdrop=document.createElement('button');backdrop.className='mobile-backdrop';backdrop.setAttribute('aria-label','关闭导航');q('#app').prepend(backdrop);q('#navToggle').classList.add('left-toggle');q('#navToggle').setAttribute('aria-controls','primarySidebar');sidebar.id='primarySidebar';
const projectLayout=q('.layout');projectLayout.id='projectLayout';const view=document.createElement('section');view.className='page-view';view.hidden=true;q('#main').append(view);
const chatLayout=document.createElement('div');chatLayout.className='layout';chatLayout.id='chatLayout';chatLayout.hidden=true;chatLayout.innerHTML=`<section class="conversation" aria-label="对话"><div class="scroll chat-log"><div class="content" id="chatContent"></div></div><div class="composer-area"><form class="composer" id="chatComposer"><textarea id="chatPrompt" aria-label="对话消息" placeholder="有什么想一起完成的？" maxlength="4000"></textarea><div class="composer-controls"><button class="icon-button" type="button" id="chatAttach" aria-label="对话添加附件"><i data-icon="plus"></i></button><input id="chatFile" type="file" hidden><select id="chatAgent" aria-label="选择对话 Agent"><option>通用助手</option><option>写作助手</option><option>代码助手</option></select><select aria-label="选择对话模型"><option>千问</option><option>演示模型</option></select><span class="branch">个人空间</span><button class="send" aria-label="发送对话"><i data-icon="arrow"></i></button></div><div id="chatAttachment" class="form-help"></div></form><p class="hint">Enter 发送 · Shift + Enter 换行 · 原型演示</p></div></section><aside class="inspector" aria-label="对话详情"><header>对话详情<span class="tag">演示</span></header><div class="repo-tile"><div class="repo-icon"><i data-icon="spark"></i></div><b id="chatAgentName">通用助手</b><small>帮助你思考、写作与整理信息</small></div><label class="field-label">使用的知识库</label><select class="search-input" aria-label="对话知识库"><option>不使用知识库</option><option>产品文档</option><option>工程规范</option></select><div class="setting-row"><span>使用个人记忆</span><button class="toggle" role="switch" aria-label="使用个人记忆" aria-checked="true"></button></div><hr><div class="files-head"><b>本次对话</b></div><div class="meta-row"><span>消息数</span><b id="chatCount">0</b></div><div class="meta-row"><span>模型</span><b>千问</b></div><details><summary>执行记录</summary><p>暂无真实执行。原型中的回复仅用于展示排版与交互。</p></details></aside>`;q('#main').append(chatLayout);
let workflow=null;let route='overview';let leftClosed=false;const rightOpen={chat:true,project:true};const projectNew=q('#newChat').onclick;let chats=[{id:1,title:'新对话',messages:[],draft:''},{id:2,title:'整理本周工作重点',messages:[['user','帮我整理本周的工作重点。'],['assistant','可以按目标、进展和待解决的问题来整理。先列出最重要的三件事，再为每件事补充下一步行动。']],draft:''}];let chatId=1;let agents=[{name:'通用助手',desc:'日常问答、资料整理和想法讨论。',model:'千问',type:'个人',icon:'✧'},{name:'代码助手',desc:'阅读代码、分析问题，协助完成项目任务。',model:'千问',type:'组织',icon:'⌘'},{name:'写作助手',desc:'整理结构、改写文字，让表达清晰自然。',model:'千问',type:'个人',icon:'✎'}];let tasks=[{name:'每日项目摘要',desc:'整理项目进展与待办',schedule:'每天 09:00',enabled:true},{name:'每周知识整理',desc:'汇总本周新增资料',schedule:'每周五 18:00',enabled:true},{name:'依赖检查',desc:'整理仓库依赖更新',schedule:'每周一 10:00',enabled:false}];let docs=[{name:'产品说明.pdf',type:'产品文档',status:'已就绪',size:'1.2 MB',date:'今天 10:24'},{name:'接口规范.md',type:'工程规范',status:'已就绪',size:'48 KB',date:'昨天 16:08'},{name:'团队协作指南.pdf',type:'产品文档',status:'已就绪',size:'860 KB',date:'09-10 09:30'}];let memories=[{title:'沟通习惯',body:'优先使用中文，说明问题时简明直接。',scope:'个人'},{title:'项目约定',body:'SpaceAgent 使用 Java 作为业务后端，React 负责交互界面。',scope:'项目'},{title:'开发偏好',body:'先确认实现范围，再进行局部修改与验证。',scope:'个人'}];let tools=[{name:'GitHub',desc:'查阅仓库、Issue 和 Pull Request。',cat:'开发',icon:'⌘',installed:true},{name:'文档检索',desc:'从已连接的文档中查找相关信息。',cat:'效率',icon:'▤',installed:true},{name:'网页读取',desc:'读取网页内容，辅助资料整理。',cat:'检索',icon:'◎',installed:false},{name:'文件系统',desc:'浏览授权目录中的项目文件。',cat:'开发',icon:'▱',installed:false},{name:'搜索',desc:'检索公开网页，获取相关资料。',cat:'检索',icon:'⌕',installed:false},{name:'日历',desc:'查看日程，整理时间安排。',cat:'效率',icon:'▦',installed:false}];let providers=[{name:'千问',model:'qwen-plus',type:'对话',enabled:true},{name:'OpenAI',model:'演示模型',type:'对话',enabled:false},{name:'Embedding',model:'text-embedding-v3',type:'向量',enabled:true}];let members=[{name:'Example User',role:'所有者',email:'当前账户'},{name:'Lin',role:'成员',email:'演示成员'}];let organization='个人空间';let tabState='基本信息';let query='',filter='全部';
const tag=(t,c='')=>`<span class="tag ${c}">${esc(t)}</span>`;const btn=(t,a,c='')=>`<button class="btn ${c}" data-action="${a}">${t}</button>`;const heading=(title,sub,action='')=>`<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div><div class="page-actions">${action}</div></div>`;const card=(content)=>`<section class="soft-card">${content}</section>`;const empty=()=>'<div class="empty-state">没有找到匹配的内容，换个关键词试试。</div>';const search=(placeholder,filters=['全部'])=>`<div class="searchbar"><input class="search-input" id="pageSearch" aria-label="搜索当前页面" placeholder="${placeholder}" value="${esc(query)}"><div class="filter">${filters.map(t=>`<button data-filter="${t}" class="${filter===t?'active':''}">${t}</button>`).join('')}</div></div>`;const stat=(name,value,note)=>card(`<div class="stat-label">${name}</div><div class="stat-value">${value}</div><div class="stat-note">${note}</div>`);const match=(text,category)=>text.toLowerCase().includes(query.toLowerCase())&&(filter==='全部'||category===filter);const toggle=(label,value,action)=>`<button role="switch" class="toggle" aria-label="${esc(label)}" aria-checked="${value}" data-action="${action}"></button>`;
function showDialog(title,html){modal(title).innerHTML=html}function detail(title,html){showDialog(title,`<div class="modal-detail">${html}</div>`)}function form(title,fields,save){showDialog(title,`<form class="form-stack" id="editForm">${fields.map(f=>`<label>${f.label}${f.options?`<select name="${f.key}">${f.options.map(v=>`<option ${v===f.value?'selected':''}>${esc(v)}</option>`).join('')}</select>`:f.multiline?`<textarea name="${f.key}" required maxlength="2000">${esc(f.value||'')}</textarea>`:`<input name="${f.key}" value="${esc(f.value||'')}" required maxlength="120" autocomplete="off">`}</label>`).join('')}<p class="form-help">仅保存于本次原型预览，刷新后恢复演示数据。</p><div class="form-actions"><button type="button" class="btn" id="cancelEdit">取消</button><button class="btn accent">保存</button></div></form>`);q('#cancelEdit').onclick=()=>q('#dialog').close();q('#editForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(Object.values(data).some(v=>!v.trim()))return;save(data);q('#dialog').close();render();toast('已保存演示内容')};}

let tokenRange='今日', tokenMotion=true;
const tokenUsage={
  '今日':{input:92400,output:36000,cost:'1.86'},
  '本周':{input:612400,output:230200,cost:'12.48'},
  '本月':{input:2380200,output:888200,cost:'48.72'}
};
function tokenCard(){
  const d=tokenUsage[tokenRange],total=d.input+d.output,share=d.input/total*100;
  const compact=total>=1e6?(total/1e6).toFixed(2)+'M':(total/1000).toFixed(1)+'K';
  return `<section class="soft-card token-card ${tokenMotion?'':'motion-stopped'}" aria-label="Token 消费统计">
    <div class="token-head"><h2>Token 消费</h2><select id="tokenRange" aria-label="消费统计周期">${Object.keys(tokenUsage).map(t=>`<option ${t===tokenRange?'selected':''}>${t}</option>`).join('')}</select></div>
    <div class="token-chart" role="img" aria-label="${tokenRange}消费 ${total.toLocaleString('en-US')} Token，输入 ${d.input.toLocaleString('en-US')}，输出 ${d.output.toLocaleString('en-US')}，费用示例人民币 ${d.cost} 元">
      <svg viewBox="0 0 240 240" aria-hidden="true"><circle class="token-track" cx="120" cy="120" r="96"/><g transform="rotate(-90 120 120)"><circle class="token-segment token-input" cx="120" cy="120" r="96" pathLength="100" style="--segment:${share-1.2};stroke-dashoffset:-.6"/><circle class="token-segment token-output" cx="120" cy="120" r="96" pathLength="100" style="--segment:${100-share-1.2};stroke-dashoffset:-${share+.6}"/></g></svg>
      <div class="token-marquee" aria-hidden="true"></div><div class="token-center"><span>${tokenRange}已消费</span><strong>${compact}</strong><small>Tokens</small></div>
    </div>
    <div class="token-legend"><div><span><i class="input-dot"></i>输入</span><b>${d.input.toLocaleString('en-US')}</b></div><div><span><i class="output-dot"></i>输出</span><b>${d.output.toLocaleString('en-US')}</b></div></div>
    <div class="token-billing"><div><span>${tokenRange}费用</span><strong><small>¥</small> ${d.cost}</strong></div><button class="icon-button" id="tokenMotion" aria-label="${tokenMotion?'暂停圆环动画':'播放圆环动画'}" aria-pressed="${!tokenMotion}" title="${tokenMotion?'暂停圆环动画':'播放圆环动画'}">${tokenMotion?'Ⅱ':'▷'}</button></div>
    <p class="token-footnote">示例消费与费用 · 未连接真实账单</p>
  </section>`;
}

function render(){
let html='';if(route==='overview')html=heading('早上好，Example User','从一段对话，开始今天的工作。',btn('＋ 新对话','go:chat','accent'))+`<div class="stats">${stat('项目','2','最近使用：今天')}${stat('对话','8','本周新增 3 段')}${stat('已启用 Agent',agents.length,'随时开始协作')}${stat('自动化',tasks.filter(t=>t.enabled).length,'正在按计划运行 · 演示')}</div><div class="overview-focus">${card(`<div class="section-head"><h2>继续上次的工作</h2><button data-action="go:project">查看项目 →</button></div><div class="row"><div class="card-icon">▱</div><div class="grow"><b>消息可靠性优化</b><small>schat · new-web</small></div><button class="btn" data-action="go:project">继续</button></div><div class="row"><div class="card-icon">✧</div><div class="grow"><b>整理本周工作重点</b><small>通用助手 · 昨天</small></div><button class="btn" data-action="resume-chat">打开</button></div>`)}${tokenCard()}</div>`;
if(route==='agents')html=heading('Agent','选择一个助手，或者配置适合你的工作方式。',btn('＋ 创建 Agent','agent:new','accent'))+search('搜索 Agent',['全部','个人','组织'])+`<div class="cards-grid">${agents.map((a,i)=>match(a.name+a.desc,a.type)?card(`<div class="card-head"><div class="card-icon">${a.icon}</div>${tag(a.type)}</div><h3>${esc(a.name)}</h3><p>${esc(a.desc)}</p><div class="tags">${tag(a.model,'green')}${tag('可用')}</div><div class="card-foot"><button data-action="agent:edit:${i}">配置</button><button data-action="agent:chat:${i}">开始对话 ↗</button></div>`):'').join('')||empty()}</div>`;
if(route==='automation')html=heading('自动化','把重复的工作交给计划，留出时间处理重要的事。',btn('＋ 新建自动化','task:new','accent'))+search('搜索自动化',['全部','已启用','已暂停'])+`<div class="table-wrap"><table><thead><tr><th>名称</th><th>运行时间</th><th>最近结果</th><th>启用</th><th></th></tr></thead><tbody>${tasks.map((t,i)=>match(t.name,t.enabled?'已启用':'已暂停')?`<tr><td>${esc(t.name)}<small>${esc(t.desc)}</small></td><td>${esc(t.schedule)}</td><td>${tag(t.enabled?'已完成':'已暂停',t.enabled?'green':'')}</td><td>${toggle(t.name,t.enabled,'task:toggle:'+i)}</td><td><button data-action="task:edit:${i}">编辑</button><button data-action="task:history:${i}">记录</button></td></tr>`:'').join('')}</tbody></table></div>`;
if(route==='knowledge')html=heading('知识库','把常用资料放在一起，让回答有所依据。',btn('＋ 添加文档','doc:new','accent'))+`<div class="stats">${stat('文档',docs.length,'本地演示列表')}${stat('知识库','2','产品文档 · 工程规范')}${stat('已就绪',docs.length,'可用于对话演示')}${stat('最近更新','今天','10:24')}</div>`+search('搜索文档',['全部','产品文档','工程规范'])+`<div class="table-wrap"><table><thead><tr><th>文档</th><th>知识库</th><th>状态</th><th>大小</th><th>更新时间</th><th></th></tr></thead><tbody>${docs.map((d,i)=>match(d.name,d.type)?`<tr><td>▤ &nbsp;${esc(d.name)}</td><td>${d.type}</td><td>${tag(d.status,'green')}</td><td>${d.size}</td><td>${d.date}</td><td><button data-action="doc:view:${i}">预览</button></td></tr>`:'').join('')}</tbody></table></div>`;
if(route==='memory')html=heading('记忆','保留有用的背景与偏好，让协作更连贯。',btn('＋ 添加记忆','memory:new','accent'))+search('搜索记忆',['全部','个人','项目'])+`<div class="cards-grid">${memories.map((m,i)=>match(m.title+m.body,m.scope)?card(`<div class="card-head">${tag(m.scope)}<button class="icon-button" aria-label="编辑${esc(m.title)}" data-action="memory:edit:${i}">✎</button></div><h3>${esc(m.title)}</h3><p>${esc(m.body)}</p><div class="card-foot"><span>用户添加 · 演示</span><button data-action="memory:remove:${i}">移除</button></div>`):'').join('')||empty()}</div>`;
if(route==='mcp')html=heading('MCP 市场','连接工具，为助手提供完成工作所需的能力。')+search('搜索工具',['全部','开发','效率','检索','已连接'])+`<div class="cards-grid">${tools.map((t,i)=>((filter==='已连接'?t.installed&&t.name.toLowerCase().includes(query.toLowerCase()):match(t.name+t.desc,t.cat)))?card(`<div class="card-head"><div class="card-icon">${t.icon}</div>${tag(t.installed?'已连接':t.cat,t.installed?'green':'')}</div><h3>${t.name}</h3><p>${t.desc}</p><div class="card-foot"><button data-action="tool:detail:${i}">查看详情</button><button data-action="tool:connect:${i}">${t.installed?'管理连接':'连接 →'}</button></div>`):'').join('')||empty()}</div>`;
if(route==='tracing'){const traces=[['消息可靠性优化','代码助手','已完成','12.4 秒','今天 10:32'],['整理项目摘要','通用助手','已完成','8.2 秒','今天 09:00'],['资料检索','通用助手','失败','3.1 秒','昨天 17:20'],['梳理项目结构','代码助手','已完成','18.6 秒','昨天 14:05']];html=heading('调用追踪','查看每次执行的过程与结果。')+`<div class="stats">${stat('执行次数','24','最近 7 天 · 演示')}${stat('成功率','95.8%','23 次成功')}${stat('平均耗时','10.6 秒','最近 7 天')}${stat('待处理','1','一次工具连接失败')}</div>`+search('搜索任务',['全部','已完成','失败'])+`<div class="table-wrap"><table><thead><tr><th>任务</th><th>Agent</th><th>状态</th><th>耗时</th><th>时间</th><th></th></tr></thead><tbody>${traces.map((t,i)=>match(t[0],t[2])?`<tr><td>${t[0]}</td><td>${t[1]}</td><td>${tag(t[2],t[2]==='失败'?'amber':'green')}</td><td>${t[3]}</td><td>${t[4]}</td><td><button data-action="trace:${i}">查看过程</button></td></tr>`:'').join('')}</tbody></table></div>`}
if(route==='models')html=heading('模型资源','统一管理模型连接与使用方式。',btn('＋ 添加连接','provider:new','accent'))+`<div class="cards-grid">${providers.map((p,i)=>card(`<div class="card-head"><div class="card-icon">◈</div>${tag(p.enabled?'已启用':'未启用',p.enabled?'green':'')}</div><h3>${esc(p.name)}</h3><p>${esc(p.model)}</p>${tag(p.type)}<div class="card-foot"><button data-action="provider:edit:${i}">配置</button>${toggle('启用'+p.name,p.enabled,'provider:toggle:'+i)}</div>`)).join('')}</div><div style="height:25px"></div>${card(`<h2>默认模型</h2><div class="setting-row"><div>对话模型<p>新建对话时默认使用的模型。</p></div><select class="search-input" aria-label="默认对话模型"><option>千问 / qwen-plus</option><option>OpenAI / 演示模型</option></select></div><div class="setting-row"><div>向量模型<p>用于知识库检索。</p></div><span class="tag">text-embedding-v3</span></div>`)}<p class="notice">原型不收集 API Key，不执行连接测试或模型调用。</p>`;
if(route==='organization'){html=heading('组织设置','管理空间信息、成员与个人偏好。')+`<div class="settings-tabs">${['基本信息','成员','偏好'].map(t=>`<button data-action="org:tab:${t}" class="${tabState===t?'active':''}">${t}</button>`).join('')}</div>`;if(tabState==='基本信息')html+=card(`<h2>空间信息</h2><div class="setting-row"><div>空间名称<p>${esc(organization)}</p></div>${btn('编辑','org:edit')}</div><div class="setting-row"><div>所有者<p>Example User</p></div>${tag('当前账户','green')}</div><div class="setting-row"><div>空间类型<p>个人工作空间</p></div>${tag('个人')}</div>`);if(tabState==='成员')html+=card(`<div class="section-head"><h2>空间成员</h2>${btn('＋ 邀请成员','org:invite')}</div>${members.map(m=>`<div class="row"><span class="avatar">${esc(m.name[0])}</span><div class="grow"><b>${esc(m.name)}</b><small>${esc(m.email)}</small></div>${tag(m.role)}</div>`).join('')}`);if(tabState==='偏好')html+=card(`<h2>界面偏好</h2><div class="setting-row"><div>深色主题<p>降低暗光环境中的亮度。</p></div>${toggle('深色主题',document.body.classList.contains('dark'),'org:theme')}</div><div class="setting-row"><div>界面语言<p>这版原型使用中文。</p></div>${tag('简体中文')}</div><div class="setting-row"><div>减少动画<p>关闭流动与折叠过渡，立即展示结果。</p></div>${toggle('减少动画',document.body.classList.contains('reduce-motion'),'org:motion')}</div>`)}
view.innerHTML=`<div class="page-inner">${html}<p class="notice">交互原型 · 列表为演示数据，项目与对话流程支持本标签页刷新恢复。</p></div>`;const tbody=view.querySelector('tbody');if(tbody&&!tbody.children.length)tbody.innerHTML='<tr><td colspan="6" class="empty-state">没有找到匹配的内容，换个关键词试试。</td></tr>';bindPage();workflow?.pageRender();}
function bindPage(){if(q('#tokenRange'))q('#tokenRange').onchange=e=>{tokenRange=e.target.value;render()};if(q('#tokenMotion'))q('#tokenMotion').onclick=()=>{tokenMotion=!tokenMotion;q('.token-card').classList.toggle('motion-stopped',!tokenMotion);q('#tokenMotion').textContent=tokenMotion?'Ⅱ':'▷';q('#tokenMotion').setAttribute('aria-label',tokenMotion?'暂停圆环动画':'播放圆环动画');q('#tokenMotion').title=tokenMotion?'暂停圆环动画':'播放圆环动画';q('#tokenMotion').setAttribute('aria-pressed',String(!tokenMotion))};if(q('#pageSearch'))q('#pageSearch').oninput=e=>{const pos=e.target.selectionStart;query=e.target.value;render();q('#pageSearch').focus();q('#pageSearch').setSelectionRange(pos,pos)};all('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});view.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));}
function act(action){if(workflow?.act(action))return;const [a,b,c]=action.split(':');const i=Number(c);if(a==='go')return navigate(b);if(a==='resume-chat'){chatId=2;return navigate('chat')}
if(a==='agent'){if(b==='chat'){navigate('chat');q('#chatAgent').value=['通用助手','代码助手','写作助手'].includes(agents[i].name)?agents[i].name:'通用助手';q('#chatAgentName').textContent=agents[i].name;return}const old=b==='edit'?agents[i]:null;form(old?'配置 Agent':'创建 Agent',[{key:'name',label:'名称',value:old?.name},{key:'desc',label:'用途',multiline:true,value:old?.desc},{key:'type',label:'可见范围',options:['个人','组织'],value:old?.type}],d=>{const value={...d,model:'千问',icon:'✧'};if(old)agents[i]=value;else agents.push(value)});}
if(a==='task'){if(b==='toggle'){tasks[i].enabled=!tasks[i].enabled;render();return}if(b==='history'){detail(tasks[i].name,`<p>${esc(tasks[i].schedule)} · 演示记录</p><div class="timeline"><div>执行完成<small>今天 09:00 · 用时 8.2 秒</small></div><div>生成工作摘要<small>已整理 3 项进展与 2 项待办</small></div></div>`);return}const t=b==='edit'?tasks[i]:null;form(t?'编辑自动化':'新建自动化',[{key:'name',label:'名称',value:t?.name},{key:'desc',label:'要完成的工作',multiline:true,value:t?.desc},{key:'schedule',label:'运行时间',options:['每天 09:00','每周五 18:00','每周一 10:00'],value:t?.schedule}],d=>{if(t)tasks[i]={...d,enabled:t.enabled};else tasks.push({...d,enabled:true})})}
if(a==='doc'){if(b==='view'){detail(docs[i].name,`<p>${docs[i].type} · ${docs[i].size}</p><h3>文档摘要</h3><p>这是一份演示文档，用于展示知识库中文档预览、内容摘要与引用的布局。</p><h3>主要内容</h3><p>1. 产品背景与使用方式<br>2. 核心功能与工作流程<br>3. 常见问题与约定</p>`);return}form('添加文档',[{key:'name',label:'文档名称（演示）',value:'新文档.md'},{key:'type',label:'知识库',options:['产品文档','工程规范']}],d=>docs.push({...d,status:'已就绪',size:'12 KB',date:'刚刚'}))}
if(a==='memory'){if(b==='remove'){const removed=memories.splice(i,1)[0];render();toast('已移除演示记忆：'+removed.title);return}const m=b==='edit'?memories[i]:null;form(m?'编辑记忆':'添加记忆',[{key:'title',label:'标题',value:m?.title},{key:'body',label:'记住什么',multiline:true,value:m?.body},{key:'scope',label:'范围',options:['个人','项目'],value:m?.scope}],d=>{if(m)memories[i]=d;else memories.push(d)})}
if(a==='tool'){const t=tools[i];detail(t.name,`<p>${t.desc}</p><h3>访问范围</h3><p>仅使用显式授权的资源。真实产品连接时会展示具体权限；本原型不会发起授权。</p><div class="tags">${tag(t.cat)}${tag(t.installed?'已连接':'未连接')}</div><div class="form-actions"><button class="btn accent" id="connectDemo">${t.installed?'断开演示连接':'添加演示连接'}</button></div>`);q('#connectDemo').onclick=()=>{t.installed=!t.installed;q('#dialog').close();render();toast(t.installed?'已添加演示连接':'已断开演示连接')}}
if(a==='trace')detail('执行过程',`<p>执行记录 #00${Number(b)+1} · 原型演示</p><div class="timeline"><div>接收任务<small>已绑定当前会话</small></div><div>准备上下文<small>加载 Agent 配置与相关资料</small></div><div>${b==='2'?'工具连接失败':'完成工具读取'}<small>${b==='2'?'连接超时，请检查连接状态':'读取相关内容'}</small></div><div>${b==='2'?'执行已停止':'生成回答'}<small>${b==='2'?'未继续模型调用':'回答已完成'}</small></div></div>`);
if(a==='provider'){if(b==='toggle'){providers[i].enabled=!providers[i].enabled;render();return}const p=b==='edit'?providers[i]:null;form(p?'配置模型连接':'添加模型连接',[{key:'name',label:'连接名称',value:p?.name},{key:'model',label:'模型名称',value:p?.model},{key:'type',label:'用途',options:['对话','向量'],value:p?.type}],d=>{if(p)providers[i]={...d,enabled:p.enabled};else providers.push({...d,enabled:false})})}
if(a==='org'){if(b==='tab'){tabState=c;render()}if(b==='edit')form('编辑空间',[{key:'name',label:'空间名称',value:organization}],d=>{organization=d.name;q('.workspace strong').textContent=d.name});if(b==='invite')form('添加演示成员',[{key:'name',label:'成员名称'},{key:'role',label:'角色',options:['成员','管理员']}],d=>members.push({...d,email:'演示成员 · 未发送邀请'}));if(b==='theme'){document.body.classList.toggle('dark');render()}if(b==='motion'){document.body.classList.toggle('reduce-motion');render()}}
}
function updatePanels(){const mobile=matchMedia('(max-width:700px)').matches;sidebar.inert=mobile?!q('#app').classList.contains('nav-open'):leftClosed;q('#navToggle').setAttribute('aria-expanded',String(!sidebar.inert));q('#navToggle').setAttribute('aria-label',sidebar.inert?'展开左侧导航':'收起左侧导航');q('#main').classList.toggle('focus-mode',!rightOpen[route]);q('#main').classList.toggle('panel-open',!!rightOpen[route]);q('#environment').setAttribute('aria-expanded',String(!!rightOpen[route]));q('#environment').setAttribute('aria-label',rightOpen[route]?'收起右侧详情':'展开右侧详情');const current=route==='chat'?chatLayout:projectLayout;current.querySelector('.inspector').inert=!rightOpen[route];}
function navigate(next,fromHistory=false){if(route==='chat')chats.find(c=>c.id===chatId).draft=q('#chatPrompt').value;route=routes.some(r=>r[1]===next)?next:'overview';query='';filter='全部';document.title='SpaceAgent · '+routes.find(r=>r[1]===route)[0];projectLayout.hidden=route!=='project';chatLayout.hidden=route!=='chat';view.hidden=['project','chat'].includes(route);setProjectDetails(route==='project');histories.hidden=route!=='chat';all('[data-route]').forEach(b=>{b.classList.toggle('selected',b.dataset.route===route);if(b.dataset.route===route)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});q('.breadcrumb').innerHTML=`<span>${routes.find(r=>r[1]===route)[0]}</span>${route==='project'?'<span>/</span><b>schat</b>':''}`;q('#environment').hidden=!['chat','project'].includes(route);q('#environment').innerHTML='<i data-icon="panel"></i>'+ (route==='chat'?'详情':'环境');drawIcons();q('#newChat').hidden=!['chat','project'].includes(route);q('#app').classList.remove('nav-open');updatePanels();if(route==='chat')renderChat();else if(route!=='project')render();workflow?.navigate(route);if(!fromHistory)location.hash=route;}
function renderChat(){const chat=chats.find(c=>c.id===chatId);q('#chatPrompt').value=chat.draft;q('#chatContent').innerHTML=chat.messages.length?`<div class="eyebrow">对话 · 今天</div><h1>${esc(chat.title)}</h1>${chat.messages.map(([role,text])=>role==='user'?`<div class="user-message">${esc(text)}</div>`:`<article><div class="assistant-head"><span class="mark"></span>SpaceAgent</div><div class="response"><p>${esc(text)}</p></div></article>`).join('')}`:`<div class="chat-hero"><span class="mark"></span><h1>有什么想一起完成的？</h1><p>一个问题、一份想法，或者一件还没开始的事。</p></div><div class="suggestions">${[['整理思路','把零散想法变成清晰的行动'],['分析代码','一起找到问题的关键'],['润色文字','让表达更自然、更准确'],['学习新知识','从一个问题开始深入理解']].map(([t,d])=>`<button data-suggest="${t}">${t}<small>${d}</small></button>`).join('')}</div>`;q('#chatCount').textContent=chat.messages.length;histories.innerHTML='<div class="chat-history-label">最近对话</div>'+chats.map(c=>`<button data-chat="${c.id}" class="${c.id===chatId?'active':''}">${esc(c.title)}</button>`).join('');all('[data-chat]').forEach(b=>b.onclick=()=>{chat.draft=q('#chatPrompt').value;chatId=Number(b.dataset.chat);renderChat()});all('[data-suggest]').forEach(b=>b.onclick=()=>{q('#chatPrompt').value='帮我'+b.dataset.suggest;q('#chatPrompt').focus()});workflow?.chatRender();}
q('#chatComposer').onsubmit=e=>{e.preventDefault();const text=q('#chatPrompt').value.trim();if(!text)return;if(workflow?.startChat(text))return;const c=chats.find(c=>c.id===chatId);if(!c.messages.length)c.title=text.slice(0,16);c.messages.push(['user',text],['assistant','可以，我们先明确目标，再拆成几个具体步骤。这是 HTML 原型中的演示回复，不会调用模型。你可以继续输入、切换对话，或收起左右面板体验专注布局。']);c.draft='';renderChat();q('.chat-log').scrollTo({top:q('.chat-log').scrollHeight,behavior:'smooth'})};q('#chatPrompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();q('#chatComposer').requestSubmit()}};q('#chatAttach').onclick=()=>q('#chatFile').click();q('#chatFile').onchange=()=>q('#chatAttachment').textContent=q('#chatFile').files[0]?.name||'';q('#chatAgent').onchange=()=>q('#chatAgentName').textContent=q('#chatAgent').value;chatLayout.querySelector('[role=switch]').onclick=e=>e.currentTarget.setAttribute('aria-checked',String(e.currentTarget.getAttribute('aria-checked')!=='true'));
all('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));q('#navToggle').onclick=()=>{if(matchMedia('(max-width:700px)').matches)q('#app').classList.toggle('nav-open');else{leftClosed=!leftClosed;q('#app').classList.toggle('left-closed',leftClosed)}updatePanels()};backdrop.onclick=()=>{q('#app').classList.remove('nav-open');updatePanels()};q('#environment').onclick=()=>{rightOpen[route]=!rightOpen[route];updatePanels()};q('#newChat').onclick=()=>{if(route==='project'){workflow?workflow.newConversation():projectNew();return}chats.find(c=>c.id===chatId).draft=q('#chatPrompt').value;chatId=Date.now();chats.unshift({id:chatId,title:'新对话',messages:[],draft:''});renderChat()};q('#settings').onclick=()=>navigate('organization');addEventListener('resize',updatePanels);addEventListener('hashchange',()=>{if(location.hash.slice(1)!==route)navigate(location.hash.slice(1),true)});addEventListener('keydown',e=>{if(e.key==='Escape'){q('#app').classList.remove('nav-open');if(matchMedia('(max-width:1150px)').matches)rightOpen[route]=false;updatePanels()}});drawIcons();if(matchMedia('(max-width:1150px)').matches){rightOpen.chat=false;rightOpen.project=false}workflow=window.installPrototypeWorkflows({esc,showDialog,toast,agents:()=>agents,chats:()=>chats,setChatId:id=>chatId=id,chat:()=>chats.find(c=>c.id===chatId),renderChat,render,route:()=>route});navigate(location.hash.slice(1)||'overview',true);
})();
