/* Prototype workflows only. No service, model, Git or OAuth requests are made. */
window.installPrototypeWorkflows = function(app) {
  const $=s=>document.querySelector(s), E=app.esc;
  const button=(label,action,kind='')=>`<button class="btn ${kind}" data-flow="${action}">${label}</button>`;
  const select=(name,values,value)=>`<select name="${name}">${values.map(v=>`<option ${v===value?'selected':''}>${E(v)}</option>`).join('')}</select>`;
  const seed=()=>({roots:[{id:'repo',name:'example-org/demo-repository',kind:'repo',branch:'new-web',ready:true,threads:[{id:'initial',title:'消息可靠性优化'},...['梳理项目结构','优化登录流程','补充单元测试','检查接口约定','整理开发文档'].map((title,i)=>({id:'history'+i,title}))]},{id:'empty',name:'我的新项目',kind:'empty',branch:'main',ready:true,threads:[]}],root:'repo',thread:'initial',runs:{},configs:{},drafts:{}});
  let state;try{state=JSON.parse(sessionStorage.getItem('spaceagent-prototype-workflows-v1'))||seed()}catch{state=seed()}
  if(state.agentRecords?.length)app.agents().splice(0,app.agents().length,...state.agentRecords);
  let generation=0, file=null, mode='询问代码', coder='代码助手', reviewer='评审助手', expanded=new Set(state.roots.map(r=>r.id));
  let pageLimit=4, older=false, scenario='正常完成',wizard=null;
  const root=()=>state.roots.find(r=>r.id===state.root), key=(scope)=>scope==='project'?'project:'+state.thread:'chat:'+app.chat().id;
  const save=()=>{state.agentRecords=app.agents();try{sessionStorage.setItem('spaceagent-prototype-workflows-v1',JSON.stringify(state))}catch{app.toast('浏览器未允许保存演示状态，刷新后可能恢复初始值')}};
  function bind(parent=document){parent.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>action(b.dataset.flow));}
  function dialog(title,html){app.showDialog(title,html);bind($('#dialog'))}
  function confirmation(title,body,ok){dialog(title,`<p class="flow-copy">${body}</p><div class="form-actions">${button('模拟删除失败','delete-failed')}${button('取消','close')}<button class="btn danger" id="flowConfirm">确认删除</button></div>`);$('#flowConfirm').onclick=()=>{ok();save();$('#dialog').close();project();app.toast('演示记录已删除，物理代码保留')}}
  function tree(){
    $('#projectDetails .project-content').innerHTML=`<div class="section-label">我的项目<button aria-label="新建根目录" data-flow="new-root">＋</button></div><div class="tree">${state.roots.map(r=>`<div class="root-row"><button class="folder" data-flow="root:${r.id}" aria-expanded="${expanded.has(r.id)}"><span>▱</span><span class="truncate" title="${E(r.name)}">${E(r.name)}</span><span>⌄</span></button><button class="row-menu" aria-label="管理${E(r.name)}" data-flow="root-menu:${r.id}">⋯</button></div>${expanded.has(r.id)?`<div class="threads">${r.threads.slice(0,pageLimit).map(t=>`<div class="root-row ${state.thread===t.id?'thread-selected':''}"><button class="truncate" data-flow="thread:${r.id}:${t.id}" title="${E(t.title)}">${E(t.title)}</button><button class="row-menu" aria-label="删除会话${E(t.title)}" data-flow="delete-thread:${r.id}:${t.id}">×</button></div>`).join('')}${r.threads.length>pageLimit?button('继续加载','load-threads'):''}<button data-flow="new-thread:${r.id}">＋ 新建会话</button></div>`:''}`).join('')}${button('＋ 新建根目录','new-root')}</div>`;bind($('#projectDetails'));
  }
  function toolbar(scope){const target=scope==='project'?$('#projectLayout .conversation'):$('#chatLayout .conversation');let tools=target.querySelector('.flow-toolbar');if(!tools){tools=document.createElement('div');tools.className='flow-toolbar';target.prepend(tools)}tools.innerHTML=`<span>状态演示</span><select aria-label="${scope==='project'?'项目':'对话'}演示场景" data-scenario="${scope}">${['正常完成','等待审批','连接中断','部分回答','执行失败','取消结果不确定'].map(s=>`<option ${s===scenario?'selected':''}>${s}</option>`).join('')}</select><span class="flow-demo-note">本地模拟，可刷新恢复</span>${button('重置演示','reset')}`;tools.querySelector('select').onchange=e=>scenario=e.target.value;bind(tools)}
  function project(){
    tree();const r=root();const selected=r?.threads.find(t=>t.id===state.thread);const crumb=$('.breadcrumb b');if(crumb)crumb.textContent=r?.name||'项目';$('#title').textContent=selected?.title||r?.name||'选择或新建根目录';$('#subtitle').textContent=r?`${r.name} / ${r.branch}`:'仓库与空白根目录平级，会话直接属于根目录';
    $('#composerBranch').textContent=r?'⑂ '+r.branch:'';$('#prompt').disabled=!selected||!r.ready;$('#prompt').placeholder=selected?(r.ready?'描述要分析或完成的工作…':'请先准备工作区'):'先新建或选择一个会话';$('#prompt').value=state.drafts[state.thread]||'';$('#prompt').oninput=e=>{state.drafts[state.thread]=e.target.value;save()};
    const modes=$('#mode');modes.innerHTML=['询问代码','AI 编程'].map(m=>`<option ${m===mode?'selected':''}>${m}</option>`).join('');modes.onchange=e=>{mode=e.target.value;inspector()};
    $('#composer .send').disabled=!selected||!r?.ready;
    const run=state.runs[key('project')];$('#composer .send').disabled=!selected||!r?.ready||['running','approval','review','disconnected','unknown'].includes(run?.status);$('#messages').innerHTML=run?runHTML(run,'project'):selected?.id==='initial'?`<div class="user-message">帮我看看群消息的消费逻辑，如何避免重复写入？</div>${answerHTML(false)}`:selected?'<div class="flow-empty"><span class="mark"></span><h2>从这个目录开始</h2><p>可以直接询问代码，或切换到 AI 编程。无需先打开文件。</p></div>':'<div class="flow-empty"><h2>还没有选中的会话</h2><p>新建根目录或会话后，即可开始工作。</p></div>';
    if(state.archives?.[key('project')])$('#messages').insertAdjacentHTML('afterbegin',state.archives[key('project')].map(r=>'<details class="past-answer"><summary>'+E(r.prompt)+' · '+labels[r.status]+'</summary>'+answerHTML(r.status!=='done')+'</details>').join(''));if(selected){$('#messages').insertAdjacentHTML('afterbegin',older?'<div class="older-messages"><p class="form-help">更早的消息 · 已加载</p><div class="user-message">先确认消费入口的位置。</div><p class="flow-copy">示例：消费入口位于 GroupMessageConsumer，下面继续分析。</p></div>':button('加载更早消息','older'))}bind($('#messages'));toolbar('project');inspector();
  }
  function inspector(){
    const r=root(),run=state.runs[key('project')],locked=run&&(['running','approval','review','disconnected','unknown'].includes(run.status)||(run.coding&&run.status==='done'&&run.branch===r?.branch));
    $('#projectLayout .inspector').innerHTML=`<header>环境${r?`<span class="tag ${r.ready?'green':'amber'}">${r.ready?'可读 · 可编程':'待准备'}</span>`:''}</header>${r?`<div class="repo-tile"><b>${E(r.name)}</b><small>${r.kind==='repo'?'仓库根目录':'空白根目录 · 后端管理存储（示意）'}</small></div><label class="field-label" for="flowBranch">代码分支</label><select id="flowBranch" class="search-input" ${locked?'disabled':''}>${(r.kind==='repo'?['new-web','main','feature/login']:['main']).map(b=>`<option ${b===r.branch?'selected':''}>${b}</option>`).join('')}</select>${locked?'<p class="form-help">执行未结束或有待处理的已评审变更，暂不能切换分支。</p>':''}<div class="meta-row"><span>执行环境</span><b>隔离工作区 · 演示</b></div><div class="meta-row"><span>存储</span><b>${r.ready?'已准备（模拟）':'尚未准备'}</b></div>${!r.ready?button('准备工作区','prepare'):''}<div class="agent-bindings"><label>编程 Agent${select('coder',['代码助手','通用助手'],coder)}</label><label>独立评审 Agent${select('reviewer',['评审助手','通用助手','代码助手'],reviewer)}</label><p class="form-help">编程与评审必须绑定不同 Agent。</p></div><hr><div class="files-head"><b>文件变更</b><span class="tag">${run?.coding&&run.status==='done'?'+12 −3':'无变更'}</span></div>${run?.coding&&run.status==='done'?button('查看评审结果','review-result'):'<p class="form-help">尚无文件修改。</p>'}<details><summary>仓库文件</summary><p class="form-help">${E(r.branch)} · 只读浏览</p>${button('打开文件浏览器','files')}</details><details><summary>任务、审批与评审</summary><p class="form-help">${run?labels[run.status]:'暂无任务'}。基线与目标：${E(r.branch)}</p>${run?.coding?`<p class="form-help">编程：${E(run.coder)}<br>评审：${E(run.reviewer)}</p>`:''}${button('查看过程','run-detail')}</details>`:'<p class="form-help">请先选择根目录。</p>'}`;
    if($('#flowBranch'))$('#flowBranch').onchange=e=>{r.branch=e.target.value;file=null;save();project();app.toast('已切换演示分支；文件与后续执行使用新上下文')};
    const c=$('[name=coder]'),v=$('[name=reviewer]');if(c)c.onchange=e=>{coder=e.target.value};if(v)v.onchange=e=>{reviewer=e.target.value};
    if(locked){if(c)c.disabled=true;if(v)v.disabled=true}bind($('#projectLayout .inspector'));
  }
  const labels={running:'生成中',approval:'等待审批',review:'独立评审中',done:'完成',partial:'部分完成',failed:'失败',cancelled:'已取消',disconnected:'连接中断',unknown:'操作结果待确认'};
  function answerHTML(partial){return `<article><div class="assistant-head"><span class="mark"></span>SpaceAgent <small>示例回答</small></div><div class="response markdown-demo"><h2>先保证写入幂等，再记录处理结果</h2><p>数据库约束负责拦截重复消息，消费记录负责区分成功与失败。</p><blockquote>消息重复投递是需要处理的正常情况，不应直接当成系统故障。</blockquote><ul><li>为 <code>group_id + sender_id + client_msg_id</code> 建立唯一约束。</li><li>记录成功、重复与失败，供排查和重试使用。</li></ul><div class="table-wrap"><table><thead><tr><th>场景</th><th>处理方式</th></tr></thead><tbody><tr><td>首次消费</td><td>写入并记录成功</td></tr><tr><td>重复消费</td><td>跳过重复写入</td></tr></tbody></table></div><div class="code"><div class="code-header">Java · 示例代码</div><pre>try {
    messageRepository.insert(message);
    consumption.markSuccess(messageId);
} catch (DuplicateKeyException e) {
    consumption.markDuplicate(messageId);
}</pre></div>${partial?'<p class="partial-note">当前只展示已生成部分。剩余说明尚未完成。</p>':'<p>最后再补充并发投递与重试场景的验证，确认约束和日志都能正确工作。</p>'}</div></article>`}
  function runHTML(run,scope){return `<div class="user-message">${E(run.prompt)}</div><div class="run-status" role="status"><div><span class="dot"></span><b>${labels[run.status]}</b><small>${run.coding?'编程：'+E(run.coder)+' · 评审：'+E(run.reviewer):'只读分析'}${run.branch?' · '+E(run.branch):''}</small></div>${['running','review'].includes(run.status)?button('停止',`stop:${scope}`):''}</div>${run.status==='approval'?`<div class="approval-card"><h3>需要允许本次操作</h3><p>${run.coding?'拟修改当前工作区中的代码并执行验证。':'拟调用已连接的工具读取相关资料。'}批准仅适用于这一次操作。</p><div class="tags"><span class="tag">操作审批</span><span class="tag">不是 Agent 配置审批</span></div><div class="form-actions">${button('拒绝',`reject:${scope}`)}${button('批准并继续',`approve:${scope}`,'accent')}</div></div>`:''}${run.status==='review'?'<div class="approval-card"><h3>实现已完成，等待独立评审</h3><p>评审助手正在检查本次修改。编程 Agent 不为自己的修改作出评审结论。</p></div>':''}${run.status==='running'?'<p class="flow-copy">正在读取当前上下文并生成回答…</p>':''}${['done','partial','disconnected','unknown','cancelled'].includes(run.status)?answerHTML(run.status!=='done'):''}${run.status==='disconnected'?`<div class="approval-card"><p>连接断开，执行结果尚未确认。重新连接只读取状态，不重发完整请求。</p>${button('重新连接',`reconnect:${scope}`,'accent')}</div>`:''}${run.status==='partial'?`<div class="approval-card"><p>回答达到演示输出限制，已有内容已保留。可进行一次有限续写。</p>${button('续写剩余内容',`continue:${scope}`)}</div>`:''}${run.status==='failed'?`<div class="approval-card"><p>工具读取超时，本次未完成。重试沿用当前任务，不创建重复记录。</p>${button('重试当前任务',`retry:${scope}`)}</div>`:''}${run.status==='unknown'?`<div class="approval-card"><p>已发送的外部操作无法确认结果。停止后不代表操作已撤销，需核对执行状态。</p>${button('核对状态',`reconcile:${scope}`)}</div>`:''}${run.status==='cancelled'?'<p class="flow-copy">执行已停止，已有回答保留。不会自动重新发送请求。</p>':''}${run.status==='done'&&run.coding?`<div class="approval-card"><h3>独立评审通过 · 演示</h3><p>${E(run.reviewer)} 已检查本次修改。变更保留在工作区，未推送，也未创建 PR。</p>${button('查看评审与变更','review-result')}</div>`:''}`}
  function renderRun(scope){if(scope==='project')project();else app.renderChat()}
  function start(scope,prompt){if(!prompt.trim())return;const r=root();if(scope==='project'&&(!r?.ready||!state.thread)){app.toast('请先准备根目录并选择会话');return}if(scope==='project'&&mode==='AI 编程'&&coder===reviewer){app.toast('请选择不同的编程 Agent 和评审 Agent');return}const id=key(scope);if(['running','approval','review','disconnected','unknown'].includes(state.runs[id]?.status)){app.toast('当前执行尚未结束，请先处理状态');return}
    if(state.runs[id]){state.archives ||= {};state.archives[id] ||= [];state.archives[id].push(state.runs[id])}const run={prompt,status:'running',coding:scope==='project'&&mode==='AI 编程',coder,reviewer,branch:scope==='project'?r.branch:null,scenario,attempt:1};state.runs[id]=run;if(scope==='project'){state.drafts[state.thread]='';$('#prompt').value=''}else{app.chat().draft='';app.chat().title=prompt.slice(0,16);app.chat().messages.push(['user',prompt]);$('#chatPrompt').value=''}save();renderRun(scope);advance(scope,id,run);
  }
  function advance(scope,id,run){setTimeout(()=>{if(state.runs[id]!==run||run.status!=='running')return;run.status=({'等待审批':'approval','连接中断':'disconnected','部分回答':'partial','执行失败':'failed','取消结果不确定':'unknown'})[run.scenario]||(run.coding?'review':'done');save();if(key(scope)===id)renderRun(scope);if(run.status==='review')finishReview(scope,id,run)},900)}
  function finishReview(scope,id,run){setTimeout(()=>{if(state.runs[id]!==run||run.status!=='review')return;run.status='done';save();if(key(scope)===id)renderRun(scope)},1600)}
  function recover(scope){const run=state.runs[key(scope)];if(run?.status==='running'){run.status='disconnected';save()}if(run?.status==='review')finishReview(scope,key(scope),run)}
  function fileBrowser(){const r=root();if(!r)return;const files=r.kind==='empty'?['README.md']:r.branch==='main'?['.gitignore']:['src/main/java/GroupMessageConsumer.java','src/test/java/GroupMessageConsumerTest.java','pom.xml','README.md'];file=files.includes(file)?file:files[0];dialog('仓库文件',`<div class="file-context">${E(r.name)} / ${E(r.branch)} <span class="tag">只读</span></div><div class="file-browser"><nav>${r.branch!=='main'&&r.kind!=='empty'?'<details open><summary>src / main / java</summary><button data-file="src/main/java/GroupMessageConsumer.java">GroupMessageConsumer.java</button></details><details><summary>src / test / java</summary><button data-file="src/test/java/GroupMessageConsumerTest.java">GroupMessageConsumerTest.java</button></details>':''}${files.filter(f=>!f.includes('/')).map(f=>`<button data-file="${f}">${f}</button>`).join('')}</nav><section><div class="code-header" id="filePath"></div><pre id="fileCode"></pre></section></div><p class="form-help">当前为示例文件。关闭后仍可继续 AI 对话编程，无需手动编辑。</p><div class="form-actions">${button('模拟无法预览','file-error')}${button('关闭文件面板','close')}</div>`);$('#dialog').classList.add('wide-dialog');function show(f){file=f;$('#filePath').textContent=f;$('#fileCode').textContent=f==='.gitignore'?'target/\nnode_modules/\n.env':f.endsWith('.java')?'// '+r.branch+' · 示例源码\npublic class GroupMessageConsumer {\n    public void consume(Message message) {\n        repository.insert(message);\n    }\n}':f==='pom.xml'?'<project>\n  <artifactId>schat</artifactId>\n</project>':'# '+r.name+'\n\n项目说明与开发约定。';}document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>show(b.dataset.file));show(file)}
  function newRoot(){wizard={stage:0,kind:'repo',repo:'example-org/demo-repository',branch:'new-web',name:'我的新项目',connected:false,status:''};wizardView()}
  function wizardView(){dialog('新建根目录',`<div class="wizard-steps">${['类型','连接与选择','准备工作区'].map((t,i)=>`<span class="${wizard.stage===i?'active':''}">${i+1} ${t}</span>`).join('')}</div>${wizard.stage===0?`<p class="flow-copy">根目录之间平级，会话直接属于根目录。</p><div class="root-options">${button('▱ 导入 GitHub 仓库','wizard-repo')}${button('＋ 创建空白根目录','wizard-empty')}</div>`:wizard.stage===1?wizard.kind==='repo'?`<div class="flow-copy">GitHub ${wizard.connected?'已连接（模拟）':'尚未连接'}</div>${!wizard.connected?button('连接 GitHub（演示）','wizard-connect','accent'):`<div class="form-stack"><label>选择仓库${select('repo',['example-org/demo-repository','example/design-system'],wizard.repo)}</label><label>选择分支${select('importBranch',['new-web','main','feature/login'],wizard.branch)}</label><p class="form-help">授权完成后仍需准备工作区。</p>${button('准备工作区','wizard-prepare','accent')}${button('模拟授权失效','wizard-expire')}</div>`}`:`<div class="form-stack"><label>根目录名称<input id="emptyName" maxlength="60" value="${E(wizard.name)}"></label><p class="form-help">正式环境由后端分配真实存储，无需填写服务器路径。本原型仅展示流程。</p>${button('准备空白工作区','wizard-prepare','accent')}</div>`:`<div class="approval-card"><h3>${wizard.status==='failed'?'准备失败':wizard.status==='ready'?'工作区已就绪（模拟）':'准备工作区'}</h3><p>${wizard.status==='failed'?'示例：仓库连接超时。重试沿用本次导入，不重复创建根目录。':wizard.status==='ready'?'已准备独立工作区，可读代码并开始编程。':'点击下方按钮体验准备成功或失败的状态。'}</p><div class="form-actions">${wizard.status==='ready'?button('创建根目录并开始会话','wizard-finish','accent'):button(wizard.status==='failed'?'重试准备':'模拟准备成功','wizard-ready','accent')+button('模拟准备失败','wizard-fail')}</div></div>`}<p class="notice">仅交互演示，不连接 GitHub，不创建真实存储。</p>`);}
  function configureAgent(index){const list=app.agents(),a=list[index];const editing=!!a;const base=state.configs[a?.name]||{binding:'直接模型',model:'千问 / qwen-plus',memory:true,rag:false,network:false,prompt:'清晰说明判断依据，按用户授权范围完成工作。',permission:'每次询问'};dialog(editing?'配置 '+E(a.name):'创建 Agent',`<form id="agentFullForm" class="form-stack"><label>名称<input name="name" required maxlength="60" value="${E(a?.name||'')}"></label><label>用途<input name="desc" required value="${E(a?.desc||'')}"></label><label>范围${select('type',['个人','组织'],a?.type||'个人')}</label><label>系统指令<textarea name="prompt">${E(base.prompt)}</textarea></label><div class="form-columns"><label>模型绑定${select('binding',['直接模型','ModelPool'],base.binding)}</label><label>模型 / 模型池<select name="model" id="agentModel"></select></label></div><div class="settings-checks"><label><input type="checkbox" name="memory" ${base.memory?'checked':''}>启用 Memory</label><label><input type="checkbox" name="rag" ${base.rag?'checked':''}>启用 RAG</label><label><input type="checkbox" name="network" disabled>联网搜索 <small>当前未连接搜索工具</small></label></div><label id="ragSources">知识库${select('knowledge',['产品文档','工程规范'],base.knowledge)}</label><label>工具权限${select('permission',['每次询问','只读','禁止工具'],base.permission)}</label><details><summary>工具与 Skill</summary><p class="form-help">工作区文件：可用（项目上下文）<br>网页搜索：不可用，需先连接工具<br>工程规范 Skill：已绑定（演示）</p></details><p class="form-help">只编辑当前配置。组织 Agent 的修改需所有者批准后生效；与编程任务的独立评审无关。</p><div class="form-actions">${editing?button('删除 Agent','delete-agent:'+index):''}<button class="btn accent">${a?.type==='组织'?'提交修改审批':'保存当前配置'}</button></div></form>`);$('#dialog').classList.add('wide-dialog');function binding(){const binding=$('[name=binding]').value;$('#agentModel').innerHTML=(binding==='直接模型'?['千问 / qwen-plus','OpenAI / 演示模型']:['日常对话池','代码推理池']).map(v=>`<option ${v===base.model?'selected':''}>${v}</option>`).join('')}binding();$('[name=binding]').onchange=binding;function rag(){$('#ragSources').hidden=!$('[name=rag]').checked}rag();$('[name=rag]').onchange=rag;$('#agentFullForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!data.name.trim()||!data.desc.trim())return;const config={...data,memory:data.memory==='on',rag:data.rag==='on',network:false,knowledge:data.rag==='on'?data.knowledge:null};const proposal={name:data.name,desc:data.desc,type:data.type,model:data.model,icon:a?.icon||'✧'};if(a?.type==='组织'||data.type==='组织'){state.pending={index:editing?index:-1,proposal,config};save();approvalConfig()}else{if(editing)list[index]=proposal;else list.push(proposal);state.configs[data.name]=config;save();$('#dialog').close();app.render();app.toast('演示当前配置已更新')}};}
  function approvalConfig(){dialog('配置修改待审批',`<div class="approval-card"><h3>当前配置继续生效</h3><p>申请中的模型、Memory、RAG 等修改尚未应用。这是组织 Agent 配置审批，不是代码评审。</p><p class="form-help">以下按钮模拟所有者处理。</p><div class="form-actions">${button('模拟拒绝','config-reject')}${button('模拟所有者批准','config-approve','accent')}</div></div>`)}
  function action(actionValue){const [name,a,b]=actionValue.split(':');if(name==='delete-failed'){app.toast('模拟删除失败：连接超时，记录仍保留，请重试');return}if(name==='older'){older=true;project();return}if(name==='close'){$('#dialog').close();return}if(name==='reset'){state=seed();expanded=new Set(state.roots.map(r=>r.id));pageLimit=4;older=false;scenario='正常完成';app.chats().splice(0,app.chats().length,{id:1,title:'新对话',messages:[],draft:''});app.setChatId(1);save();file=null;project();app.renderChat();app.toast('已重置本地流程演示');return}if(name==='new-root')return newRoot();if(name==='root'){state.root=a;state.thread=state.roots.find(r=>r.id===a).threads[0]?.id||null;expanded.has(a)?expanded.delete(a):expanded.add(a);file=null;save();project();return}if(name==='thread'){state.root=a;state.thread=b;file=null;save();project();return}if(name==='load-threads'){pageLimit+=4;tree();return}if(name==='new-thread'){const r=state.roots.find(r=>r.id===a)||root();if(!r)return newRoot();const t={id:'t'+Date.now(),title:'新会话 '+(r.threads.length+1)};r.threads.push(t);state.root=r.id;state.thread=t.id;expanded.add(r.id);save();project();return}if(name==='root-menu'){dialog('管理根目录',`<p class="flow-copy">${E(state.roots.find(r=>r.id===a).name)}</p><div class="form-actions">${button('新建会话','new-thread-close:'+a)}${button('删除根目录','delete-root:'+a)}</div>`);return}if(name==='new-thread-close'){$('#dialog').close();action('new-thread:'+a);return}if(name==='delete-thread'){confirmation('删除会话','只删除该会话及其组织关系，不删除根目录中的物理代码。',()=>{const r=state.roots.find(r=>r.id===a);r.threads=r.threads.filter(t=>t.id!==b);delete state.runs['project:'+b];if(state.thread===b)state.thread=r.threads[0]?.id||null});return}if(name==='delete-root'){confirmation('删除逻辑根目录','删除此根目录及其会话入口。物理代码保留；物理存储清理由管理员通过专门流程处理。',()=>{state.roots=state.roots.filter(r=>r.id!==a);if(state.root===a){state.root=state.roots[0]?.id;state.thread=state.roots[0]?.threads[0]?.id||null}});return}
    if(name==='prepare'){root().ready=true;save();project();return}if(name==='files')return fileBrowser();if(name==='file-error'){$('#fileCode').textContent='无法预览：文件超过预览大小限制。可返回文件树选择其他文件，或在对话中询问相关内容。';return}
    if(name==='review-result'){const run=state.runs[key('project')];dialog('评审与变更',`<div class="flow-copy"><h3>${run?.status==='done'?'评审通过（演示）':'尚未完成评审'}</h3><p>编程 Agent：${E(run?.coder||coder)}<br>评审 Agent：${E(run?.reviewer||reviewer)}<br>修改基线与后续合并目标：${E(run?.branch||root()?.branch||'—')}</p><div class="code"><pre>+ 增加重复消息处理分支
+ 补充消费记录与验证
- 移除重复写入逻辑</pre></div><p>未推送、未创建 PR。原型不执行代码修改或合并。</p></div>`);return}if(name==='run-detail'){dialog('执行过程',`<div class="timeline"><div>接收当前会话目标<small>自动绑定根目录与分支</small></div><div>编程 Agent 实施<small>${E(coder)}</small></div><div>独立评审 Agent 检查<small>${E(reviewer)}</small></div><div>后续处理<small>根据真实执行状态提供操作</small></div></div>`);return}
    if(name.startsWith('wizard-')){if(name==='wizard-repo'||name==='wizard-empty'){wizard.kind=name==='wizard-repo'?'repo':'empty';wizard.branch=wizard.kind==='empty'?'main':'new-web';wizard.stage=1}if(name==='wizard-connect')wizard.connected=true;if(name==='wizard-expire'){wizard.connected=false;app.toast('授权已失效，请重新连接')}if(name==='wizard-prepare'){if(wizard.kind==='repo'){wizard.repo=$('[name=repo]').value;wizard.branch=$('[name=importBranch]').value}else{wizard.name=$('#emptyName').value.trim();if(!wizard.name){$('#emptyName').focus();return}}wizard.stage=2;wizard.status='preparing'}if(name==='wizard-ready')wizard.status='ready';if(name==='wizard-fail')wizard.status='failed';if(name==='wizard-finish'){const name=wizard.kind==='repo'?wizard.repo:wizard.name;let r=state.roots.find(r=>r.name===name);if(!r){r={id:'r'+Date.now(),name,kind:wizard.kind,branch:wizard.branch,ready:true,threads:[]};state.roots.push(r)}state.root=r.id;expanded.add(r.id);$('#dialog').close();action('new-thread:'+r.id);return}wizardView();return}
    if(name==='delete-agent'){confirmation('删除 Agent','删除当前 Agent，而不是归档。正在引用该 Agent 的任务在正式环境中需由后端判断是否允许删除。',()=>{app.agents().splice(Number(a),1);app.render()});return}if(name==='config-approve'){const p=state.pending;if(p){if(p.index>=0)app.agents()[p.index]=p.proposal;else app.agents().push(p.proposal);state.configs[p.proposal.name]=p.config;delete state.pending;save();app.render();$('#dialog').close();app.toast('模拟审批通过，当前配置已生效')}return}if(name==='config-reject'){delete state.pending;save();$('#dialog').close();app.toast('修改被拒绝，原配置保留');return}if(name==='config-pending')return approvalConfig();
    const scope=a,run=state.runs[key(scope)];if(!run)return;if(name==='stop'){generation++;run.status=run.scenario==='取消结果不确定'?'unknown':'cancelled'}if(name==='reject')run.status='cancelled';if(name==='approve'||name==='retry'){run.status='running';run.scenario='正常完成';if(name==='retry')run.attempt++;advance(scope,key(scope),run)}if(name==='continue')run.status='done';if(name==='reconnect'||name==='reconcile'){run.status=run.coding?'review':'done';if(run.status==='review')finishReview(scope,key(scope),run)}save();renderRun(scope);
  }
  if(state.chats?.length){app.chats().splice(0,app.chats().length,...state.chats);app.setChatId(state.chats.some(c=>c.id===state.chatId)?state.chatId:state.chats[0].id)}
  // Returning to a page presents a durable-state simulation, never resends a request.
  Object.values(state.runs).forEach(r=>{if(r.status==='running')r.status='disconnected'});save();
  if(!app.agents().some(a=>a.name==='评审助手'))app.agents().push({name:'评审助手',desc:'独立检查代码修改与验证结果，不评审自己实施的任务。',model:'千问',type:'组织',icon:'✓'});
  const oldClose=$('#closeDialog').onclick;$('#closeDialog').onclick=()=>{oldClose();$('#dialog').classList.remove('wide-dialog')};$('#dialog').addEventListener('close',()=>$('#dialog').classList.remove('wide-dialog'));
  $('#composer').onsubmit=e=>{e.preventDefault();start('project',$('#prompt').value)};
  return {
    navigate(route){if(route==='project'){recover('project');project()}if(route==='chat'){recover('chat');toolbar('chat')}},
    chatRender(){state.chats=app.chats();state.chatId=app.chat().id;save();toolbar('chat');const run=state.runs[key('chat')];if(run){$('#chatContent').innerHTML=(state.archives?.[key('chat')]||[]).map(r=>'<details class="past-answer"><summary>'+E(r.prompt)+' · '+labels[r.status]+'</summary>'+answerHTML(r.status!=='done')+'</details>').join('')+runHTML(run,'chat');bind($('#chatContent'))}},
    startChat(text){start('chat',text);return true},
    newConversation(){action('new-thread:'+state.root)},
    act(action){if(action==='agent:new'){configureAgent(-1);return true}if(action.startsWith('agent:edit:')){configureAgent(Number(action.split(':')[2]));return true}return false},
    pageRender(){if(app.route()==='agents'&&state.pending){const n=document.createElement('div');n.className='approval-card';n.innerHTML='<b>组织 Agent 配置修改待审批</b><p class="form-help">当前配置仍在生效。</p>'+button('查看审批','config-pending');$('.page-inner').prepend(n);bind(n)}},
  };
};
