package com.spaceagent.platform.inference.infrastructure.memory;

import com.spaceagent.platform.inference.domain.*;import com.spaceagent.shared.time.TimeProvider;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.stereotype.Repository;
import java.time.*;import java.util.*;import java.util.concurrent.ConcurrentHashMap;
@Repository @ConditionalOnProperty(prefix="platform",name="persistence",havingValue="memory",matchIfMissing=true)
public class InMemoryInferenceBudgetRepository implements InferenceBudgetRepository{
 private final TimeProvider time;private final Map<String,InferenceBudgetPolicy> policies=new ConcurrentHashMap<>();private final Map<String,InferenceBudgetReservation> reservations=new ConcurrentHashMap<>();private final Map<String,String> embeddingReservations=new ConcurrentHashMap<>();private final Map<String,Period> periods=new ConcurrentHashMap<>();public InMemoryInferenceBudgetRepository(TimeProvider t){time=t;}
 public synchronized InferenceBudgetPolicy savePolicy(InferenceBudgetPolicy p){policies.put(p.tenantId(),p);return p;}public Optional<InferenceBudgetPolicy> findPolicy(String t){return Optional.ofNullable(policies.get(t));}
 public synchronized ReservationDecision reserve(ReserveRequest r){InferenceBudgetReservation existing=reservations.values().stream().filter(v->Objects.equals(v.agentRunId(),r.agentRunId())&&v.logicalCallId().equals(r.logicalCallId())).findFirst().orElse(null);if(existing!=null)return new ReservationDecision(existing,false);String key=periodKey(r.tenantId());Period p=periods.computeIfAbsent(key,k->new Period());InferenceBudgetPolicy policy=policies.get(r.tenantId());if(policy!=null&&policy.enabled()){if(policy.monthlyCostLimitMicros()>0&&r.reservedCostMicros()==null)throw new InferenceBudgetLimitException("INFERENCE_PRICE_REQUIRED");check(policy.monthlyRequestLimit(),p.consumedRequests+p.reservedRequests+1,"INFERENCE_REQUEST_QUOTA_EXCEEDED");check(policy.monthlyTokenLimit(),p.consumedTokens+p.reservedTokens+r.reservedTokens(),"INFERENCE_TOKEN_BUDGET_EXCEEDED");check(policy.monthlyCostLimitMicros(),p.consumedCost+p.reservedCost+nvl(r.reservedCostMicros()),"INFERENCE_COST_BUDGET_EXCEEDED");}p.reservedRequests++;p.reservedTokens+=r.reservedTokens();p.reservedCost+=nvl(r.reservedCostMicros());Instant now=time.now();InferenceBudgetReservation v=new InferenceBudgetReservation(r.id(),r.tenantId(),r.agentRunId(),r.logicalCallId(),r.providerId(),r.modelId(),r.priceId(),r.inputRate(),r.outputRate(),r.reservedTokens(),r.reservedCostMicros(),"HELD",null,null,null,now,now);reservations.put(v.id(),v);if(r.embeddingCallId()!=null)embeddingReservations.put(r.embeddingCallId(),v.id());return new ReservationDecision(v,true);}
 public synchronized Optional<InferenceBudgetReservation> settle(String id,long in,long out){InferenceBudgetReservation v=reservations.get(id);if(v==null)return Optional.empty();if(v.status().equals("SETTLED"))return Optional.of(v);if(!v.status().equals("HELD"))return Optional.of(v);Period p=periods.get(periodKey(v.tenantId()));long cost=cost(v,in,out);p.reservedRequests--;p.reservedTokens-=v.reservedTokens();p.reservedCost-=nvl(v.reservedCostMicros());p.consumedRequests++;p.consumedTokens+=in+out;p.consumedCost+=cost;InferenceBudgetReservation done=new InferenceBudgetReservation(v.id(),v.tenantId(),v.agentRunId(),v.logicalCallId(),v.providerId(),v.modelId(),v.priceId(),v.inputPriceMicrosPerMillion(),v.outputPriceMicrosPerMillion(),v.reservedTokens(),v.reservedCostMicros(),"SETTLED",in,out,v.priceId()==null?null:cost,v.createdAt(),time.now());reservations.put(id,done);return Optional.of(done);}
 public synchronized void release(String id){InferenceBudgetReservation v=reservations.get(id);if(v==null||!v.status().equals("HELD"))return;Period p=periods.get(periodKey(v.tenantId()));p.reservedRequests--;p.reservedTokens-=v.reservedTokens();p.reservedCost-=nvl(v.reservedCostMicros());reservations.put(id,new InferenceBudgetReservation(v.id(),v.tenantId(),v.agentRunId(),v.logicalCallId(),v.providerId(),v.modelId(),v.priceId(),v.inputPriceMicrosPerMillion(),v.outputPriceMicrosPerMillion(),v.reservedTokens(),v.reservedCostMicros(),"RELEASED",null,null,null,v.createdAt(),time.now()));}
 public synchronized void markUnknown(String id){InferenceBudgetReservation v=reservations.get(id);if(v!=null&&v.status().equals("HELD"))reservations.put(id,new InferenceBudgetReservation(v.id(),v.tenantId(),v.agentRunId(),v.logicalCallId(),v.providerId(),v.modelId(),v.priceId(),v.inputPriceMicrosPerMillion(),v.outputPriceMicrosPerMillion(),v.reservedTokens(),v.reservedCostMicros(),"UNKNOWN",null,null,null,v.createdAt(),time.now()));}
 public synchronized Optional<InferenceBudgetReservation> findEmbeddingReservation(String id){String r=embeddingReservations.get(id);return r==null?Optional.empty():Optional.ofNullable(reservations.get(r));}
 public synchronized BudgetUsage usage(String t){Period p=periods.getOrDefault(periodKey(t),new Period());return new BudgetUsage(p.consumedRequests,p.reservedRequests,p.consumedTokens,p.reservedTokens,p.consumedCost,p.reservedCost);}
 private String periodKey(String t){ZonedDateTime z=time.now().atZone(ZoneOffset.UTC);return t+":"+z.getYear()+":"+z.getMonthValue();}private static void check(long limit,long value,String code){if(limit>0&&value>limit)throw new InferenceBudgetLimitException(code);}private static long nvl(Long v){return v==null?0:v;}private static long cost(InferenceBudgetReservation v,long in,long out){if(v.priceId()==null)return 0;return ceil(in,v.inputPriceMicrosPerMillion())+ceil(out,v.outputPriceMicrosPerMillion());}private static long ceil(long tokens,long rate){return Math.addExact(Math.multiplyExact(tokens,rate),999999)/1000000;}private static class Period{long consumedRequests,reservedRequests,consumedTokens,reservedTokens,consumedCost,reservedCost;}
}
