package com.spaceagent.platform.artifact;

import com.spaceagent.platform.artifact.api.ArtifactObjectMaintenanceApplicationApi;
import com.spaceagent.platform.artifact.application.ArtifactObjectMaintenanceApplicationService;
import com.spaceagent.platform.artifact.domain.*;
import com.spaceagent.platform.artifact.infrastructure.memory.InMemoryArtifactObjectRepository;
import org.junit.jupiter.api.Test;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.atomic.*;
import static org.assertj.core.api.Assertions.*;

class ArtifactObjectMaintenanceApplicationServiceTest {
    @Test void bytesAreDeletedBeforeAtomicMetadataCompletion(){Fixture f=new Fixture(false);var scheduled=f.service.scheduleDeletion(new ArtifactObjectMaintenanceApplicationApi.ScheduleDeletionCommand("tenant",f.object.id()));assertThat(scheduled.state()).isEqualTo("PENDING");assertThat(f.service.runDeletionOnce("worker",60)).isTrue();assertThat(f.deleted.get()).isTrue();assertThat(f.repo.findObject("tenant",f.object.id())).get().extracting(ManagedArtifactObject::state).isEqualTo(ManagedArtifactObject.State.DELETED);assertThat(f.repo.findDeletion("tenant",f.object.id())).get().extracting(ArtifactObjectDeletionJob::state).isEqualTo(ArtifactObjectDeletionJob.State.COMPLETED);}
    @Test void byteFailureBlocksObjectAndJobWithoutMetadataDeletion(){Fixture f=new Fixture(true);f.service.scheduleDeletion(new ArtifactObjectMaintenanceApplicationApi.ScheduleDeletionCommand("tenant",f.object.id()));f.service.runDeletionOnce("worker",60);assertThat(f.repo.findObject("tenant",f.object.id())).get().extracting(ManagedArtifactObject::state).isEqualTo(ManagedArtifactObject.State.BLOCKED);assertThat(f.repo.findDeletion("tenant",f.object.id())).get().satisfies(v->{assertThat(v.state()).isEqualTo(ArtifactObjectDeletionJob.State.BLOCKED);assertThat(v.safeErrorCode()).isEqualTo("ARTIFACT_BYTES_DELETE_BLOCKED");});}
    @Test void activeReferenceOrLegalHoldPreventsScheduling(){Fixture refs=new Fixture(false);refs.repo.insertReference(new ArtifactObjectReference("ref","tenant",refs.object.id(),ArtifactObjectReference.OwnerType.PROJECT,"project","source",ArtifactObjectReference.State.ACTIVE,1,refs.now.get(),null));assertThatThrownBy(()->refs.service.scheduleDeletion(new ArtifactObjectMaintenanceApplicationApi.ScheduleDeletionCommand("tenant",refs.object.id()))).isInstanceOf(IllegalStateException.class);Fixture holds=new Fixture(false);holds.repo.insertHold(new ArtifactObjectLegalHold("hold","tenant",holds.object.id(),HASH,"owner",ArtifactObjectLegalHold.State.ACTIVE,1,holds.now.get(),null,null));assertThatThrownBy(()->holds.service.scheduleDeletion(new ArtifactObjectMaintenanceApplicationApi.ScheduleDeletionCommand("tenant",holds.object.id()))).isInstanceOf(IllegalStateException.class);}
    @Test void expiredUnpublishedStagingIsRemovedAndRejected(){Fixture f=new Fixture(false);var session=new ArtifactObjectStagingSession("00000000-0000-4000-8000-000000000090","tenant","owner","expired",HASH,0,"text/plain","tenant-key:v1",null,ArtifactObjectStagingSession.State.OPEN,null,1,f.now.get().minusSeconds(1),f.now.get().minusSeconds(2),f.now.get().minusSeconds(2));f.repo.insertStaging(session);assertThat(f.service.sweepExpiredStaging(10)).isEqualTo(1);assertThat(f.repo.findStaging("tenant",session.id())).get().extracting(ArtifactObjectStagingSession::state).isEqualTo(ArtifactObjectStagingSession.State.REJECTED);}
    @Test void expiredClaimBecomesBlockedAndIsNeverBlindlyReclaimed(){Fixture f=new Fixture(false);f.service.scheduleDeletion(new ArtifactObjectMaintenanceApplicationApi.ScheduleDeletionCommand("tenant",f.object.id()));assertThat(f.repo.claimDeletion("lost",UUID.randomUUID().toString(),1)).isPresent();f.now.set(f.now.get().plusSeconds(2));assertThat(f.service.recoverExpiredDeletion()).isTrue();assertThat(f.repo.findDeletion("tenant",f.object.id())).get().extracting(ArtifactObjectDeletionJob::state).isEqualTo(ArtifactObjectDeletionJob.State.BLOCKED);assertThat(f.repo.claimDeletion("other",UUID.randomUUID().toString(),60)).isEmpty();}
    @Test void blockedDeletionRequiresExplicitRetryAndRechecksHolds(){Fixture f=new Fixture(true);f.service.scheduleDeletion(new ArtifactObjectMaintenanceApplicationApi.ScheduleDeletionCommand("tenant",f.object.id()));f.service.runDeletionOnce("worker",60);assertThat(f.repo.claimDeletion("automatic",UUID.randomUUID().toString(),60)).isEmpty();var retried=f.service.retryBlockedDeletion(new ArtifactObjectMaintenanceApplicationApi.RetryBlockedDeletionCommand("tenant",f.object.id()));assertThat(retried.state()).isEqualTo("PENDING");assertThat(f.repo.claimDeletion("explicit",UUID.randomUUID().toString(),60)).isPresent();Fixture held=new Fixture(true);held.service.scheduleDeletion(new ArtifactObjectMaintenanceApplicationApi.ScheduleDeletionCommand("tenant",held.object.id()));held.service.runDeletionOnce("worker",60);var legacyHold=new ArtifactObjectLegalHold("hold-retry","tenant",held.object.id(),HASH,"owner",ArtifactObjectLegalHold.State.ACTIVE,1,held.now.get(),null,null);assertThatThrownBy(()->held.repo.insertHold(legacyHold)).isInstanceOf(ArtifactObjectLifecycleConflictException.class);@SuppressWarnings("unchecked") var legacyHolds=(java.util.Map<String,ArtifactObjectLegalHold>)org.springframework.test.util.ReflectionTestUtils.getField(held.repo,"holds");legacyHolds.put(legacyHold.id(),legacyHold);assertThatThrownBy(()->held.service.retryBlockedDeletion(new ArtifactObjectMaintenanceApplicationApi.RetryBlockedDeletionCommand("tenant",held.object.id()))).isInstanceOf(com.spaceagent.shared.exception.BusinessException.class);}
    private static final String HASH="sha256:"+"a".repeat(64);private static final class Fixture{final AtomicReference<Instant> now=new AtomicReference<>(Instant.parse("2026-09-09T00:00:00Z"));final InMemoryArtifactObjectRepository repo=new InMemoryArtifactObjectRepository(now::get);final AtomicBoolean deleted=new AtomicBoolean();final ManagedArtifactObject object;final ArtifactObjectMaintenanceApplicationService service;Fixture(boolean fail){var stage=new ArtifactObjectStagingSession("00000000-0000-4000-8000-000000000001","tenant","owner","request",HASH,0,"text/plain","tenant-key:v1",null,ArtifactObjectStagingSession.State.OPEN,null,1,now.get().plusSeconds(300),now.get(),now.get()).verify(HASH,0,"artifact-staging:one",now.get());repo.insertStaging(stage);object=repo.publish("tenant",stage.id(),stage.revision(),new ManagedArtifactObject("00000000-0000-4000-8000-000000000002","tenant","owner",HASH,0,"text/plain","artifact-object:one","tenant-key:v1",new ManagedArtifactObject.Retention(now.get(),true),ManagedArtifactObject.State.READY,1,now.get(),now.get(),null),now.get()).object();ArtifactObjectStorageGateway storage=new ArtifactObjectStorageGateway(){public StagingHandle createStaging(CreateStagingCommand c){throw new UnsupportedOperationException();}public WriteResult write(WriteCommand c){throw new UnsupportedOperationException();}public Verification verify(VerifyCommand c){throw new UnsupportedOperationException();}public PublishResult publish(PublishCommand c){throw new UnsupportedOperationException();}public ReadResult read(ReadQuery q){throw new UnsupportedOperationException();}public void deleteStaging(DeleteStagingCommand c){deleted.set(true);}public void deleteObject(DeleteObjectCommand c){if(fail)throw new IllegalStateException("unknown");deleted.set(true);}};AtomicInteger ids=new AtomicInteger(10);service=new ArtifactObjectMaintenanceApplicationService(repo,storage,()->"00000000-0000-4000-8000-"+String.format("%012d",ids.incrementAndGet()));}}
}
