package com.spaceagent.platform.artifact;

import com.spaceagent.platform.artifact.api.*;
import com.spaceagent.platform.artifact.application.*;
import com.spaceagent.platform.artifact.domain.*;
import com.spaceagent.platform.artifact.infrastructure.*;
import com.spaceagent.platform.artifact.infrastructure.memory.InMemoryArtifactObjectRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import static org.assertj.core.api.Assertions.*;

class ManagedArtifactObjectApplicationServiceTest {
    @TempDir Path root;
    @Test void productionServiceStagesPublishesAttachesAndReadsOpaqueObject(){Instant now=Instant.parse("2026-09-09T00:00:00Z");var repo=new InMemoryArtifactObjectRepository(()->now);var storage=new LocalArtifactObjectStorageGateway(root);AtomicInteger sequence=new AtomicInteger();var maintenance=new ArtifactObjectMaintenanceApplicationService(repo,storage,()->uuid(sequence.incrementAndGet()+100));var properties=new ArtifactObjectStorageProperties();var service=new ManagedArtifactObjectApplicationService(repo,storage,(t,a,type,id)->id.equals("project"),maintenance,(t,a)->t.equals("tenant")&&a.equals("owner"),()->uuid(sequence.incrementAndGet()),properties);String hash=hash("hello");var staging=service.beginStaging(new ArtifactObjectApplicationApi.BeginStagingCommand("tenant","owner","request",hash,5,"text/plain",300));assertThat(staging.state()).isEqualTo("UPLOADING");service.upload(new ArtifactObjectApplicationApi.UploadChunkCommand("tenant","owner",staging.id(),0,Base64.getEncoder().encodeToString("hello".getBytes(StandardCharsets.UTF_8))));var verified=service.verify(new ArtifactObjectApplicationApi.VerifyStagingCommand("tenant","owner",staging.id(),staging.revision()));var object=service.publish(new ArtifactObjectApplicationApi.PublishStagingCommand("tenant","owner",staging.id(),verified.revision(),now.plusSeconds(60),true));assertThat(object.state()).isEqualTo("READY");service.attach(new ArtifactObjectApplicationApi.AttachReferenceCommand("tenant","owner",object.id(),ArtifactObjectReference.OwnerType.PROJECT,"project","report","attach"));var read=service.read(new ArtifactObjectApplicationApi.ReadObjectQuery("tenant","owner",object.id(),0,10));assertThat(new String(Base64.getDecoder().decode(read.contentBase64()),StandardCharsets.UTF_8)).isEqualTo("hello");assertThatThrownBy(()->service.requestDeletion(new ArtifactObjectApplicationApi.RequestDeletionCommand("tenant","owner",object.id(),object.revision(),"delete"))).isInstanceOf(IllegalStateException.class);}
    @Test void crossTenantOrNonMemberCannotReadObject(){var repo=new InMemoryArtifactObjectRepository(()->Instant.now());var storage=new LocalArtifactObjectStorageGateway(root);var maintenance=new ArtifactObjectMaintenanceApplicationService(repo,storage,()->uuid(90));var service=new ManagedArtifactObjectApplicationService(repo,storage,(t,a,type,id)->false,maintenance,(t,a)->false,()->uuid(91),new ArtifactObjectStorageProperties());assertThatThrownBy(()->service.get(new ArtifactObjectApplicationApi.GetObjectQuery("tenant","foreign","missing"))).isInstanceOf(com.spaceagent.shared.exception.BusinessException.class);}
    @Test void publishCanRetryAfterMetadataFailureBecauseStagingBytesRemain(){Instant now=Instant.parse("2026-09-09T00:00:00Z");var repo=new FailOnceRepository(now);var storage=new LocalArtifactObjectStorageGateway(root);AtomicInteger sequence=new AtomicInteger();var service=new ManagedArtifactObjectApplicationService(repo,storage,(t,a,type,id)->true,new ArtifactObjectMaintenanceApplicationService(repo,storage,()->uuid(sequence.incrementAndGet()+100)),(t,a)->true,()->uuid(sequence.incrementAndGet()),new ArtifactObjectStorageProperties());String hash=hash("retry");var staging=service.beginStaging(new ArtifactObjectApplicationApi.BeginStagingCommand("tenant","owner","retry-request",hash,5,"text/plain",300));service.upload(new ArtifactObjectApplicationApi.UploadChunkCommand("tenant","owner",staging.id(),0,Base64.getEncoder().encodeToString("retry".getBytes(StandardCharsets.UTF_8))));var verified=service.verify(new ArtifactObjectApplicationApi.VerifyStagingCommand("tenant","owner",staging.id(),staging.revision()));var publish=new ArtifactObjectApplicationApi.PublishStagingCommand("tenant","owner",staging.id(),verified.revision(),now.plusSeconds(60),true);assertThatThrownBy(()->service.publish(publish)).isInstanceOf(IllegalStateException.class);assertThat(storage.verify(new ArtifactObjectStorageGateway.VerifyCommand("tenant","artifact-staging:"+staging.id(),hash,5)).byteSize()).isEqualTo(5);var object=service.publish(publish);assertThat(object.state()).isEqualTo("READY");assertThatThrownBy(()->storage.verify(new ArtifactObjectStorageGateway.VerifyCommand("tenant","artifact-staging:"+staging.id(),hash,5))).isInstanceOf(IllegalStateException.class);}
    @Test void objectUserAndTenantCapacityLimitsFailBeforeMoreBytesAreCreated(){Instant now=Instant.parse("2026-09-09T00:00:00Z");var repo=new InMemoryArtifactObjectRepository(()->now);var storage=new LocalArtifactObjectStorageGateway(root);var properties=new ArtifactObjectStorageProperties();properties.setMaximumObjectBytes(5);properties.setMaximumActiveStagingSessionsPerUser(1);properties.setMaximumActiveStagingBytesPerUser(5);properties.setMaximumActiveStagingSessionsPerTenant(2);properties.setMaximumActiveStagingBytesPerTenant(10);properties.setMaximumStoredBytesPerTenant(5);AtomicInteger sequence=new AtomicInteger();var service=new ManagedArtifactObjectApplicationService(repo,storage,(t,a,type,id)->true,new ArtifactObjectMaintenanceApplicationService(repo,storage,()->uuid(sequence.incrementAndGet()+100)),(t,a)->t.equals("tenant"),()->uuid(sequence.incrementAndGet()),properties);assertThatThrownBy(()->service.beginStaging(new ArtifactObjectApplicationApi.BeginStagingCommand("tenant","owner","too-large",hash("123456"),6,"text/plain",300))).isInstanceOfSatisfying(com.spaceagent.shared.exception.BusinessException.class,error->assertThat(error.getCode()).isEqualTo("ARTIFACT_OBJECT_SIZE_LIMIT"));var staging=service.beginStaging(new ArtifactObjectApplicationApi.BeginStagingCommand("tenant","owner","first",hash("hello"),5,"text/plain",300));assertThatThrownBy(()->service.beginStaging(new ArtifactObjectApplicationApi.BeginStagingCommand("tenant","owner","second",hash("x"),1,"text/plain",300))).isInstanceOfSatisfying(com.spaceagent.shared.exception.BusinessException.class,error->assertThat(error.getCode()).isEqualTo("ARTIFACT_USER_STAGING_QUOTA_EXCEEDED"));service.upload(new ArtifactObjectApplicationApi.UploadChunkCommand("tenant","owner",staging.id(),0,Base64.getEncoder().encodeToString("hello".getBytes(StandardCharsets.UTF_8))));var verified=service.verify(new ArtifactObjectApplicationApi.VerifyStagingCommand("tenant","owner",staging.id(),staging.revision()));service.publish(new ArtifactObjectApplicationApi.PublishStagingCommand("tenant","owner",staging.id(),verified.revision(),now.plusSeconds(60),true));assertThatThrownBy(()->service.beginStaging(new ArtifactObjectApplicationApi.BeginStagingCommand("tenant","other","tenant-full",hash("x"),1,"text/plain",300))).isInstanceOfSatisfying(com.spaceagent.shared.exception.BusinessException.class,error->assertThat(error.getCode()).isEqualTo("ARTIFACT_TENANT_STORAGE_QUOTA_EXCEEDED"));}
    private static String hash(String value){try{return "sha256:"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static String uuid(int n){return "00000000-0000-4000-8000-"+String.format("%012d",n);}
    private static final class FailOnceRepository extends InMemoryArtifactObjectRepository{private boolean fail=true;private FailOnceRepository(Instant now){super(()->now);}@Override public synchronized ArtifactObjectRepository.PublishResult publish(String tenant,String staging,long revision,ManagedArtifactObject object,Instant at,long maximum){if(fail){fail=false;throw new IllegalStateException("metadata unavailable");}return super.publish(tenant,staging,revision,object,at,maximum);}}
}
