package com.spaceagent.platform.artifact;

import com.spaceagent.platform.artifact.domain.ArtifactObjectStorageGateway;
import com.spaceagent.platform.artifact.infrastructure.*;
import org.junit.jupiter.api.Test;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import static org.assertj.core.api.Assertions.*;

class S3ArtifactObjectStorageGatewayTest {
    @Test void fakeS3StagesVerifiesComposesAndReads(){var fake=new FakeS3();var gateway=new S3ArtifactObjectStorageGateway(fake);byte[] bytes="hello".getBytes(StandardCharsets.UTF_8);var stage=gateway.createStaging(new ArtifactObjectStorageGateway.CreateStagingCommand("tenant",UUID.randomUUID().toString(),bytes.length));gateway.write(new ArtifactObjectStorageGateway.WriteCommand("tenant",stage.stagingReference(),0,bytes,bytes.length));String ref=gateway.publish(new ArtifactObjectStorageGateway.PublishCommand("tenant",stage.stagingReference(),hash("hello"),bytes.length,"tenant-key:v1")).storageReference();assertThat(gateway.verify(new ArtifactObjectStorageGateway.VerifyCommand("tenant",stage.stagingReference(),hash("hello"),bytes.length)).byteSize()).isEqualTo(bytes.length);assertThat(new String(gateway.read(new ArtifactObjectStorageGateway.ReadQuery("tenant",ref,0,5)).bytes(),StandardCharsets.UTF_8)).isEqualTo("hello");assertThat(fake.composeCalls).isEqualTo(1);}
    @Test void identicalContentHasIndependentPublicationWithoutOverwrite(){var fake=new FakeS3();var gateway=new S3ArtifactObjectStorageGateway(fake);String one=publish(gateway,"same"),two=publish(gateway,"same");assertThat(two).isNotEqualTo(one);assertThat(fake.composeCalls).isEqualTo(2);}
    @Test void offsetMismatchAndOversizedChunksFailClosed(){var gateway=new S3ArtifactObjectStorageGateway(new FakeS3());var stage=gateway.createStaging(new ArtifactObjectStorageGateway.CreateStagingCommand("tenant",uuid(3),10));assertThatThrownBy(()->gateway.write(new ArtifactObjectStorageGateway.WriteCommand("tenant",stage.stagingReference(),1,new byte[]{1},10))).isInstanceOf(IllegalStateException.class);assertThatThrownBy(()->gateway.write(new ArtifactObjectStorageGateway.WriteCommand("tenant",stage.stagingReference(),0,new byte[LocalArtifactObjectStorageGateway.MAX_CHUNK_BYTES+1],10))).isInstanceOf(IllegalArgumentException.class);}
    @Test void presignedCapabilityIsExactGetAndAtMostFiveMinutes(){var fake=new FakeS3();var gateway=new S3ArtifactObjectStorageGateway(fake);String ref=publish(gateway,"signed");assertThatThrownBy(()->gateway.presignDownload(new ArtifactObjectStorageGateway.PresignDownloadQuery("tenant",ref,301))).isInstanceOf(IllegalArgumentException.class);var capability=gateway.presignDownload(new ArtifactObjectStorageGateway.PresignDownloadQuery("tenant",ref,300));assertThat(capability.url()).contains("method=GET","ttl=300");assertThat(fake.lastPresignedKey).doesNotContain("staging");}
    @Test void anotherTenantCannotResolveTheSameOpaqueReference(){var fake=new FakeS3();var gateway=new S3ArtifactObjectStorageGateway(fake);String ref=publish(gateway,"private");assertThatThrownBy(()->gateway.read(new ArtifactObjectStorageGateway.ReadQuery("other",ref,0,10))).isInstanceOf(IllegalStateException.class);}
    private static String publish(S3ArtifactObjectStorageGateway gateway,String value){byte[] bytes=value.getBytes(StandardCharsets.UTF_8);var stage=gateway.createStaging(new ArtifactObjectStorageGateway.CreateStagingCommand("tenant",UUID.randomUUID().toString(),bytes.length));gateway.write(new ArtifactObjectStorageGateway.WriteCommand("tenant",stage.stagingReference(),0,bytes,bytes.length));return gateway.publish(new ArtifactObjectStorageGateway.PublishCommand("tenant",stage.stagingReference(),hash(value),bytes.length,"tenant-key:v1")).storageReference();}
    private static String hash(String value){try{return "sha256:"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static String uuid(int n){return "00000000-0000-4000-8000-"+String.format("%012d",n);}
    private static final class FakeS3 implements ArtifactObjectS3Client{final Map<String,byte[]> values=new HashMap<>();int composeCalls;String lastPresignedKey;public void put(String key,byte[] bytes,String media){values.put(key,bytes.clone());}public Optional<ObjectInfo> stat(String key){return Optional.ofNullable(values.get(key)).map(v->new ObjectInfo(key,v.length));}public byte[] read(String key,long offset,int max){byte[] value=values.get(key);if(value==null)throw new IllegalStateException("missing");return Arrays.copyOfRange(value,(int)offset,Math.min(value.length,(int)offset+max));}public List<ObjectInfo> list(String prefix){return values.entrySet().stream().filter(e->e.getKey().startsWith(prefix)).sorted(Map.Entry.comparingByKey()).map(e->new ObjectInfo(e.getKey(),e.getValue().length)).toList();}public void compose(String target,List<String> sources){composeCalls++;int size=sources.stream().mapToInt(k->values.get(k).length).sum();byte[] joined=new byte[size];int offset=0;for(String key:sources){byte[] value=values.get(key);System.arraycopy(value,0,joined,offset,value.length);offset+=value.length;}if(values.putIfAbsent(target,joined)!=null)throw new IllegalStateException("overwrite");}public void delete(String key){values.remove(key);}public String presignGet(String key,int ttl){lastPresignedKey=key;return "https://fixture.invalid/"+key+"?method=GET&ttl="+ttl;}}
}
