package com.spaceagent.platform.integration.infrastructure.http;

import com.spaceagent.platform.identity.api.IdentityApplicationApi;import com.spaceagent.platform.identity.domain.*;import com.spaceagent.platform.inference.api.InferenceBudgetApplicationApi;import com.spaceagent.shared.api.ApiResponse;import com.spaceagent.shared.exception.BusinessException;import jakarta.validation.Valid;import jakarta.validation.constraints.PositiveOrZero;import org.springframework.http.HttpStatus;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/inference-budget") public class PlatformInferenceBudgetHttpController{
 private final InferenceBudgetApplicationApi budget;private final IdentityApplicationApi identity;public PlatformInferenceBudgetHttpController(InferenceBudgetApplicationApi b,IdentityApplicationApi i){budget=b;identity=i;}
 @GetMapping("/policy") public ApiResponse<InferenceBudgetApplicationApi.PolicyView> policy(Authentication a){return ApiResponse.ok(budget.policy(PlatformHttpSupport.tenantId(a)));}
 @PutMapping("/policy") public ApiResponse<InferenceBudgetApplicationApi.PolicyView> configure(@Valid @RequestBody Request r,Authentication a){PlatformHttpSupport.requireWrite(a);String t=PlatformHttpSupport.tenantId(a),u=PlatformHttpSupport.userId(a);var m=identity.findTenantMembership(t,u).filter(v->v.status()==TenantMembershipStatus.ACTIVE).orElseThrow(PlatformInferenceBudgetHttpController::denied);if(m.role()!=TenantRole.OWNER&&m.role()!=TenantRole.ADMIN)throw denied();return ApiResponse.ok(budget.configure(new InferenceBudgetApplicationApi.ConfigurePolicyCommand(t,u,r.enabled(),r.monthlyRequestLimit(),r.monthlyTokenLimit(),r.monthlyCostLimitMicros())));}
 @GetMapping("/usage") public ApiResponse<InferenceBudgetApplicationApi.UsageView> usage(Authentication a){return ApiResponse.ok(budget.usage(PlatformHttpSupport.tenantId(a)));}
 public record Request(boolean enabled,@PositiveOrZero long monthlyRequestLimit,@PositiveOrZero long monthlyTokenLimit,@PositiveOrZero long monthlyCostLimitMicros){}private static BusinessException denied(){return new BusinessException("Organization manager required",HttpStatus.FORBIDDEN,"INFERENCE_BUDGET_ACCESS_DENIED");}
}
