package com.spaceagent.platform.integration.infrastructure.http;
import com.spaceagent.platform.tooling.api.GithubMcpApplicationApi;import com.spaceagent.shared.api.ApiResponse;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/github-mcp") public class PlatformGithubMcpHttpController{
 private final GithubMcpApplicationApi api;public PlatformGithubMcpHttpController(GithubMcpApplicationApi a){api=a;}
 @PostMapping("/connections/{id}/oauth/begin") public ApiResponse<GithubMcpApplicationApi.OAuthView> begin(@PathVariable String id,@Valid @RequestBody BeginRequest r,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(api.beginOAuth(new GithubMcpApplicationApi.BeginOAuthCommand(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),id,r.redirectUri())));}
 @PostMapping("/oauth/complete") public ApiResponse<GithubMcpApplicationApi.AccountView> complete(@Valid @RequestBody CompleteRequest r,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(api.completeOAuth(new GithubMcpApplicationApi.CompleteOAuthCommand(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),r.state(),r.code())));}
 @GetMapping("/connections/{id}/repositories") public ApiResponse<List<GithubMcpApplicationApi.RepositoryView>> repositories(@PathVariable String id,Authentication a){return ApiResponse.ok(api.repositories(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),id));}
 @PostMapping("/discover") public ApiResponse<GithubMcpApplicationApi.RepositoryView> discover(@Valid @RequestBody DiscoverRequest r,Authentication a){return ApiResponse.ok(api.discover(new GithubMcpApplicationApi.DiscoverCommand(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),r.connectionId(),r.githubUrl())));}
 public record BeginRequest(@NotBlank @Size(max=1000) String redirectUri){}public record CompleteRequest(@NotBlank @Size(max=512) String state,@Size(max=2048) String code){}public record DiscoverRequest(@NotBlank String connectionId,@NotBlank @Size(max=1000) String githubUrl){}
}
