package com.spaceagent.platform.integration.infrastructure.http;import com.spaceagent.platform.artifact.api.ArtifactApplicationApi;import com.spaceagent.platform.project.domain.WorkspaceCodingGateway;import com.spaceagent.platform.runtime.api.CodingRuntimeApplicationApi;import com.spaceagent.shared.api.ApiResponse;import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import jakarta.validation.constraints.NotNull;import org.springframework.http.HttpStatus;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/coding") public class PlatformCodingRuntimeHttpController{private final CodingRuntimeApplicationApi api;public PlatformCodingRuntimeHttpController(CodingRuntimeApplicationApi a){api=a;}
@PostMapping("/runs") @ResponseStatus(HttpStatus.CREATED) public ApiResponse<CodingRuntimeApplicationApi.CodingRunView> start(@Valid @RequestBody StartRequest r,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(api.start(new CodingRuntimeApplicationApi.StartCommand(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),r.agentId(),null,r.conversationId(),r.projectId(),r.taskId(),r.taskPlanId(),r.planStepId(),r.workspaceId())));}
@PostMapping("/runs/{runId}/actions") public ApiResponse<CodingRuntimeApplicationApi.CodingActionView> action(@PathVariable String runId,@Valid @RequestBody ActionRequest r,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(api.execute(new CodingRuntimeApplicationApi.ActionCommand(PlatformHttpSupport.userId(a),runId,r.workspaceId(),r.toolCallId(),r.type(),r.relativePath(),r.content(),r.executable(),r.arguments(),r.timeoutSeconds(),r.approvalId())));}
@PostMapping("/runs/{runId}/evidence") public ApiResponse<CodingRuntimeApplicationApi.CodingActionView> evidence(@PathVariable String runId,@Valid @RequestBody EvidenceRequest r,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(api.evidence(new CodingRuntimeApplicationApi.EvidenceCommand(PlatformHttpSupport.userId(a),runId,r.workspaceId(),r.criterion(),r.passed(),r.details())));}
@PostMapping("/runs/{runId}/finalize") public ApiResponse<CodingRuntimeApplicationApi.CodingRunView> finalizeRun(@PathVariable String runId,@Valid @RequestBody FinalizeRequest r,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(api.finalizeRun(new CodingRuntimeApplicationApi.FinalizeCommand(PlatformHttpSupport.userId(a),runId,r.workspaceId(),r.commitMessage())));}
@GetMapping("/runs/{runId}/artifacts") public ApiResponse<List<ArtifactApplicationApi.ArtifactView>> artifacts(@PathVariable String runId,Authentication a){return ApiResponse.ok(api.artifacts(PlatformHttpSupport.userId(a),runId));}
public record StartRequest(@NotBlank String agentId,@NotBlank String conversationId,@NotBlank String projectId,@NotBlank String taskId,@NotBlank String taskPlanId,@NotBlank String planStepId,@NotBlank String workspaceId){}public record ActionRequest(@NotBlank String workspaceId,@NotBlank String toolCallId,@NotNull WorkspaceCodingGateway.Type type,String relativePath,String content,String executable,List<String> arguments,int timeoutSeconds,String approvalId){}public record EvidenceRequest(@NotBlank String workspaceId,@NotBlank String criterion,boolean passed,@NotBlank String details){}public record FinalizeRequest(@NotBlank String workspaceId,@NotBlank String commitMessage){}
}
