package com.spaceagent.platform.integration.infrastructure.http;
import com.spaceagent.platform.project.api.ProjectBlueprintApplicationApi;import com.spaceagent.platform.project.domain.*;import com.spaceagent.shared.api.ApiResponse;import jakarta.validation.Valid;import jakarta.validation.constraints.NotNull;import org.springframework.http.HttpStatus;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/projects/{projectId}/blueprints") public class PlatformProjectBlueprintHttpController{
 private final ProjectBlueprintApplicationApi api;public PlatformProjectBlueprintHttpController(ProjectBlueprintApplicationApi a){api=a;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) public ApiResponse<ProjectBlueprintApplicationApi.BlueprintView> create(@PathVariable String projectId,@Valid @RequestBody CreateRequest r,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(api.create(new ProjectBlueprintApplicationApi.CreateCommand(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),projectId,r.sourceRepositoryId(),r.generatedByAgentId(),r.generatedByRunConfigurationSnapshotId(),r.source(),r.document())));}
 @PostMapping("/{id}/confirm") public ApiResponse<ProjectBlueprintApplicationApi.BlueprintView> confirm(@PathVariable String projectId,@PathVariable String id,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(api.confirm(new ProjectBlueprintApplicationApi.ConfirmCommand(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),projectId,id)));}
 @GetMapping public ApiResponse<List<ProjectBlueprintApplicationApi.BlueprintView>> list(@PathVariable String projectId,Authentication a){return ApiResponse.ok(api.list(new ProjectBlueprintApplicationApi.ListQuery(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),projectId)));}
 public record CreateRequest(String sourceRepositoryId,String generatedByAgentId,String generatedByRunConfigurationSnapshotId,@NotNull ProjectBlueprintSource source,@NotNull ProjectBlueprintDocument document){}
}
