package com.spaceagent.platform.integration.infrastructure.http;
import com.spaceagent.platform.project.api.WorkspaceApplicationApi;import com.spaceagent.shared.api.ApiResponse;import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import org.springframework.http.HttpStatus;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController public class PlatformWorkspaceHttpController{
 private final WorkspaceApplicationApi api;public PlatformWorkspaceHttpController(WorkspaceApplicationApi a){api=a;}
 @PostMapping("/api/v1/projects/{projectId}/workspaces") @ResponseStatus(HttpStatus.CREATED) public ApiResponse<WorkspaceApplicationApi.WorkspaceView> provision(@PathVariable String projectId,@Valid @RequestBody ProvisionRequest r,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(present(api.provision(new WorkspaceApplicationApi.ProvisionCommand(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),projectId,r.projectDirectoryId(),r.taskId(),r.sourceRepositoryId(),r.baseRef(),"primary"))));}
 @GetMapping("/api/v1/projects/{projectId}/workspaces") public ApiResponse<List<WorkspaceApplicationApi.WorkspaceView>> list(@PathVariable String projectId,Authentication a){return ApiResponse.ok(api.list(new WorkspaceApplicationApi.ListQuery(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),projectId)).stream().map(PlatformWorkspaceHttpController::present).toList());}
 @DeleteMapping("/api/v1/projects/{projectId}/workspaces/{id}") public ApiResponse<WorkspaceApplicationApi.WorkspaceView> archive(@PathVariable String projectId,@PathVariable String id,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(present(api.archive(new WorkspaceApplicationApi.ArchiveCommand(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),projectId,id))));}
 @GetMapping("/api/v1/workspace-bridges/{bridgeId}/workspace-commands") public ApiResponse<List<WorkspaceApplicationApi.BridgeCommandView>> commands(@PathVariable String bridgeId,Authentication a){return ApiResponse.ok(api.pendingBridgeCommands(new WorkspaceApplicationApi.BridgeCommandsQuery(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),bridgeId)));}
 @PostMapping("/api/v1/workspace-bridges/workspace-commands/{commandId}/complete") public ApiResponse<WorkspaceApplicationApi.WorkspaceView> complete(@PathVariable String commandId,@RequestHeader("X-SpaceAgent-Bridge-Token") String token,@Valid @RequestBody CompleteRequest r,Authentication a){PlatformHttpSupport.requireWrite(a);return ApiResponse.ok(present(api.completeBridge(new WorkspaceApplicationApi.CompleteBridgeCommand(PlatformHttpSupport.tenantId(a),PlatformHttpSupport.userId(a),commandId,token,r.opaqueLocator(),r.headCommit(),r.success(),r.failureReason()))));}
 private static WorkspaceApplicationApi.WorkspaceView present(WorkspaceApplicationApi.WorkspaceView w) {
  return new WorkspaceApplicationApi.WorkspaceView(w.id(),w.projectId(),w.projectDirectoryId(),w.taskId(),w.sourceRepositoryId(),w.bridgeId(),w.isolationKey(),w.mode(),w.worktreeKey(),com.spaceagent.platform.project.domain.RepositoryBranchVisibility.publicRef(w.baseRef()),null,w.worktreeRef(),w.headCommit(),w.writable(),w.state(),w.failureReason(),w.revision(),w.createdAt(),w.updatedAt());
 }
 public record ProvisionRequest(String projectDirectoryId,@NotBlank String taskId,@NotBlank String sourceRepositoryId,String baseRef){}public record CompleteRequest(String opaqueLocator,String headCommit,boolean success,String failureReason){}
}
