package com.spaceagent.platform.artifact.infrastructure;

import com.spaceagent.platform.artifact.domain.ArtifactObjectStorageGateway;
import com.spaceagent.platform.artifact.domain.ManagedArtifactObject;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.HexFormat;

@Component
@ConditionalOnProperty(prefix="platform.artifact-object",name="mode",havingValue="local",matchIfMissing=true)
public class LocalArtifactObjectStorageGateway implements ArtifactObjectStorageGateway {
    public static final int MAX_CHUNK_BYTES=5*1024*1024;public static final int MAX_READ_BYTES=1024*1024;
    private final Path root;
    @org.springframework.beans.factory.annotation.Autowired
    public LocalArtifactObjectStorageGateway(ArtifactObjectStorageProperties properties){this(Path.of(properties.getLocalRoot()));}
    public LocalArtifactObjectStorageGateway(Path root){this.root=root.toAbsolutePath().normalize();}
    @Override public synchronized StagingHandle createStaging(CreateStagingCommand c){uuid(c.stagingId());bounds(c.expectedBytes(),ManagedArtifactObject.MAX_BYTES);Path file=staging(c.stagingId());try{Files.createDirectories(file.getParent());if(!Files.exists(file))Files.createFile(file);else if(!Files.isRegularFile(file,LinkOption.NOFOLLOW_LINKS))throw new IllegalStateException();return new StagingHandle("artifact-staging:"+c.stagingId());}catch(Exception e){throw failure("Artifact staging create failed",e);}}
    @Override public synchronized WriteResult write(WriteCommand c){Path file=stagingRef(c.stagingReference());if(c.bytes().length==0||c.bytes().length>MAX_CHUNK_BYTES||c.maximumBytes()<0||c.maximumBytes()>ManagedArtifactObject.MAX_BYTES)throw new IllegalArgumentException("Artifact staging chunk is invalid");try{long size=Files.size(file);if(size!=c.expectedOffset()||Math.addExact(size,c.bytes().length)>c.maximumBytes())throw new IllegalStateException("Artifact staging offset or size conflict");try(FileChannel channel=FileChannel.open(file,StandardOpenOption.WRITE)){channel.position(size);ByteBuffer value=ByteBuffer.wrap(c.bytes());while(value.hasRemaining())channel.write(value);channel.force(true);}return new WriteResult(size+c.bytes().length);}catch(RuntimeException e){throw e;}catch(Exception e){throw failure("Artifact staging write failed",e);}}
    @Override public synchronized Verification verify(VerifyCommand c){ManagedArtifactObjectHash.require(c.expectedSha256());Path file=stagingRef(c.stagingReference());try{long size=Files.size(file);String hash=hash(file);if(size!=c.expectedBytes()||!hash.equals(c.expectedSha256()))throw new IllegalStateException("Artifact staging verification mismatch");return new Verification(hash,size);}catch(RuntimeException e){throw e;}catch(Exception e){throw failure("Artifact staging verification failed",e);}}
    @Override public synchronized PublishResult publish(PublishCommand c){ManagedArtifactObjectHash.require(c.contentSha256());bounds(c.byteSize(),ManagedArtifactObject.MAX_BYTES);ManagedArtifactObjectHash.opaque(c.encryptionReference(),"tenant-key:");Path source=stagingRef(c.stagingReference());Path temporary=null;try{if(Files.size(source)!=c.byteSize()||!hash(source).equals(c.contentSha256()))throw new IllegalStateException("Artifact staging changed before publish");String key=sha256(c.tenantId()+"\n"+c.encryptionReference()+"\n"+c.contentSha256()+"\n"+c.byteSize()+"\npublication:"+c.stagingReference());Path target=under(root.resolve("objects").resolve(key.substring(0,2)).resolve(key));Files.createDirectories(target.getParent());if(Files.exists(target,LinkOption.NOFOLLOW_LINKS)){if(!Files.isRegularFile(target,LinkOption.NOFOLLOW_LINKS)||Files.size(target)!=c.byteSize()||!hash(target).equals(c.contentSha256()))throw new IllegalStateException("Artifact content-address collision");return new PublishResult("artifact-object:"+key,true);}temporary=Files.createTempFile(target.getParent(),key+"-",".publishing");Files.copy(source,temporary,StandardCopyOption.REPLACE_EXISTING);if(Files.size(temporary)!=c.byteSize()||!hash(temporary).equals(c.contentSha256()))throw new IllegalStateException("Artifact publish copy mismatch");boolean reused=false;try{Files.move(temporary,target,StandardCopyOption.ATOMIC_MOVE);temporary=null;}catch(FileAlreadyExistsException exists){if(!Files.isRegularFile(target,LinkOption.NOFOLLOW_LINKS)||Files.size(target)!=c.byteSize()||!hash(target).equals(c.contentSha256()))throw new IllegalStateException("Artifact content-address collision");reused=true;}return new PublishResult("artifact-object:"+key,reused);}catch(RuntimeException e){throw e;}catch(Exception e){throw failure("Artifact publish failed",e);}finally{if(temporary!=null)try{Files.deleteIfExists(temporary);}catch(Exception ignored){}}}
    @Override public ReadResult read(ReadQuery q){Path file=objectRef(q.storageReference());if(q.offset()<0||q.maximumBytes()<1||q.maximumBytes()>MAX_READ_BYTES)throw new IllegalArgumentException("Artifact read range is invalid");try{long total=Files.size(file);if(q.offset()>total)throw new IllegalArgumentException("Artifact read offset is invalid");int count=(int)Math.min(q.maximumBytes(),total-q.offset());byte[] bytes=new byte[count];try(FileChannel channel=FileChannel.open(file,StandardOpenOption.READ)){channel.position(q.offset());ByteBuffer value=ByteBuffer.wrap(bytes);while(value.hasRemaining()&&channel.read(value)>=0){}}return new ReadResult(bytes,total,q.offset()+count<total);}catch(RuntimeException e){throw e;}catch(Exception e){throw failure("Artifact read failed",e);}}
    @Override public synchronized void deleteStaging(DeleteStagingCommand c){Path target=stagingRef(c.stagingReference());try{Files.deleteIfExists(target);}catch(Exception e){throw failure("Artifact staging delete failed",e);}}
    @Override public synchronized void deleteObject(DeleteObjectCommand c){Path target=objectRef(c.storageReference());try{Files.deleteIfExists(target);}catch(Exception e){throw failure("Artifact object delete failed",e);}}
    private Path stagingRef(String ref){ManagedArtifactObjectHash.opaque(ref,"artifact-staging:");return staging(ref.substring("artifact-staging:".length()));}private Path objectRef(String ref){if(ref==null||!ref.matches("artifact-object:[0-9a-f]{64}"))throw new IllegalArgumentException("Artifact object reference is invalid");return under(root.resolve("objects").resolve(ref.substring(16,18)).resolve(ref.substring(16)));}private Path staging(String id){uuid(id);return under(root.resolve("staging").resolve(id+".partial"));}private Path under(Path value){Path normalized=value.toAbsolutePath().normalize();if(!normalized.startsWith(root)||Files.isSymbolicLink(normalized))throw new IllegalArgumentException("Artifact storage reference escaped root");return normalized;}
    private static String hash(Path file)throws Exception{MessageDigest digest=MessageDigest.getInstance("SHA-256");try(InputStream input=Files.newInputStream(file)){byte[] buffer=new byte[8192];for(int read;(read=input.read(buffer))>=0;)digest.update(buffer,0,read);}return "sha256:"+HexFormat.of().formatHex(digest.digest());}private static String sha256(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static void uuid(String value){try{java.util.UUID.fromString(value);}catch(Exception e){throw new IllegalArgumentException("Artifact staging identifier is invalid");}}private static void bounds(long value,long maximum){if(value<0||value>maximum)throw new IllegalArgumentException("Artifact byte size is invalid");}private static IllegalStateException failure(String message,Exception error){return new IllegalStateException(message,error);}
    private static final class ManagedArtifactObjectHash{static void require(String value){if(value==null||!value.matches("sha256:[0-9a-f]{64}"))throw new IllegalArgumentException("Artifact hash is invalid");}static void opaque(String value,String prefix){if(value==null||!value.matches(java.util.regex.Pattern.quote(prefix)+"[A-Za-z0-9_.:-]{1,300}"))throw new IllegalArgumentException("Artifact opaque reference is invalid");}}
}
