package com.spaceagent.platform.artifact.infrastructure;

import com.spaceagent.platform.artifact.domain.ArtifactObjectStorageGateway;
import com.spaceagent.platform.artifact.domain.ManagedArtifactObject;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;
import java.io.ByteArrayInputStream;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;

@Component
@ConditionalOnProperty(prefix="platform.artifact-object",name="mode",havingValue="s3")
public class S3ArtifactObjectStorageGateway implements ArtifactObjectStorageGateway {
    private static final int MAX_CHUNKS=1000;private final ArtifactObjectS3Client client;
    public S3ArtifactObjectStorageGateway(ArtifactObjectS3Client client){this.client=client;}
    @Override public StagingHandle createStaging(CreateStagingCommand c){uuid(c.stagingId());size(c.expectedBytes());String ref="artifact-staging:"+c.stagingId();client.put(prefix(c.tenantId(),ref)+".open",new byte[0],"application/octet-stream");return new StagingHandle(ref);}
    @Override public WriteResult write(WriteCommand c){if(c.bytes().length<1||c.bytes().length>LocalArtifactObjectStorageGateway.MAX_CHUNK_BYTES||c.maximumBytes()<0||c.maximumBytes()>ManagedArtifactObject.MAX_BYTES)throw new IllegalArgumentException("S3 staging chunk is invalid");List<ArtifactObjectS3Client.ObjectInfo> chunks=chunks(c.tenantId(),c.stagingReference());long current=chunks.stream().mapToLong(ArtifactObjectS3Client.ObjectInfo::byteSize).sum();long next=Math.addExact(current,c.bytes().length);if(current!=c.expectedOffset()||next>c.maximumBytes()||chunks.size()>=MAX_CHUNKS||(next<c.maximumBytes()&&c.bytes().length<LocalArtifactObjectStorageGateway.MAX_CHUNK_BYTES))throw new IllegalStateException("S3 staging offset or size conflict");client.put(chunkPrefix(c.tenantId(),c.stagingReference())+String.format("%020d",current),c.bytes(),"application/octet-stream");return new WriteResult(next);}
    @Override public Verification verify(VerifyCommand c){hash(c.expectedSha256());List<ArtifactObjectS3Client.ObjectInfo> chunks=chunks(c.tenantId(),c.stagingReference());try{MessageDigest digest=MessageDigest.getInstance("SHA-256");long total=0;for(var item:chunks){byte[] bytes=client.read(item.key(),0,Math.toIntExact(item.byteSize()));if(bytes.length!=item.byteSize())throw new IllegalStateException("S3 staging read is incomplete");digest.update(bytes);total+=bytes.length;}String actual="sha256:"+HexFormat.of().formatHex(digest.digest());if(total!=c.expectedBytes()||!actual.equals(c.expectedSha256()))throw new IllegalStateException("S3 staging verification mismatch");return new Verification(actual,total);}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalStateException("S3 staging verification failed",e);}}
    @Override public PublishResult publish(PublishCommand c){hash(c.contentSha256());size(c.byteSize());opaque(c.encryptionReference(),"tenant-key:");Verification verified=verify(new VerifyCommand(c.tenantId(),c.stagingReference(),c.contentSha256(),c.byteSize()));String key=objectKey(c.tenantId(),c.contentSha256(),c.byteSize(),c.encryptionReference(),c.stagingReference());boolean reused=client.stat(key).map(value->{if(value.byteSize()!=verified.byteSize())throw new IllegalStateException("S3 content-address collision");return true;}).orElse(false);if(!reused){List<String> sources=chunks(c.tenantId(),c.stagingReference()).stream().map(ArtifactObjectS3Client.ObjectInfo::key).toList();if(sources.isEmpty())client.put(key,new byte[0],"application/octet-stream");else client.compose(key,sources);}return new PublishResult("artifact-object:"+key.substring(key.lastIndexOf('/')+1),reused);}
    @Override public ReadResult read(ReadQuery q){String key=objectKey(q.tenantId(),q.storageReference());var stat=client.stat(key).orElseThrow(()->new IllegalStateException("Artifact object is unavailable"));if(q.offset()<0||q.offset()>stat.byteSize()||q.maximumBytes()<1||q.maximumBytes()>LocalArtifactObjectStorageGateway.MAX_READ_BYTES)throw new IllegalArgumentException("Artifact read range is invalid");int count=(int)Math.min(q.maximumBytes(),stat.byteSize()-q.offset());byte[] bytes=client.read(key,q.offset(),count);if(bytes.length!=count)throw new IllegalStateException("S3 object read is incomplete");return new ReadResult(bytes,stat.byteSize(),q.offset()+count<stat.byteSize());}
    @Override public void deleteStaging(DeleteStagingCommand c){for(var value:client.list(prefix(c.tenantId(),c.stagingReference())))client.delete(value.key());}
    @Override public void deleteObject(DeleteObjectCommand c){client.delete(objectKey(c.tenantId(),c.storageReference()));}
    @Override public DownloadCapability presignDownload(PresignDownloadQuery q){if(q.ttlSeconds()<1||q.ttlSeconds()>300)throw new IllegalArgumentException("Artifact download capability TTL is invalid");String key=objectKey(q.tenantId(),q.storageReference());if(client.stat(key).isEmpty())throw new IllegalStateException("Artifact object is unavailable");return new DownloadCapability(client.presignGet(key,q.ttlSeconds()),Instant.now().plusSeconds(q.ttlSeconds()));}
    private List<ArtifactObjectS3Client.ObjectInfo> chunks(String tenant,String ref){List<ArtifactObjectS3Client.ObjectInfo> values=client.list(chunkPrefix(tenant,ref));if(values.size()>MAX_CHUNKS)throw new IllegalStateException("S3 staging chunk limit exceeded");return values;}
    private static String chunkPrefix(String tenant,String ref){return prefix(tenant,ref)+"chunks/";}private static String prefix(String tenant,String ref){opaque(ref,"artifact-staging:");return "staging/"+digest(tenant)+"/"+ref.substring(17)+"/";}private static String objectKey(String tenant,String hash,long bytes,String encryption,String staging){return "objects/"+digest(tenant)+"/"+digest(encryption+"\n"+hash+"\n"+bytes+"\npublication:"+staging);}private static String objectKey(String tenant,String ref){if(ref==null||!ref.matches("artifact-object:[0-9a-f]{64}"))throw new IllegalArgumentException("Artifact object reference is invalid");return "objects/"+digest(tenant)+"/"+ref.substring(16);}private static String digest(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static void hash(String value){if(value==null||!value.matches("sha256:[0-9a-f]{64}"))throw new IllegalArgumentException("Artifact hash is invalid");}private static void opaque(String value,String prefix){if(value==null||!value.matches(java.util.regex.Pattern.quote(prefix)+"[A-Za-z0-9_.:-]{1,300}"))throw new IllegalArgumentException("Artifact reference is invalid");}private static void uuid(String value){try{UUID.fromString(value);}catch(Exception e){throw new IllegalArgumentException("Artifact staging identifier is invalid");}}private static void size(long value){if(value<0||value>ManagedArtifactObject.MAX_BYTES)throw new IllegalArgumentException("Artifact size is invalid");}
}
